export default {
  'negara kepulauan terbesar di dunia dengan lebih dari': 'the world\'s largest archipelago, with more than',
  'negara kepulauan terbesar di dunia': 'the world\'s largest archipelago',
  'negara kepulauan': 'an archipelago',
  'negara kerajaan': 'a kingdom',
  'negara kota di asia tenggara yang terkenal sebagai pusat keuangan global': 'a city-state in Southeast Asia famous as a global financial center',
  'negara kota': 'a city-state',
  'negara federasi': 'a federal country',
  'negara dengan ekonomi terbesar di asia tenggara': 'the largest economy in Southeast Asia',
  'negara dengan ekonomi paling kompetitif di dunia': 'one of the most competitive economies in the world',
  'negara dengan': 'a country with',
  'segera pindah ke': 'soon moving to',
  'kaya akan sumber daya alam, budaya, dan keanekaragaman hayati': 'rich in natural resources, culture, and biodiversity',
  'kaya akan sumber daya alam': 'rich in natural resources',
  'keanekaragaman hayati': 'biodiversity',
  'sumber daya alam': 'natural resources',
  'rumah bagi': 'home to',
  'destinasi wisata': 'tourist destinations',
  'sistem pemerintahan': 'government system',
  'republik presidensial': 'presidential republic',
  'republik parlementer': 'parliamentary republic',
  'monarki konstitusional federal': 'federal constitutional monarchy',
  'monarki konstitusional': 'constitutional monarchy',
  'ibu kota': 'capital',
  'kota terbesar': 'largest city',
  'mata uang': 'currency',
  'juta jiwa': 'million people',
  'lebih dari': 'more than',
  'terkenal sebagai': 'famous as',
  'terkenal dengan': 'known for',
  'pusat keuangan global': 'a global financial center',
  'pusat keuangan': 'financial center',
  'pusat perdagangan': 'a trade hub',
  'pusat pariwisata': 'tourism hub',
  'asia tenggara': 'Southeast Asia',
  'terbesar di dunia': 'the largest in the world',
  'terbesar di': 'the largest in',
  'paling kompetitif': 'most competitive',
  'anggota': 'a member of',
  'dan': 'and',
  'dengan': 'with',
  'di': 'in',
  'yang': 'that',
  'budaya': 'culture',
  'pariwisata': 'tourism',
  'ekonomi': 'economy',
  'teknologi': 'technology',
  'inovasi': 'innovation',
  'sejarah': 'history',
  'kepulauan': 'archipelago',
  'pulau': 'islands',
  'terbesar': 'largest',
  'republik': 'republic',
  'presidensial': 'presidential',
  'parlementer': 'parliamentary',
  'monarki': 'monarchy',
  'konstitusional': 'constitutional',
  'federasi': 'federation',
  'federal': 'federal',
  'inggris': 'English',
  'mandarin': 'Mandarin',
  'melayu': 'Malay',
  'tamil': 'Tamil',
  'filipino': 'Filipino',
  'dolar singapura': 'Singapore Dollar',
  'bunga bangkai': 'the corpse flower',
  'orangutan': 'orangutans',
  'komodo': 'komodo dragons'
};
