export default {
  'negara kepulauan terbesar di dunia dengan lebih dari': 'nagara kapuloan paling gedhe ing donya, kanthi luwih saka',
  'negara kepulauan terbesar di dunia': 'nagara kapuloan paling gedhe ing donya',
  'negara kepulauan': 'nagara kapuloan',
  'negara federasi di asia tenggara yang terdiri dari': 'nagara federasi ing Asia Tenggara sing kadadeyan saka',
  'negara federasi di asia tenggara': 'nagara federasi ing Asia Tenggara',
  'negara federasi': 'nagara federasi',
  'negara kerajaan di asia tenggara yang terkenal dengan budaya dan pariwisata': 'nagara krajan ing Asia Tenggara sing misuwur amarga budaya lan pariwisata',
  'negara kerajaan': 'nagara krajan',
  'negara kota di asia tenggara yang terkenal sebagai pusat keuangan global': 'nagara kutha ing Asia Tenggara sing misuwur minangka puser keuangan global',
  'negara kota': 'nagara kutha',
  'negara dengan ekonomi terbesar di asia tenggara': 'nagara kanthi ekonomi paling gedhe ing Asia Tenggara',
  'negara dengan ekonomi paling kompetitif di dunia': 'nagara kanthi ekonomi paling kompetitif ing donya',
  'negara dengan': 'nagara kanthi',
  'terdiri dari': 'kadadeyan saka',
  'negara bagian dan': 'nagara bagean lan',
  'negara bagian': 'nagara bagean',
  'wilayah federal': 'wilayah federal',
  'pusat pemerintahan': 'puser pamaréntahan',
  'segera pindah ke': 'enggal pindhah menyang',
  'kaya akan sumber daya alam, budaya, dan keanekaragaman hayati': 'sugih sumber daya alam, budaya, lan keanekaragaman hayati',
  'kaya akan sumber daya alam': 'sugih sumber daya alam',
  'keanekaragaman hayati': 'keanekaragaman hayati',
  'sumber daya alam': 'sumber daya alam',
  'sistem pemerintahan': 'sistem pamaréntahan',
  'republik presidensial': 'republik presidensial',
  'republik parlementer': 'republik parlementer',
  'monarki konstitusional federal': 'monarki konstitusional federal',
  'monarki konstitusional': 'monarki konstitusional',
  'ibu kota': 'kutha krajan',
  'kota terbesar': 'kutha paling gedhe',
  'mata uang': 'dhuwit',
  'juta jiwa': 'yuta jiwa',
  'rumah bagi': 'omah kanggo',
  'destinasi wisata': 'papan wisata',
  'lebih dari': 'luwih saka',
  'terkenal sebagai': 'misuwur minangka',
  'terkenal dengan': 'misuwur amarga',
  'pusat keuangan global': 'puser keuangan global',
  'pusat keuangan': 'puser keuangan',
  'pusat perdagangan': 'puser dagang',
  'pusat pariwisata': 'puser pariwisata',
  'ekspor beras terbesar dunia': 'ekspor beras paling gedhe ing donya',
  'tidak pernah dijajah': 'ora nate dijajah',
  'satu-satunya negara': 'siji-sijine nagara',
  'asia tenggara': 'Asia Tenggara',
  'hutan hujan tertua di dunia': 'alas udan paling tuwa ing donya',
  'hutan hujan tertua': 'alas udan paling tuwa',
  'minyak sawit': 'minyak sawit',
  'sektor elektronik': 'sektor elektronik',
  'ekonomi maju': 'ekonomi maju',
  'anggota': 'anggota',
  'kepulauan': 'kapuloan',
  'pulau': 'pulo',
  'terbesar': 'paling gedhe',
  'dunia': 'donya',
  'budaya': 'budaya',
  'pariwisata': 'pariwisata',
  'ekonomi': 'ekonomi',
  'teknologi': 'teknologi',
  'sejarah': 'sejarah',
  'bahasa': 'basa',
  'populasi': 'cacah jiwa',
  'dan': 'lan',
  'dengan': 'kanthi',
  'di': 'ing',
  'dari': 'saka',
  'yang': 'sing',
  'untuk': 'kanggo',
  'adalah': 'yaiku',
  'merupakan': 'yaiku',
  'memiliki': 'duwe',
  'negara': 'nagara',
  'kota': 'kutha',
  'juta': 'yuta',
  'ribu': 'ewu',
  'jiwa': 'jiwa',
  'kaya': 'sugih',
  'alam': 'alam',
  'wisata': 'wisata'
};
