const data = [
  { text: 'Nelson Mandela — pemimpin Afrika Selatan, presiden kulit hitam pertama, tokoh utama perjuangan anti-apartheid.', metadata: { name: 'Nelson Mandela', field: 'pemimpin', knownFor: 'anti-apartheid, presiden Afrika Selatan', country: 'Afrika Selatan', born: '1918', tags: ['mandela', 'apartheid'] } },
  { text: 'Winston Churchill — pemimpin Inggris, Perdana Menteri yang memimpin negara itu selama Perang Dunia II.', metadata: { name: 'Winston Churchill', field: 'pemimpin', knownFor: 'PM Inggris Perang Dunia II', country: 'Inggris', born: '1874', tags: ['churchill', 'perang dunia ii'] } },
  { text: 'Abraham Lincoln — presiden ke-16 Amerika Serikat, memimpin negara melalui Perang Saudara dan menghapus perbudakan.', metadata: { name: 'Abraham Lincoln', field: 'pemimpin', knownFor: 'presiden AS, hapus perbudakan', country: 'Amerika Serikat', born: '1809', tags: ['lincoln', 'perbudakan'] } },
  { text: 'Angela Merkel — kanselir wanita pertama Jerman, memimpin negara itu selama enam belas tahun.', metadata: { name: 'Angela Merkel', field: 'pemimpin', knownFor: 'kanselir wanita pertama Jerman', country: 'Jerman', born: '1954', tags: ['merkel', 'jerman'] } },
  { text: 'Ratu Elizabeth II — raja/ratu Inggris dengan masa pemerintahan terlama dalam sejarah monarki Inggris.', metadata: { name: 'Ratu Elizabeth II', field: 'pemimpin', knownFor: 'monarki Inggris terlama', country: 'Inggris', born: '1926', tags: ['elizabeth ii', 'monarki'] } },
  { text: 'Jawaharlal Nehru — perdana menteri pertama India, memimpin negara itu pasca kemerdekaan dari Inggris.', metadata: { name: 'Jawaharlal Nehru', field: 'pemimpin', knownFor: 'PM pertama India', country: 'India', born: '1889', tags: ['nehru', 'india'] } },
  { text: 'Kwame Nkrumah — presiden pertama Ghana, tokoh penting gerakan pan-Afrikanisme dan dekolonisasi Afrika.', metadata: { name: 'Kwame Nkrumah', field: 'pemimpin', knownFor: 'presiden pertama Ghana, pan-Afrikanisme', country: 'Ghana', born: '1909', tags: ['nkrumah', 'ghana'] } },
  { text: 'Lee Kuan Yew — perdana menteri pendiri Singapura, arsitek transformasi negara itu menjadi pusat ekonomi dunia.', metadata: { name: 'Lee Kuan Yew', field: 'pemimpin', knownFor: 'PM pendiri Singapura', country: 'Singapura', born: '1923', tags: ['lee kuan yew', 'singapura'] } },
  { text: 'Simon Bolivar — pemimpin revolusi Amerika Selatan yang membebaskan beberapa negara dari kekuasaan kolonial Spanyol.', metadata: { name: 'Simon Bolivar', field: 'pemimpin', knownFor: 'pembebas Amerika Selatan', country: 'Venezuela', born: '1783', tags: ['bolivar', 'amerika selatan'] } },
  { text: 'Otto von Bismarck — negarawan Jerman yang memimpin unifikasi negara-negara Jerman menjadi satu kekaisaran pada 1871.', metadata: { name: 'Otto von Bismarck', field: 'pemimpin', knownFor: 'unifikasi Jerman', country: 'Jerman', born: '1815', tags: ['bismarck', 'unifikasi jerman'] } },
  { text: 'Golda Meir — perdana menteri wanita pertama Israel, memimpin negara itu pada masa-masa penting sejarahnya.', metadata: { name: 'Golda Meir', field: 'pemimpin', knownFor: 'PM wanita pertama Israel', country: 'Israel', born: '1898', tags: ['golda meir', 'israel'] } },
  { text: 'Justin Trudeau — perdana menteri Kanada yang dikenal dengan kebijakan progresif dan keterbukaan terhadap imigrasi.', metadata: { name: 'Justin Trudeau', field: 'pemimpin', knownFor: 'PM Kanada', country: 'Kanada', born: '1971', tags: ['trudeau', 'kanada'] } },
  { text: 'Jacinda Ardern — perdana menteri Selandia Baru, dikenal atas kepemimpinan empatik saat krisis nasional.', metadata: { name: 'Jacinda Ardern', field: 'pemimpin', knownFor: 'PM Selandia Baru', country: 'Selandia Baru', born: '1980', tags: ['ardern', 'selandia baru'] } },
  { text: 'Sun Yat-sen — bapak pendiri Republik Tiongkok, tokoh sentral revolusi yang mengakhiri era kekaisaran Tiongkok.', metadata: { name: 'Sun Yat-sen', field: 'pemimpin', knownFor: 'bapak pendiri Republik Tiongkok', country: 'Tiongkok', born: '1866', tags: ['sun yat-sen', 'tiongkok'] } },
  { text: 'Jomo Kenyatta — presiden pertama Kenya, pemimpin gerakan kemerdekaan negara itu dari penjajahan Inggris.', metadata: { name: 'Jomo Kenyatta', field: 'pemimpin', knownFor: 'presiden pertama Kenya', country: 'Kenya', born: '1897', tags: ['kenyatta', 'kenya'] } },
];

export const DATA = data;
