const data = [
  { text: 'Albert Einstein — fisikawan pencetus teori relativitas, penerima Nobel Fisika 1921. Lahir tahun 1879 di Jerman.', metadata: { name: 'Albert Einstein', field: 'fisika', knownFor: 'teori relativitas', country: 'Jerman', born: '1879', tags: ['einstein', 'fisika', 'relativitas'] } },
  { text: 'Isaac Newton — ilmuwan penemu hukum gravitasi dan hukum gerak Newton. Lahir tahun 1643 di Inggris.', metadata: { name: 'Isaac Newton', field: 'fisika', knownFor: 'hukum gravitasi', country: 'Inggris', born: '1643', tags: ['newton', 'fisika', 'gravitasi'] } },
  { text: 'Marie Curie — ilmuwan pionir radioaktivitas, satu-satunya peraih Nobel di dua bidang sains berbeda. Lahir tahun 1867 di Polandia.', metadata: { name: 'Marie Curie', field: 'fisika/kimia', knownFor: 'radioaktivitas', country: 'Polandia', born: '1867', tags: ['marie curie', 'radioaktivitas'] } },
  { text: 'Charles Darwin — naturalis pencetus teori evolusi melalui seleksi alam. Lahir tahun 1809 di Inggris.', metadata: { name: 'Charles Darwin', field: 'biologi', knownFor: 'teori evolusi', country: 'Inggris', born: '1809', tags: ['darwin', 'evolusi', 'biologi'] } },
  { text: 'Galileo Galilei — astronom dan fisikawan pendukung utama heliosentrisme, bapak sains modern. Lahir tahun 1564 di Italia.', metadata: { name: 'Galileo Galilei', field: 'astronomi', knownFor: 'heliosentrisme', country: 'Italia', born: '1564', tags: ['galileo', 'astronomi'] } },
  { text: 'Stephen Hawking — fisikawan teoretis terkenal dengan riset lubang hitam dan kosmologi. Lahir tahun 1942 di Inggris.', metadata: { name: 'Stephen Hawking', field: 'fisika', knownFor: 'lubang hitam', country: 'Inggris', born: '1942', tags: ['hawking', 'lubang hitam'] } },
  { text: 'Gregor Mendel — biarawan pendiri genetika modern lewat eksperimen kacang polong. Lahir tahun 1822 di Austria.', metadata: { name: 'Gregor Mendel', field: 'biologi', knownFor: 'genetika', country: 'Austria', born: '1822', tags: ['mendel', 'genetika'] } },
  { text: 'Nikola Tesla — ilmuwan dan penemu di bidang kelistrikan arus bolak-balik (AC). Lahir tahun 1856 di Serbia.', metadata: { name: 'Nikola Tesla', field: 'fisika/teknik', knownFor: 'arus bolak-balik', country: 'Serbia', born: '1856', tags: ['tesla', 'listrik'] } },
  { text: 'Alan Turing — matematikawan bapak ilmu komputer dan kecerdasan buatan, pemecah kode Enigma. Lahir tahun 1912 di Inggris.', metadata: { name: 'Alan Turing', field: 'matematika/komputer', knownFor: 'mesin Turing', country: 'Inggris', born: '1912', tags: ['turing', 'komputer'] } },
  { text: 'Ibnu Sina (Avicenna) — ilmuwan dan filsuf Persia, penulis Canon of Medicine yang berpengaruh berabad-abad. Lahir tahun 980 di Persia.', metadata: { name: 'Ibnu Sina', field: 'kedokteran', knownFor: 'Canon of Medicine', country: 'Persia', born: '980', tags: ['ibnu sina', 'kedokteran'] } },
  { text: 'B.J. Habibie — ilmuwan dan insinyur penerbangan Indonesia, pencetus Faktor Habibie di bidang keretakan pesawat.', metadata: { name: 'B.J. Habibie', field: 'teknik penerbangan', knownFor: 'Faktor Habibie', country: 'Indonesia', born: '1936', tags: ['habibie', 'indonesia', 'penerbangan'] } },
  { text: 'Carl Sagan — astronom dan penulis populer sains, dikenal lewat serial Cosmos. Lahir tahun 1934 di Amerika Serikat.', metadata: { name: 'Carl Sagan', field: 'astronomi', knownFor: 'Cosmos', country: 'Amerika Serikat', born: '1934', tags: ['carl sagan', 'astronomi'] } },
];

export const DATA = data;
