const data = [
  { text: 'Soekarno — presiden pertama Indonesia, proklamator kemerdekaan Indonesia 17 Agustus 1945.', metadata: { name: 'Soekarno', field: 'politik', knownFor: 'presiden pertama Indonesia', country: 'Indonesia', born: '1901', tags: ['soekarno', 'indonesia', 'proklamator'] } },
  { text: 'Mahatma Gandhi — pemimpin gerakan kemerdekaan India, pelopor perlawanan tanpa kekerasan.', metadata: { name: 'Mahatma Gandhi', field: 'politik', knownFor: 'perlawanan tanpa kekerasan', country: 'India', born: '1869', tags: ['gandhi', 'india'] } },
  { text: 'Napoleon Bonaparte — kaisar Prancis dan jenderal militer berpengaruh awal abad ke-19.', metadata: { name: 'Napoleon Bonaparte', field: 'politik/militer', knownFor: 'kaisar Prancis', country: 'Prancis', born: '1769', tags: ['napoleon', 'prancis'] } },
  { text: 'Cleopatra — firaun terakhir Mesir Kuno, dikenal karena kecerdasan politik dan pengaruhnya.', metadata: { name: 'Cleopatra', field: 'politik', knownFor: 'firaun terakhir Mesir', country: 'Mesir', born: '69 SM', tags: ['cleopatra', 'mesir'] } },
  { text: 'Nelson Mandela — presiden kulit hitam pertama Afrika Selatan, ikon perjuangan anti-apartheid.', metadata: { name: 'Nelson Mandela', field: 'politik', knownFor: 'anti-apartheid', country: 'Afrika Selatan', born: '1918', tags: ['mandela', 'afrika selatan'] } },
  { text: 'Abraham Lincoln — presiden ke-16 Amerika Serikat, dikenal karena menghapus perbudakan.', metadata: { name: 'Abraham Lincoln', field: 'politik', knownFor: 'penghapusan perbudakan', country: 'Amerika Serikat', born: '1809', tags: ['lincoln', 'amerika serikat'] } },
  { text: 'Genghis Khan — pendiri Kekaisaran Mongol, kekaisaran daratan terbesar dalam sejarah.', metadata: { name: 'Genghis Khan', field: 'militer', knownFor: 'pendiri Kekaisaran Mongol', country: 'Mongolia', born: '1162', tags: ['genghis khan', 'mongolia'] } },
  { text: 'Julius Caesar — jenderal dan negarawan Romawi, berperan penting dalam kejatuhan Republik Romawi.', metadata: { name: 'Julius Caesar', field: 'politik/militer', knownFor: 'negarawan Romawi', country: 'Romawi', born: '100 SM', tags: ['julius caesar', 'romawi'] } },
  { text: 'Cut Nyak Dhien — pahlawan nasional Indonesia, pemimpin perlawanan Aceh melawan kolonial Belanda.', metadata: { name: 'Cut Nyak Dhien', field: 'militer', knownFor: 'perlawanan Aceh', country: 'Indonesia', born: '1848', tags: ['cut nyak dhien', 'indonesia'] } },
  { text: 'Martin Luther King Jr. — tokoh gerakan hak sipil Amerika Serikat, pelopor perjuangan anti-rasisme tanpa kekerasan.', metadata: { name: 'Martin Luther King Jr.', field: 'politik', knownFor: 'gerakan hak sipil', country: 'Amerika Serikat', born: '1929', tags: ['mlk', 'amerika serikat'] } },
  { text: 'Winston Churchill — perdana menteri Inggris yang memimpin negara itu melewati Perang Dunia II.', metadata: { name: 'Winston Churchill', field: 'politik', knownFor: 'pemimpin PD II', country: 'Inggris', born: '1874', tags: ['churchill', 'inggris'] } },
  { text: 'Kartini — pahlawan nasional Indonesia, pelopor emansipasi wanita lewat surat-suratnya.', metadata: { name: 'Kartini', field: 'sosial', knownFor: 'emansipasi wanita', country: 'Indonesia', born: '1879', tags: ['kartini', 'indonesia'] } },
];

export const DATA = data;
