const data = [
  { text: 'Leonardo da Vinci — seniman dan ilmuwan Renaisans, pelukis Mona Lisa dan The Last Supper. Lahir tahun 1452 di Italia.', metadata: { name: 'Leonardo da Vinci', field: 'seni', knownFor: 'Mona Lisa', country: 'Italia', born: '1452', tags: ['da vinci', 'mona lisa'] } },
  { text: 'Vincent van Gogh — pelukis pasca-impresionis Belanda, dikenal lewat Starry Night dan Sunflowers. Lahir tahun 1853 di Belanda.', metadata: { name: 'Vincent van Gogh', field: 'seni', knownFor: 'Starry Night', country: 'Belanda', born: '1853', tags: ['van gogh', 'starry night'] } },
  { text: 'Pablo Picasso — pelukis dan pematung Spanyol, pelopor gerakan seni Kubisme. Lahir tahun 1881 di Spanyol.', metadata: { name: 'Pablo Picasso', field: 'seni', knownFor: 'Kubisme', country: 'Spanyol', born: '1881', tags: ['picasso', 'kubisme'] } },
  { text: 'Wolfgang Amadeus Mozart — komponis klasik Austria, salah satu musisi paling berpengaruh sepanjang sejarah. Lahir tahun 1756 di Austria.', metadata: { name: 'Wolfgang Amadeus Mozart', field: 'musik', knownFor: 'komposer klasik', country: 'Austria', born: '1756', tags: ['mozart', 'musik klasik'] } },
  { text: 'Ludwig van Beethoven — komponis Jerman, dikenal lewat Symphony No. 9 meski mengalami tuli.', metadata: { name: 'Ludwig van Beethoven', field: 'musik', knownFor: 'Symphony No. 9', country: 'Jerman', born: '1770', tags: ['beethoven', 'symphony'] } },
  { text: 'Raden Saleh — pelukis Indonesia perintis seni lukis modern bergaya romantisisme. Lahir tahun 1811 di Indonesia.', metadata: { name: 'Raden Saleh', field: 'seni', knownFor: 'pelukis romantisisme', country: 'Indonesia', born: '1811', tags: ['raden saleh', 'indonesia'] } },
  { text: 'William Shakespeare — penulis drama dan penyair Inggris, dianggap penulis terbesar berbahasa Inggris. Lahir tahun 1564 di Inggris.', metadata: { name: 'William Shakespeare', field: 'sastra', knownFor: 'drama Romeo and Juliet', country: 'Inggris', born: '1564', tags: ['shakespeare', 'sastra'] } },
  { text: 'Frida Kahlo — pelukis Meksiko dikenal lewat lukisan potret diri yang penuh simbolisme. Lahir tahun 1907 di Meksiko.', metadata: { name: 'Frida Kahlo', field: 'seni', knownFor: 'potret diri', country: 'Meksiko', born: '1907', tags: ['frida kahlo', 'meksiko'] } },
  { text: 'Michael Jackson — penyanyi dan penari Amerika Serikat, dijuluki King of Pop. Lahir tahun 1958 di Amerika Serikat.', metadata: { name: 'Michael Jackson', field: 'musik', knownFor: 'King of Pop', country: 'Amerika Serikat', born: '1958', tags: ['michael jackson', 'king of pop'] } },
  { text: 'Chairil Anwar — penyair Indonesia angkatan 45, dijuluki "Si Binatang Jalang" karena karyanya yang berapi-api. Lahir tahun 1922 di Indonesia.', metadata: { name: 'Chairil Anwar', field: 'sastra', knownFor: 'puisi Aku', country: 'Indonesia', born: '1922', tags: ['chairil anwar', 'indonesia', 'puisi'] } },
  { text: 'Walt Disney — animator dan produser film Amerika Serikat, pendiri The Walt Disney Company. Lahir tahun 1901 di Amerika Serikat.', metadata: { name: 'Walt Disney', field: 'seni/film', knownFor: 'pendiri Disney', country: 'Amerika Serikat', born: '1901', tags: ['walt disney'] } },
  { text: 'Beyoncé — penyanyi dan penulis lagu Amerika Serikat, salah satu artis paling berpengaruh abad ke-21. Lahir tahun 1981 di Amerika Serikat.', metadata: { name: 'Beyoncé', field: 'musik', knownFor: 'penyanyi pop-R&B', country: 'Amerika Serikat', born: '1981', tags: ['beyonce', 'musik'] } },
];

export const DATA = data;
