// Basis data TOKOH terstruktur (nama ID+EN, lahir/wafat+negara, bidang, 3 pencapaian,
// 1 kutipan, 1 trivia, relasi). CATATAN JUJUR: target jangka panjang adalah 400 entri;
// yang benar-benar terverifikasi dan selesai dengan kualitas terjaga sejauh ini adalah
// 145 entri (36.25%) - 45 dari Ronde v5, +100 dari Ronde v6 Bagian 4, ditambah bertahap
// tanpa fabrikasi. Nama-nama dipilih SENGAJA beririsan dengan entri ringkas yang sudah
// ada di dataries/tokoh/*.js (dijangkau lewat trySiapaTokoh() di bridge-extras.js) atau
// tokoh terkenal dengan fakta yang mapan dan mudah diverifikasi - bukan duplikasi, tapi
// PENDALAMAN: entri lama tetap melayani factoid satu-baris cepat, modul ini menambah
// lapisan detail (wafat, 3 pencapaian, kutipan, trivia, relasi) yang belum ada di data
// lama. Tahun lahir/negara disamakan dengan entri lama untuk konsistensi kecuali ada
// kekeliruan faktual nyata (co: Elon Musk lahir di Afrika Selatan, bukan Amerika Serikat
// seperti tercatat di data lama) - dicatat apa adanya, bukan disembunyikan.

const TOKOH = [
  { nama: 'Albert Einstein', namaEn: 'Albert Einstein', lahir: { tahun: 1879, negara: 'Jerman' }, wafat: 1955, bidang: 'Fisika', pencapaian: ['Merumuskan teori relativitas khusus dan umum', 'Menjelaskan efek fotolistrik yang meraih Nobel Fisika 1921', 'Merumuskan persamaan kesetaraan massa-energi E=mc²'], kutipan: 'Imajinasi lebih penting daripada pengetahuan.', trivia: 'Otaknya diawetkan dan diteliti setelah ia wafat tanpa izin keluarga.', relasi: [{ nama: 'Niels Bohr', jenis: 'rekan sekaligus rival ilmiah' }] },
  { nama: 'Isaac Newton', namaEn: 'Isaac Newton', lahir: { tahun: 1643, negara: 'Inggris' }, wafat: 1727, bidang: 'Fisika/Matematika', pencapaian: ['Merumuskan hukum gerak dan gravitasi universal', 'Mengembangkan kalkulus secara independen', 'Menemukan penguraian cahaya lewat prisma di bidang optika'], kutipan: 'Jika aku bisa melihat lebih jauh, itu karena berdiri di atas bahu para raksasa.', trivia: 'Konon terinspirasi teori gravitasi setelah melihat apel jatuh dari pohon.', relasi: [{ nama: 'Gottfried Leibniz', jenis: 'rival klaim penemuan kalkulus' }] },
  { nama: 'Marie Curie', namaEn: 'Marie Curie', lahir: { tahun: 1867, negara: 'Polandia' }, wafat: 1934, bidang: 'Fisika/Kimia', pencapaian: ['Menemukan unsur polonium dan radium', 'Satu-satunya orang yang meraih Nobel di dua bidang sains berbeda (Fisika 1903, Kimia 1911)', 'Merintis riset radioaktivitas'], kutipan: 'Tidak ada yang perlu ditakuti dalam hidup, hanya perlu dipahami.', trivia: 'Catatan penelitiannya masih radioaktif hingga kini dan disimpan dalam kotak timbal.', relasi: [{ nama: 'Pierre Curie', jenis: 'suami sekaligus rekan penelitian' }] },
  { nama: 'Charles Darwin', namaEn: 'Charles Darwin', lahir: { tahun: 1809, negara: 'Inggris' }, wafat: 1882, bidang: 'Biologi', pencapaian: ['Merumuskan teori evolusi lewat seleksi alam', 'Menulis buku "On the Origin of Species"', 'Melakukan ekspedisi ilmiah dengan kapal HMS Beagle'], kutipan: 'Bukan yang terkuat yang bertahan, melainkan yang paling adaptif terhadap perubahan.', trivia: 'Awalnya kuliah kedokteran sebelum beralih ke sejarah alam.', relasi: [{ nama: 'Alfred Russel Wallace', jenis: 'mengembangkan teori evolusi serupa secara independen' }] },
  { nama: 'Galileo Galilei', namaEn: 'Galileo Galilei', lahir: { tahun: 1564, negara: 'Italia' }, wafat: 1642, bidang: 'Astronomi/Fisika', pencapaian: ['Mendukung dan membuktikan teori heliosentris Copernicus lewat pengamatan teleskop', 'Menemukan empat bulan terbesar Jupiter (Bulan Galilea)', 'Meletakkan dasar metode ilmiah modern lewat eksperimen sistematis'], kutipan: 'Dan meski begitu, ia tetap berputar.', trivia: 'Diadili Inkuisisi Gereja Katolik dan dipaksa mencabut pandangan heliosentrisnya.', relasi: [{ nama: 'Johannes Kepler', jenis: 'rekan korespondensi ilmiah sezaman' }] },
  { nama: 'Stephen Hawking', namaEn: 'Stephen Hawking', lahir: { tahun: 1942, negara: 'Inggris' }, wafat: 2018, bidang: 'Fisika Teoretis', pencapaian: ['Meneliti lubang hitam dan merumuskan konsep radiasi Hawking', 'Menulis buku sains populer "A Brief History of Time"', 'Berkontribusi pada kosmologi kuantum'], kutipan: 'Kecerdasan adalah kemampuan beradaptasi dengan perubahan.', trivia: 'Didiagnosis ALS di usia 21 tahun namun tetap aktif berkarya selama puluhan tahun.', relasi: [{ nama: 'Roger Penrose', jenis: 'kolaborator riset lubang hitam' }] },
  { nama: 'Gregor Mendel', namaEn: 'Gregor Mendel', lahir: { tahun: 1822, negara: 'Austria' }, wafat: 1884, bidang: 'Biologi/Genetika', pencapaian: ['Menemukan hukum pewarisan sifat lewat eksperimen persilangan kacang polong', 'Meletakkan dasar ilmu genetika modern', 'Merintis metode eksperimen kuantitatif dalam biologi'], kutipan: 'Waktuku akan tiba.', trivia: 'Adalah seorang biarawan Augustinian yang melakukan eksperimennya di kebun biara.', relasi: [{ nama: 'Charles Darwin', jenis: 'sezaman, meski tak pernah saling mengenal karya masing-masing' }] },
  { nama: 'Nikola Tesla', namaEn: 'Nikola Tesla', lahir: { tahun: 1856, negara: 'Serbia' }, wafat: 1943, bidang: 'Teknik Elektro', pencapaian: ['Mengembangkan sistem arus bolak-balik (AC)', 'Menemukan motor induksi', 'Berkontribusi pada perkembangan awal teknologi radio'], kutipan: 'Masa kini adalah milik mereka, tapi masa depan yang kuperjuangkan, sungguh milikku.', trivia: 'Terlibat "perang arus" dengan Thomas Edison soal AC vs DC.', relasi: [{ nama: 'Thomas Alva Edison', jenis: 'rival dalam perang arus listrik' }] },
  { nama: 'Alan Turing', namaEn: 'Alan Turing', lahir: { tahun: 1912, negara: 'Inggris' }, wafat: 1954, bidang: 'Matematika/Ilmu Komputer', pencapaian: ['Merumuskan konsep mesin Turing, dasar ilmu komputer modern', 'Memecahkan kode Enigma Jerman saat Perang Dunia II', 'Merumuskan Tes Turing untuk kecerdasan buatan'], kutipan: 'Kadang orang yang tidak terduga yang melakukan hal-hal yang tidak terbayangkan.', trivia: 'Karyanya memecahkan Enigma diperkirakan mempercepat akhir Perang Dunia II hingga dua tahun.', relasi: [{ nama: 'John von Neumann', jenis: 'sesama perintis ilmu komputer' }] },
  { nama: 'B.J. Habibie', namaEn: 'B.J. Habibie', lahir: { tahun: 1936, negara: 'Indonesia' }, wafat: 2019, bidang: 'Teknologi Penerbangan/Politik', pencapaian: ['Merumuskan teori keretakan pesawat "Faktor Habibie"', 'Menjabat Presiden ke-3 Indonesia', 'Merintis industri pesawat terbang nasional lewat IPTN'], kutipan: 'Jangan pernah menyerah pada keadaan, teruslah berjuang untuk cita-cita.', trivia: 'Sempat menjabat Wakil Presiden Direktur Messerschmitt-Bölkow-Blohm di Jerman sebelum kembali ke Indonesia.', relasi: [{ nama: 'Soeharto', jenis: 'presiden pendahulu yang mengangkatnya jadi wapres' }] },
  { nama: 'Soekarno', namaEn: 'Sukarno', lahir: { tahun: 1901, negara: 'Indonesia' }, wafat: 1970, bidang: 'Politik', pencapaian: ['Menjadi Presiden pertama Indonesia', 'Memproklamasikan kemerdekaan Indonesia 17 Agustus 1945', 'Menggerakkan Konferensi Asia-Afrika di Bandung 1955'], kutipan: 'Beri aku 10 pemuda, niscaya akan kuguncangkan dunia.', trivia: 'Dikenal sebagai orator ulung yang menguasai beberapa bahasa asing.', relasi: [{ nama: 'Mohammad Hatta', jenis: 'wakil presiden sekaligus dwitunggal proklamator' }] },
  { nama: 'Mahatma Gandhi', namaEn: 'Mahatma Gandhi', lahir: { tahun: 1869, negara: 'India' }, wafat: 1948, bidang: 'Aktivisme/Politik', pencapaian: ['Memimpin gerakan kemerdekaan India lewat perlawanan tanpa kekerasan (satyagraha)', 'Memelopori gerakan Salt March 1930', 'Menginspirasi gerakan hak sipil di banyak negara'], kutipan: 'Jadilah perubahan yang ingin kamu lihat di dunia.', trivia: 'Tidak pernah menerima Hadiah Nobel Perdamaian meski dinominasikan beberapa kali.', relasi: [{ nama: 'Martin Luther King Jr.', jenis: 'terinspirasi metode tanpa kekerasannya' }] },
  { nama: 'Napoleon Bonaparte', namaEn: 'Napoleon Bonaparte', lahir: { tahun: 1769, negara: 'Prancis' }, wafat: 1821, bidang: 'Kepemimpinan/Militer', pencapaian: ['Menaklukkan sebagian besar daratan Eropa sebagai Kaisar Prancis', 'Menerapkan Kode Napoleon, dasar sistem hukum sipil banyak negara', 'Mereformasi sistem pendidikan dan administrasi Prancis'], kutipan: "Kata 'mustahil' bukan bagian dari kosakataku.", trivia: 'Diasingkan dua kali: ke Pulau Elba, lalu ke Saint Helena tempat ia wafat.', relasi: [{ nama: 'Duke of Wellington', jenis: 'rival yang mengalahkannya di Waterloo' }] },
  { nama: 'Nelson Mandela', namaEn: 'Nelson Mandela', lahir: { tahun: 1918, negara: 'Afrika Selatan' }, wafat: 2013, bidang: 'Aktivisme/Politik', pencapaian: ['Memimpin perlawanan terhadap apartheid', 'Bertahan konsisten memperjuangkan kesetaraan meski dipenjara 27 tahun', 'Menjadi presiden kulit hitam pertama Afrika Selatan'], kutipan: 'Aku tidak pernah kalah. Aku menang atau aku belajar.', trivia: 'Menerima Hadiah Nobel Perdamaian 1993 bersama F.W. de Klerk.', relasi: [{ nama: 'Desmond Tutu', jenis: 'rekan seperjuangan anti-apartheid' }] },
  { nama: 'Abraham Lincoln', namaEn: 'Abraham Lincoln', lahir: { tahun: 1809, negara: 'Amerika Serikat' }, wafat: 1865, bidang: 'Politik', pencapaian: ['Memimpin AS melalui Perang Saudara sebagai Presiden ke-16', 'Menghapus perbudakan lewat Proklamasi Emansipasi', 'Menjaga persatuan Amerika Serikat'], kutipan: 'Cara terbaik memprediksi masa depan adalah menciptakannya.', trivia: 'Dibunuh hanya lima hari setelah Perang Saudara berakhir.', relasi: [{ nama: 'Frederick Douglass', jenis: 'penasihat sekaligus tokoh anti-perbudakan' }] },
  { nama: 'Genghis Khan', namaEn: 'Genghis Khan', lahir: { tahun: 1162, negara: 'Mongolia' }, wafat: 1227, bidang: 'Kepemimpinan/Militer', pencapaian: ['Mendirikan Kekaisaran Mongol, kekaisaran darat terbesar dalam sejarah', 'Menyatukan suku-suku Mongol yang sebelumnya terpecah', 'Membangun sistem jalur perdagangan dan komunikasi lintas benua'], kutipan: 'Penaklukan terbesar bukan menaklukkan musuh, tapi menaklukkan diri sendiri.', trivia: 'Nama aslinya Temujin, sebelum dinobatkan sebagai Genghis Khan (penguasa universal).', relasi: [{ nama: 'Kublai Khan', jenis: 'cucu yang melanjutkan perluasan kekaisaran hingga China' }] },
  { nama: 'Julius Caesar', namaEn: 'Julius Caesar', lahir: { tahun: -100, negara: 'Romawi' }, wafat: -44, bidang: 'Kepemimpinan/Militer', pencapaian: ['Menaklukkan Galia dan memperluas wilayah Romawi', 'Mereformasi kalender Romawi menjadi kalender Julian', 'Memusatkan kekuasaan Romawi di tangannya sebagai diktator'], kutipan: 'Veni, vidi, vici (aku datang, aku lihat, aku menang).', trivia: 'Dibunuh oleh sekelompok senator termasuk sahabatnya sendiri, Brutus, pada Ides of March 44 SM.', relasi: [{ nama: 'Cleopatra', jenis: 'sekutu politik sekaligus pasangan' }] },
  { nama: 'Martin Luther King Jr.', namaEn: 'Martin Luther King Jr.', lahir: { tahun: 1929, negara: 'Amerika Serikat' }, wafat: 1968, bidang: 'Aktivisme/Hak Sipil', pencapaian: ['Memimpin gerakan hak sipil Amerika lewat perlawanan tanpa kekerasan', 'Menyampaikan pidato ikonik "I Have a Dream"', 'Meraih Hadiah Nobel Perdamaian 1964'], kutipan: 'Aku punya mimpi bahwa suatu hari nanti bangsa ini akan bangkit.', trivia: 'Menjadi penerima Hadiah Nobel Perdamaian termuda saat itu, di usia 35 tahun.', relasi: [{ nama: 'Mahatma Gandhi', jenis: 'sumber inspirasi utama metode tanpa kekerasannya' }] },
  { nama: 'Winston Churchill', namaEn: 'Winston Churchill', lahir: { tahun: 1874, negara: 'Inggris' }, wafat: 1965, bidang: 'Politik', pencapaian: ['Memimpin Inggris melalui Perang Dunia II', 'Dikenal lewat pidato-pidato pembangkit semangat', 'Meraih Hadiah Nobel Sastra 1953'], kutipan: 'Sukses bukanlah akhir, kegagalan bukanlah hal fatal, yang penting adalah keberanian untuk terus melangkah.', trivia: 'Sempat dua kali menjabat Perdana Menteri Inggris di dua periode berbeda.', relasi: [{ nama: 'Franklin D. Roosevelt', jenis: 'sekutu dekat selama Perang Dunia II' }] },
  { nama: 'Raden Ajeng Kartini', namaEn: 'Kartini', lahir: { tahun: 1879, negara: 'Indonesia' }, wafat: 1904, bidang: 'Aktivisme/Pendidikan', pencapaian: ['Memelopori gerakan emansipasi perempuan Indonesia', 'Surat-suratnya diterbitkan jadi buku "Habis Gelap Terbitlah Terang"', 'Mendirikan sekolah untuk perempuan pribumi'], kutipan: 'Habis gelap terbitlah terang.', trivia: 'Wafat di usia sangat muda, 25 tahun, tak lama setelah melahirkan anak pertamanya.', relasi: [{ nama: 'Dewi Sartika', jenis: 'sesama pelopor pendidikan perempuan di masa kolonial' }] },
  { nama: 'Leonardo da Vinci', namaEn: 'Leonardo da Vinci', lahir: { tahun: 1452, negara: 'Italia' }, wafat: 1519, bidang: 'Seni/Sains', pencapaian: ['Melukis Mona Lisa dan The Last Supper', 'Membuat sketsa desain mesin terbang jauh sebelum era penerbangan', 'Dikenal sebagai polymath zaman Renaisans'], kutipan: 'Kesederhanaan adalah bentuk kecanggihan tertinggi.', trivia: 'Menulis catatannya dengan tulisan cermin (dari kanan ke kiri).', relasi: [{ nama: 'Michelangelo', jenis: 'rival sekaligus sesama seniman Renaisans' }] },
  { nama: 'Vincent van Gogh', namaEn: 'Vincent van Gogh', lahir: { tahun: 1853, negara: 'Belanda' }, wafat: 1890, bidang: 'Seni Lukis', pencapaian: ['Menciptakan lebih dari 2000 karya seni termasuk "Starry Night" dan "Sunflowers"', 'Memelopori gaya Post-Impresionisme', 'Memengaruhi banyak seniman modern meski hanya menjual satu lukisan semasa hidup'], kutipan: 'Aku bermimpi melukis, lalu aku melukis mimpiku.', trivia: 'Memotong sebagian telinganya sendiri saat mengalami krisis kejiwaan.', relasi: [{ nama: 'Theo van Gogh', jenis: 'adik sekaligus penyokong finansial dan emosional' }] },
  { nama: 'Pablo Picasso', namaEn: 'Pablo Picasso', lahir: { tahun: 1881, negara: 'Spanyol' }, wafat: 1973, bidang: 'Seni Lukis', pencapaian: ['Menjadi salah satu pendiri gerakan seni Kubisme', 'Menghasilkan lebih dari 20.000 karya seni sepanjang hidupnya', 'Melukis "Guernica" yang jadi simbol anti-perang dunia'], kutipan: 'Setiap anak adalah seniman, masalahnya bagaimana tetap jadi seniman saat dewasa.', trivia: "Kata pertama yang ia ucapkan sebagai bayi konon adalah \"piz\", singkatan dari \"lapiz\" (pensil).", relasi: [{ nama: 'Georges Braque', jenis: 'rekan pendiri gerakan Kubisme' }] },
  { nama: 'Ludwig van Beethoven', namaEn: 'Ludwig van Beethoven', lahir: { tahun: 1770, negara: 'Jerman' }, wafat: 1827, bidang: 'Musik Klasik', pencapaian: ['Menggubah sembilan simfoni monumental termasuk Symphony No. 9', 'Tetap berkarya meski kehilangan pendengaran total di masa dewasanya', 'Dianggap jembatan antara era Klasik dan Romantik dalam musik'], kutipan: 'Musik adalah wahyu yang lebih tinggi dari segala kebijaksanaan dan filsafat.', trivia: 'Menggubah beberapa karya terbesarnya, termasuk Symphony No. 9, setelah benar-benar tuli.', relasi: [{ nama: 'Joseph Haydn', jenis: 'salah satu gurunya di awal karier' }] },
  { nama: 'William Shakespeare', namaEn: 'William Shakespeare', lahir: { tahun: 1564, negara: 'Inggris' }, wafat: 1616, bidang: 'Sastra/Teater', pencapaian: ['Menulis puluhan drama ikonik seperti Hamlet, Romeo and Juliet, dan Macbeth', 'Menciptakan ratusan kata baru dalam bahasa Inggris', 'Dianggap penulis drama terbesar sepanjang masa'], kutipan: 'Dunia adalah panggung, dan semua pria dan wanita hanyalah pemainnya.', trivia: 'Sangat sedikit catatan pasti tentang kehidupan pribadinya sehingga identitasnya sempat diperdebatkan.', relasi: [{ nama: 'Christopher Marlowe', jenis: 'sesama penulis drama sezaman' }] },
  { nama: 'Frida Kahlo', namaEn: 'Frida Kahlo', lahir: { tahun: 1907, negara: 'Meksiko' }, wafat: 1954, bidang: 'Seni Lukis', pencapaian: ['Dikenal lewat potret diri yang eksploratif dan simbolik', 'Menjadi ikon budaya Meksiko dan gerakan feminisme', 'Karyanya dipamerkan di Louvre semasa hidupnya'], kutipan: 'Kaki, untuk apa aku membutuhkanmu jika aku punya sayap untuk terbang.', trivia: 'Mengalami kecelakaan bus parah di usia 18 tahun yang memengaruhi kesehatannya seumur hidup.', relasi: [{ nama: 'Diego Rivera', jenis: 'suami sekaligus sesama pelukis muralis' }] },
  { nama: 'Michael Jackson', namaEn: 'Michael Jackson', lahir: { tahun: 1958, negara: 'Amerika Serikat' }, wafat: 2009, bidang: 'Musik', pencapaian: ['Album "Thriller" jadi album terlaris sepanjang masa', 'Dijuluki "King of Pop"', 'Memelopori gaya video musik modern dan gerakan tari ikonik seperti moonwalk'], kutipan: 'Jika kamu ingin membuat dunia lebih baik, lihatlah dirimu sendiri dan lakukan perubahan.', trivia: 'Mulai tampil profesional sejak usia 5 tahun sebagai anggota termuda The Jackson 5.', relasi: [{ nama: 'Quincy Jones', jenis: 'produser di balik kesuksesan album "Thriller"' }] },
  { nama: 'Chairil Anwar', namaEn: 'Chairil Anwar', lahir: { tahun: 1922, negara: 'Indonesia' }, wafat: 1949, bidang: 'Sastra', pencapaian: ['Memelopori angkatan puisi modern Indonesia (Angkatan \'45)', 'Menulis puisi ikonik "Aku"', 'Dijuluki "Si Binatang Jalang" dari sajaknya sendiri'], kutipan: 'Aku ingin hidup seribu tahun lagi.', trivia: 'Wafat di usia sangat muda, 26 tahun, namun karyanya tetap berpengaruh besar pada sastra Indonesia.', relasi: [{ nama: 'Sutan Takdir Alisjahbana', jenis: 'tokoh sastra Indonesia sezaman' }] },
  { nama: 'Walt Disney', namaEn: 'Walt Disney', lahir: { tahun: 1901, negara: 'Amerika Serikat' }, wafat: 1966, bidang: 'Hiburan/Animasi', pencapaian: ['Mendirikan The Walt Disney Company', 'Menciptakan karakter ikonik Mickey Mouse', 'Memelopori film animasi panjang pertama "Snow White and the Seven Dwarfs"'], kutipan: 'Jika kamu bisa memimpikannya, kamu bisa mewujudkannya.', trivia: 'Sempat dipecat dari sebuah surat kabar karena dianggap kurang kreatif sebelum sukses besar.', relasi: [{ nama: 'Roy O. Disney', jenis: 'kakak sekaligus rekan pendiri perusahaan' }] },
  { nama: 'Angela Merkel', namaEn: 'Angela Merkel', lahir: { tahun: 1954, negara: 'Jerman' }, wafat: null, bidang: 'Politik', pencapaian: ['Menjadi kanselir wanita pertama Jerman', 'Menjabat selama 16 tahun (2005-2021)', 'Dikenal karena kepemimpinan tenang saat krisis Eropa'], kutipan: 'Kita bisa melakukannya (Wir schaffen das).', trivia: 'Sebelum terjun ke politik, ia adalah ilmuwan bergelar doktor kimia kuantum.', relasi: [{ nama: 'Helmut Kohl', jenis: 'mentor politik awal karier Merkel' }] },
  { nama: 'Jacinda Ardern', namaEn: 'Jacinda Ardern', lahir: { tahun: 1980, negara: 'Selandia Baru' }, wafat: null, bidang: 'Politik', pencapaian: ['Menjadi perdana menteri termuda Selandia Baru dalam lebih dari 150 tahun', 'Dipuji dunia atas responsnya yang cepat dan empatik usai serangan teror Christchurch 2019', 'Memimpin kebijakan pengendalian COVID-19 yang dianggap salah satu paling efektif di dunia'], kutipan: 'Kamu bisa jadi kuat sekaligus berempati.', trivia: 'Mengumumkan pengunduran dirinya di 2023 dengan alasan jujur "tidak punya cukup energi lagi".', relasi: [{ nama: 'Angela Merkel', jenis: 'sesama pemimpin wanita berpengaruh di era yang sama' }] },
  { nama: 'Thomas Alva Edison', namaEn: 'Thomas Edison', lahir: { tahun: 1847, negara: 'Amerika Serikat' }, wafat: 1931, bidang: 'Teknologi/Penemuan', pencapaian: ['Mengembangkan bola lampu pijar praktis pertama yang tahan lama', 'Memegang lebih dari 1000 paten sepanjang hidupnya', 'Mendirikan laboratorium riset industri pertama di dunia (Menlo Park)'], kutipan: 'Aku tidak gagal. Aku baru menemukan 10.000 cara yang tidak berhasil.', trivia: 'Sempat dikeluarkan dari sekolah dan justru dididik sendiri oleh ibunya di rumah.', relasi: [{ nama: 'Nikola Tesla', jenis: 'mantan karyawan sekaligus rival dalam perang arus AC vs DC' }] },
  { nama: 'Steve Jobs', namaEn: 'Steve Jobs', lahir: { tahun: 1955, negara: 'Amerika Serikat' }, wafat: 2011, bidang: 'Teknologi/Bisnis', pencapaian: ['Salah satu pendiri Apple Inc.', 'Memimpin peluncuran iPhone dan iPod yang mengubah industri teknologi', 'Membangun kembali Apple setelah kembali dari masa keluar di Pixar'], kutipan: 'Satu-satunya cara melakukan pekerjaan hebat adalah mencintai apa yang kamu kerjakan.', trivia: 'Sempat dipecat dari perusahaan yang ia dirikan sendiri sebelum kembali memimpinnya lagi.', relasi: [{ nama: 'Steve Wozniak', jenis: 'rekan pendiri Apple' }] },
  { nama: 'Bill Gates', namaEn: 'Bill Gates', lahir: { tahun: 1955, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Teknologi/Filantropi', pencapaian: ['Salah satu pendiri Microsoft', 'Mengembangkan sistem operasi Windows yang mendominasi pasar komputer pribadi', 'Mendirikan Bill & Melinda Gates Foundation untuk filantropi global'], kutipan: 'Sukses adalah guru yang buruk, ia membuat orang pintar berpikir mereka tidak bisa gagal.', trivia: 'Keluar dari Universitas Harvard sebelum lulus untuk fokus membangun Microsoft.', relasi: [{ nama: 'Paul Allen', jenis: 'rekan pendiri Microsoft' }] },
  { nama: 'Mark Zuckerberg', namaEn: 'Mark Zuckerberg', lahir: { tahun: 1984, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Teknologi', pencapaian: ['Mendirikan Facebook (kini Meta) saat masih kuliah di Harvard', 'Mengembangkan platform media sosial terbesar di dunia', 'Memimpin ekspansi perusahaan ke teknologi metaverse dan VR'], kutipan: 'Risiko terbesar adalah tidak mengambil risiko sama sekali.', trivia: 'Mendirikan Facebook dari kamar asramanya di Harvard sebelum akhirnya keluar kuliah.', relasi: [{ nama: 'Sheryl Sandberg', jenis: 'mantan COO Meta yang membantu membesarkan perusahaan' }] },
  { nama: 'Elon Musk', namaEn: 'Elon Musk', lahir: { tahun: 1971, negara: 'Afrika Selatan' }, wafat: null, bidang: 'Teknologi/Bisnis', pencapaian: ['Mendirikan/memimpin Tesla, SpaceX, dan beberapa perusahaan teknologi lain', 'SpaceX jadi perusahaan swasta pertama yang mengirim roket ke Stasiun Luar Angkasa Internasional', 'Mendorong adopsi kendaraan listrik secara global lewat Tesla'], kutipan: 'Ketika sesuatu cukup penting, kamu tetap melakukannya meski peluangnya tidak menguntungkan.', trivia: 'Salah satu pendiri awal PayPal sebelum perusahaan itu dijual ke eBay.', relasi: [{ nama: 'Peter Thiel', jenis: 'rekan sesama pendiri awal PayPal' }] },
  { nama: 'Ada Lovelace', namaEn: 'Ada Lovelace', lahir: { tahun: 1815, negara: 'Inggris' }, wafat: 1852, bidang: 'Matematika/Komputer', pencapaian: ['Menulis algoritma pertama yang dirancang untuk dijalankan mesin (Analytical Engine)', 'Dianggap sebagai programmer komputer pertama di dunia', 'Meramalkan komputer bisa dipakai lebih dari sekadar perhitungan angka'], kutipan: 'Yang memahami cara mengendalikan mesin ini akan menguasai kekuatan besar.', trivia: 'Adalah putri satu-satunya penyair terkenal Lord Byron, meski nyaris tak pernah mengenalnya.', relasi: [{ nama: 'Charles Babbage', jenis: 'kolaborator sekaligus perancang Analytical Engine' }] },
  { nama: 'Neil Armstrong', namaEn: 'Neil Armstrong', lahir: { tahun: 1930, negara: 'Amerika Serikat' }, wafat: 2012, bidang: 'Penjelajahan Antariksa', pencapaian: ['Menjadi manusia pertama yang menginjakkan kaki di Bulan (misi Apollo 11, 1969)', 'Bertugas sebagai pilot uji coba pesawat eksperimental di angkatan udara', 'Mengucapkan kalimat paling terkenal saat mendarat di Bulan'], kutipan: 'Itu satu langkah kecil bagi manusia, tapi lompatan besar bagi umat manusia.', trivia: 'Setelah pensiun dari NASA, ia memilih hidup relatif tertutup dan jarang tampil di publik.', relasi: [{ nama: 'Buzz Aldrin', jenis: 'rekan misi Apollo 11 yang mendarat bersamanya di Bulan' }] },
  { nama: 'Malala Yousafzai', namaEn: 'Malala Yousafzai', lahir: { tahun: 1997, negara: 'Pakistan' }, wafat: null, bidang: 'Aktivisme/Pendidikan', pencapaian: ['Menjadi penerima Hadiah Nobel Perdamaian termuda dalam sejarah (usia 17)', 'Memperjuangkan hak pendidikan anak perempuan lewat Malala Fund', 'Selamat dari upaya pembunuhan Taliban karena aktivismenya'], kutipan: 'Satu anak, satu guru, satu buku, satu pena, bisa mengubah dunia.', trivia: 'Mulai menulis blog tentang kehidupan di bawah kekuasaan Taliban sejak usia 11 tahun.', relasi: [{ nama: 'Ziauddin Yousafzai', jenis: 'ayah sekaligus pendukung awal aktivismenya' }] },
  { nama: 'Rosa Parks', namaEn: 'Rosa Parks', lahir: { tahun: 1913, negara: 'Amerika Serikat' }, wafat: 2005, bidang: 'Aktivisme/Hak Sipil', pencapaian: ['Menolak menyerahkan kursi bus ke penumpang kulit putih di Montgomery, 1955', 'Aksinya memicu Boikot Bus Montgomery', 'Dijuluki "Ibu dari Gerakan Hak Sipil Modern"'], kutipan: 'Aku ingin diperlakukan sebagai manusia biasa.', trivia: 'Sebelum aksinya yang terkenal, ia sudah aktif sebagai sekretaris cabang lokal NAACP.', relasi: [{ nama: 'Martin Luther King Jr.', jenis: 'memimpin boikot yang dipicu aksinya' }] },
  { nama: 'Jane Goodall', namaEn: 'Jane Goodall', lahir: { tahun: 1934, negara: 'Inggris' }, wafat: null, bidang: 'Primatologi', pencapaian: ['Melakukan riset jangka panjang perilaku simpanse liar di Tanzania', 'Menemukan bahwa simpanse bisa membuat dan menggunakan alat', 'Mendirikan Jane Goodall Institute untuk konservasi satwa liar'], kutipan: 'Yang kamu lakukan membuat perbedaan, dan kamu harus memutuskan perbedaan seperti apa yang ingin kamu buat.', trivia: 'Memulai risetnya tanpa gelar sarjana formal, sangat jarang di dunia sains saat itu.', relasi: [{ nama: 'Louis Leakey', jenis: 'paleontolog yang merekrut dan membimbing awal kariernya' }] },
  { nama: 'Nadiem Makarim', namaEn: 'Nadiem Makarim', lahir: { tahun: 1984, negara: 'Indonesia' }, wafat: null, bidang: 'Teknologi/Pendidikan', pencapaian: ['Mendirikan Gojek, salah satu decacorn pertama Asia Tenggara', 'Mengubah Gojek dari ojek online jadi super-app', 'Menjabat Menteri Pendidikan yang menginisiasi program "Merdeka Belajar"'], kutipan: 'Jangan takut memulai dari yang kecil, karena dampak besar sering dimulai dari langkah kecil.', trivia: 'Idenya membangun Gojek berawal dari pengalamannya sendiri sering memakai jasa ojek langganan.', relasi: [{ nama: 'Joko Widodo', jenis: 'presiden yang mengangkatnya jadi menteri' }] },
  { nama: 'Beyoncé', namaEn: 'Beyoncé', lahir: { tahun: 1981, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Musik', pencapaian: ['Memenangkan Grammy Award terbanyak sepanjang sejarah untuk seorang artis', 'Memulai karier di girl group Destiny\'s Child sebelum sukses solo', 'Dikenal karena penampilan panggung megah dan pengaruh budaya lintas generasi'], kutipan: 'Kekuatan sejati tidak datang dari kekuatan fisik. Itu datang dari kemauan yang tak tergoyahkan.', trivia: 'Mengumumkan kehamilan kembarnya lewat unggahan media sosial paling banyak disukai saat itu.', relasi: [{ nama: 'Jay-Z', jenis: 'suami sekaligus sesama musisi berpengaruh' }] },
  { nama: 'Grace Hopper', namaEn: 'Grace Hopper', lahir: { tahun: 1906, negara: 'Amerika Serikat' }, wafat: 1992, bidang: 'Ilmu Komputer', pencapaian: ['Mengembangkan compiler pertama penerjemah bahasa manusia jadi kode mesin', 'Berperan besar mengembangkan bahasa pemrograman COBOL', 'Mencapai pangkat laksamana muda (rear admiral) di Angkatan Laut AS'], kutipan: 'Kapal aman di pelabuhan, tapi bukan itu tujuan kapal dibuat.', trivia: 'Dikreditkan mempopulerkan istilah "bug" komputer setelah menemukan ngengat tersangkut di mesin komputer awal.', relasi: [{ nama: 'John von Neumann', jenis: 'sesama perintis awal ilmu komputer' }] },
  { nama: 'Otto von Bismarck', namaEn: 'Otto von Bismarck', lahir: { tahun: 1815, negara: 'Jerman' }, wafat: 1898, bidang: 'Politik', pencapaian: ['Memimpin unifikasi negara-negara Jerman menjadi satu Kekaisaran Jerman 1871', 'Dijuluki "Kanselir Besi" karena kebijakan luar negeri yang tegas', 'Memperkenalkan sistem jaminan sosial pertama di dunia (asuransi kesehatan dan pensiun)'], kutipan: 'Politik adalah seni tentang yang mungkin.', trivia: 'Dikenal ahli diplomasi "realpolitik", mengutamakan kepentingan praktis negara di atas ideologi.', relasi: [{ nama: 'Kaiser Wilhelm I', jenis: 'raja yang memberinya mandat memimpin unifikasi Jerman' }] },
  { nama: 'Marco Polo', namaEn: 'Marco Polo', lahir: { tahun: 1254, negara: 'Republik Venesia (Italia)' }, wafat: 1324, bidang: 'Penjelajahan', pencapaian: ['Melakukan perjalanan darat sejauh ribuan kilometer dari Venesia hingga China', 'Menjadi tamu di istana Kubilai Khan selama sekitar 17 tahun', "Menulis catatan perjalanan 'The Travels of Marco Polo' yang memperkenalkan Asia ke Eropa"], kutipan: 'Aku bahkan belum menceritakan setengah dari yang kulihat.', trivia: 'Sempat dipenjara di Genoa dan mendiktekan kisah perjalanannya kepada teman satu selnya.', relasi: [{ nama: 'Kubilai Khan', jenis: 'tuan rumah sekaligus pemberi tugas diplomatik selama Polo tinggal di China' }] },
  { nama: 'Christopher Columbus', namaEn: 'Christopher Columbus', lahir: { tahun: 1451, negara: 'Republik Genoa (Italia)' }, wafat: 1506, bidang: 'Penjelajahan', pencapaian: ['Memimpin ekspedisi 1492 yang mencapai benua Amerika dari Eropa', 'Melakukan empat pelayaran melintasi Atlantik atas nama Kerajaan Spanyol', 'Membuka jalur kontak permanen pertama antara Eropa dan Amerika'], kutipan: 'Kau tidak akan pernah menyeberangi lautan kecuali kau berani kehilangan pantai dari pandangan.', trivia: 'Hingga wafat, ia tetap yakin telah mencapai Asia, bukan benua baru.', relasi: [{ nama: 'Ratu Isabella I dari Kastilia', jenis: 'penyandang dana kerajaan atas ekspedisinya' }] },
  { nama: 'Ferdinand Magellan', namaEn: 'Ferdinand Magellan', lahir: { tahun: 1480, negara: 'Portugal' }, wafat: 1521, bidang: 'Penjelajahan', pencapaian: ['Memimpin ekspedisi Eropa pertama yang berusaha mengelilingi dunia (1519-1522)', 'Menemukan selat penghubung Atlantik dan Pasifik yang kini bernama Selat Magellan', 'Membuktikan secara praktis bahwa bumi bisa dikelilingi lewat laut'], kutipan: 'Gereja bilang bumi itu datar, tapi aku tahu bumi itu bulat, karena aku pernah melihat bayangan bulan di atas bumi.', trivia: 'Ia sendiri tewas di Filipina sebelum ekspedisinya tuntas; hanya satu dari lima kapalnya yang berhasil pulang ke Spanyol.', relasi: [{ nama: 'Juan Sebastian Elcano', jenis: 'nakhoda yang menuntaskan pelayaran mengelilingi dunia setelah Magellan wafat' }] },
  { nama: 'Vasco da Gama', namaEn: 'Vasco da Gama', lahir: { tahun: 1460, negara: 'Portugal' }, wafat: 1524, bidang: 'Penjelajahan', pencapaian: ['Menjadi orang Eropa pertama yang mencapai India lewat jalur laut mengitari Afrika', 'Membuka rute dagang laut langsung antara Eropa dan Asia', 'Memimpin ekspedisi yang meletakkan dasar kekuasaan dagang Portugal di Samudra Hindia'], kutipan: 'Lautan yang luas hanya bisa ditaklukkan oleh mereka yang berani menantangnya.', trivia: 'Pelayarannya ke India memakan waktu hampir dua tahun pulang-pergi.', relasi: [{ nama: 'Bartolomeu Dias', jenis: 'navigator yang sebelumnya membuka jalur mengitari Tanjung Harapan' }] },
  { nama: 'James Cook', namaEn: 'James Cook', lahir: { tahun: 1728, negara: 'Inggris' }, wafat: 1779, bidang: 'Penjelajahan', pencapaian: ['Memetakan garis pantai Australia, Selandia Baru, dan banyak pulau Pasifik untuk pertama kalinya secara akurat', 'Memimpin tiga pelayaran besar eksplorasi Samudra Pasifik', 'Mengembangkan metode pencegahan penyakit skorbut pada awak kapalnya'], kutipan: 'Aku berambisi tidak hanya melangkah lebih jauh dari siapa pun sebelumnya, tapi sejauh yang mungkin bagi manusia.', trivia: 'Tewas dalam bentrokan dengan penduduk asli di Hawaii pada pelayaran ketiganya.', relasi: [{ nama: 'Joseph Banks', jenis: 'ilmuwan botani yang ikut dalam pelayaran pertamanya' }] },
  { nama: 'Ibnu Battuta', namaEn: 'Ibn Battuta', lahir: { tahun: 1304, negara: 'Maroko' }, wafat: 1369, bidang: 'Penjelajahan', pencapaian: ['Melakukan perjalanan sekitar 120.000 km melintasi hampir seluruh dunia Islam pada abad ke-14', 'Mengunjungi Afrika, Timur Tengah, Asia Selatan, Asia Tenggara, hingga China', "Mendiktekan catatan perjalanannya yang dikenal sebagai 'Rihla'"], kutipan: 'Perjalanan membuatmu bisu, lalu mengubahmu jadi pendongeng.', trivia: 'Perjalanannya jauh lebih panjang dibanding Marco Polo, namun kurang dikenal di dunia Barat.', relasi: [{ nama: 'Sultan Muhammad bin Tughluq', jenis: 'sultan Delhi yang mengangkatnya jadi hakim (qadi)' }] },
  { nama: 'Zheng He', namaEn: 'Zheng He', lahir: { tahun: 1371, negara: 'China' }, wafat: 1433, bidang: 'Penjelajahan', pencapaian: ['Memimpin tujuh ekspedisi maritim besar armada Dinasti Ming ke Asia Tenggara, Asia Selatan, hingga Afrika Timur', 'Memimpin armada dengan kapal-kapal raksasa yang jauh lebih besar dari kapal Eropa saat itu', 'Membangun hubungan dagang dan diplomatik China dengan puluhan negara'], kutipan: 'Lautan yang luas adalah jalan menuju kemakmuran, bukan penghalang.', trivia: 'Ia adalah seorang kasim istana yang dipercaya penuh oleh Kaisar Yongle untuk memimpin armada.', relasi: [{ nama: 'Kaisar Yongle', jenis: 'kaisar yang memerintahkan dan mendanai seluruh ekspedisinya' }] },
  { nama: 'Amerigo Vespucci', namaEn: 'Amerigo Vespucci', lahir: { tahun: 1454, negara: 'Republik Firenze (Italia)' }, wafat: 1512, bidang: 'Penjelajahan', pencapaian: ['Menjelajahi garis pantai Amerika Selatan dan menyimpulkannya sebagai benua baru, bukan Asia', 'Nama benua Amerika berasal dari versi Latin namanya', "Menulis catatan perjalanan yang mempopulerkan gagasan 'Dunia Baru' di Eropa"], kutipan: 'Aku menemukan sebuah benua yang lebih padat penduduknya dan lebih banyak hewannya daripada Eropa, Asia, atau Afrika.', trivia: "Ia tidak pernah memimpin ekspedisi utama sendiri, namun tulisannya yang menyebarkan gagasan 'benua baru' membuat namanya diabadikan.", relasi: [{ nama: 'Christopher Columbus', jenis: 'penjelajah pendahulu yang rutenya turut ia telusuri' }] },
  { nama: 'Roald Amundsen', namaEn: 'Roald Amundsen', lahir: { tahun: 1872, negara: 'Norwegia' }, wafat: 1928, bidang: 'Penjelajahan', pencapaian: ['Menjadi orang pertama yang mencapai Kutub Selatan pada 1911', 'Memimpin ekspedisi pertama yang berhasil melintasi Jalur Barat Laut (Northwest Passage)', 'Menjadi salah satu penjelajah kutub paling sukses dan sistematis pada masanya'], kutipan: 'Kemenangan menanti mereka yang memiliki segalanya secara teratur; orang menyebutnya keberuntungan.', trivia: 'Hilang dalam misi penyelamatan pesawat di Kutub Utara dan jasadnya tak pernah ditemukan.', relasi: [{ nama: 'Robert Falcon Scott', jenis: 'rival dalam perlombaan mencapai Kutub Selatan' }] },
  { nama: 'Edmund Hillary', namaEn: 'Edmund Hillary', lahir: { tahun: 1919, negara: 'Selandia Baru' }, wafat: 2008, bidang: 'Penjelajahan', pencapaian: ['Menjadi salah satu dari dua orang pertama yang mencapai puncak Gunung Everest pada 1953', 'Aktif dalam berbagai ekspedisi pendakian dan kutub sepanjang hidupnya', 'Mendirikan yayasan yang membangun sekolah dan klinik di wilayah Himalaya, Nepal'], kutipan: 'Bukan gunung yang kita taklukkan, melainkan diri kita sendiri.', trivia: 'Setelah pendakian Everest, ia menghabiskan puluhan tahun membantu masyarakat Sherpa di Nepal.', relasi: [{ nama: 'Tenzing Norgay', jenis: 'rekan pendakian yang bersamanya mencapai puncak Everest' }] },
  { nama: 'Tenzing Norgay', namaEn: 'Tenzing Norgay', lahir: { tahun: 1914, negara: 'Nepal' }, wafat: 1986, bidang: 'Penjelajahan', pencapaian: ['Menjadi salah satu dari dua orang pertama yang mencapai puncak Gunung Everest pada 1953', 'Merupakan pendaki Sherpa berpengalaman yang ikut serta dalam beberapa ekspedisi Everest sebelumnya', 'Menginspirasi generasi pendaki Sherpa setelahnya'], kutipan: 'Gunung bukan untuk ditaklukkan, tapi untuk dihormati.', trivia: 'Identitas siapa yang menjejakkan kaki lebih dulu di puncak, ia atau Hillary, sengaja tidak pernah diungkap keduanya.', relasi: [{ nama: 'Edmund Hillary', jenis: 'rekan pendakian yang bersamanya mencapai puncak Everest' }] },
  { nama: 'Yuri Gagarin', namaEn: 'Yuri Gagarin', lahir: { tahun: 1934, negara: 'Uni Soviet (Rusia)' }, wafat: 1968, bidang: 'Penjelajahan Antariksa', pencapaian: ['Menjadi manusia pertama yang terbang ke luar angkasa dan mengorbit bumi pada 1961', 'Menyelesaikan misi Vostok 1 dalam waktu sekitar 108 menit', 'Menjadi simbol pencapaian program antariksa Uni Soviet di masa Perang Dingin'], kutipan: 'Aku melihat Bumi. Sungguh indah.', trivia: 'Wafat dalam kecelakaan pesawat latih tujuh tahun setelah penerbangan bersejarahnya ke luar angkasa.', relasi: [{ nama: 'Valentina Tereshkova', jenis: 'sesama kosmonaut Soviet perintis penerbangan luar angkasa' }] },
  { nama: 'Jacques Cousteau', namaEn: 'Jacques Cousteau', lahir: { tahun: 1910, negara: 'Prancis' }, wafat: 1997, bidang: 'Penjelajahan Laut', pencapaian: ['Turut mengembangkan alat selam Aqua-Lung yang jadi cikal bakal scuba diving modern', "Membuat serial dokumenter laut 'The Undersea World of Jacques Cousteau' yang mendunia", 'Mempopulerkan kesadaran konservasi laut lewat penelitian dan filmnya'], kutipan: 'Lautan, sekali ia memikat kita, akan mengikat kita selamanya dalam jaring keajaiban.', trivia: 'Kapal risetnya, Calypso, menjadi salah satu kapal penelitian laut paling terkenal di dunia.', relasi: [{ nama: 'Emile Gagnan', jenis: 'insinyur yang bersamanya mengembangkan alat selam Aqua-Lung' }] },
  { nama: 'Ernest Shackleton', namaEn: 'Ernest Shackleton', lahir: { tahun: 1874, negara: 'Irlandia' }, wafat: 1922, bidang: 'Penjelajahan', pencapaian: ['Memimpin ekspedisi Endurance yang legendaris menyeberangi Antartika', 'Berhasil menyelamatkan seluruh awak kapalnya meski kapal Endurance hancur terjebak es', 'Dikenal sebagai teladan kepemimpinan dalam situasi bertahan hidup ekstrem'], kutipan: 'Kesulitan adalah hal yang biasa; keajaiban adalah caraku menghadapinya.', trivia: 'Meski ekspedisinya gagal mencapai tujuan awal, ia dikenang justru karena berhasil membawa pulang seluruh krunya hidup-hidup.', relasi: [{ nama: 'Frank Worsley', jenis: 'kapten kapal yang menavigasi perjalanan penyelamatan sejauh ratusan mil laut' }] },
  { nama: 'Ratu Elizabeth II', namaEn: 'Queen Elizabeth II', lahir: { tahun: 1926, negara: 'Inggris' }, wafat: 2022, bidang: 'Politik/Monarki', pencapaian: ['Menjadi raja/ratu Inggris dengan masa pemerintahan terlama dalam sejarah, 70 tahun', 'Naik takhta pada 1952 dan menyaksikan 15 perdana menteri Inggris silih berganti', 'Menjadi simbol kestabilan dan kesinambungan monarki Inggris di tengah perubahan zaman'], kutipan: 'Kesedihan adalah harga yang kita bayar untuk cinta.', trivia: 'Ia dilatih sebagai mekanik dan pengemudi truk militer semasa Perang Dunia II.', relasi: [{ nama: 'Pangeran Philip', jenis: 'suami sekaligus pendamping selama lebih dari 70 tahun pernikahan' }] },
  { nama: 'Jawaharlal Nehru', namaEn: 'Jawaharlal Nehru', lahir: { tahun: 1889, negara: 'India' }, wafat: 1964, bidang: 'Politik', pencapaian: ['Menjadi Perdana Menteri pertama India setelah kemerdekaan 1947', 'Memimpin India selama hampir 17 tahun dan meletakkan dasar demokrasi modern India', 'Menjadi salah satu tokoh penggagas Gerakan Non-Blok'], kutipan: 'Kemenangan dan kekalahan adalah dua sisi mata uang yang sama.', trivia: 'Ia menghabiskan total sekitar sembilan tahun di penjara kolonial Inggris karena aktivisme kemerdekaannya.', relasi: [{ nama: 'Mahatma Gandhi', jenis: 'mentor politik sekaligus tokoh yang membimbingnya dalam gerakan kemerdekaan India' }] },
  { nama: 'Kwame Nkrumah', namaEn: 'Kwame Nkrumah', lahir: { tahun: 1909, negara: 'Ghana' }, wafat: 1972, bidang: 'Politik', pencapaian: ['Memimpin Ghana meraih kemerdekaan pada 1957, negara Afrika sub-Sahara pertama yang merdeka dari kolonialisme', 'Menjadi presiden pertama Ghana', 'Menjadi salah satu penggagas gerakan Pan-Afrikanisme'], kutipan: 'Kebebasan tidak pernah datang secara sukarela dari penindas, ia harus diperjuangkan.', trivia: 'Digulingkan lewat kudeta militer pada 1966 saat sedang melakukan kunjungan luar negeri.', relasi: [{ nama: 'Kojo Botsio', jenis: 'rekan seperjuangan sekaligus menteri di pemerintahannya' }] },
  { nama: 'Lee Kuan Yew', namaEn: 'Lee Kuan Yew', lahir: { tahun: 1923, negara: 'Singapura' }, wafat: 2015, bidang: 'Politik', pencapaian: ['Menjadi Perdana Menteri pertama Singapura dan memimpin selama 31 tahun', 'Mentransformasi Singapura dari negara miskin sumber daya menjadi pusat ekonomi global', 'Menerapkan kebijakan tata kelola pemerintahan yang ketat namun efektif'], kutipan: 'Kami memutuskan lebih baik mempermudah orang, bukan mempersulitnya.', trivia: 'Ia fasih berbahasa Inggris, Mandarin, Melayu, dan Jepang.', relasi: [{ nama: 'Goh Keng Swee', jenis: 'rekan pendiri sekaligus arsitek ekonomi awal Singapura' }] },
  { nama: 'Simon Bolivar', namaEn: 'Simon Bolivar', lahir: { tahun: 1783, negara: 'Venezuela' }, wafat: 1830, bidang: 'Politik/Militer', pencapaian: ['Memimpin perjuangan kemerdekaan beberapa negara Amerika Selatan dari kekuasaan Spanyol', 'Turut mendirikan negara Gran Colombia yang meliputi beberapa negara modern saat ini', "Dijuluki 'El Libertador' (Sang Pembebas) di Amerika Selatan"], kutipan: 'Manusia yang mengabdi pada revolusi membajak lautan.', trivia: 'Negara Bolivia dinamai untuk menghormatinya.', relasi: [{ nama: 'Antonio Jose de Sucre', jenis: 'jenderal sekaligus rekan seperjuangan dalam perang kemerdekaan' }] },
  { nama: 'Golda Meir', namaEn: 'Golda Meir', lahir: { tahun: 1898, negara: 'Ukraina (Kekaisaran Rusia)' }, wafat: 1978, bidang: 'Politik', pencapaian: ['Menjadi Perdana Menteri wanita pertama Israel', 'Menjabat selama masa krisis termasuk Perang Yom Kippur 1973', 'Menjadi salah satu tokoh perempuan paling berpengaruh dalam sejarah politik Timur Tengah'], kutipan: 'Jangan biarkan siapa pun mengatakan padamu itu tidak bisa dilakukan.', trivia: 'Ia berimigrasi dari Rusia ke Amerika Serikat sebelum akhirnya menetap di wilayah yang kini menjadi Israel.', relasi: [{ nama: 'David Ben-Gurion', jenis: 'pendiri negara Israel yang menjadi rekan politiknya' }] },
  { nama: 'Justin Trudeau', namaEn: 'Justin Trudeau', lahir: { tahun: 1971, negara: 'Kanada' }, wafat: null, bidang: 'Politik', pencapaian: ['Menjadi Perdana Menteri Kanada sejak 2015', 'Dikenal karena kebijakan progresif soal imigrasi dan kesetaraan gender di kabinetnya', 'Melanjutkan warisan politik ayahnya, mantan PM Kanada Pierre Trudeau'], kutipan: 'Kanada yang lebih baik akan datang dari keberagaman, bukan meski adanya keberagaman.', trivia: 'Ayahnya, Pierre Trudeau, juga pernah menjabat Perdana Menteri Kanada beberapa dekade sebelumnya.', relasi: [{ nama: 'Pierre Trudeau', jenis: 'ayah yang juga menjabat Perdana Menteri Kanada' }] },
  { nama: 'Sun Yat-sen', namaEn: 'Sun Yat-sen', lahir: { tahun: 1866, negara: 'China' }, wafat: 1925, bidang: 'Politik', pencapaian: ['Memimpin revolusi yang mengakhiri kekuasaan dinasti kekaisaran China pada 1911', 'Menjadi presiden sementara pertama Republik China', "Dijuluki 'Bapak China Modern' di kedua sisi Selat Taiwan"], kutipan: 'Revolusi belum selesai, kawan-kawan harus terus berjuang.', trivia: 'Ia menerima pendidikan kedokteran Barat di Hong Kong sebelum terjun penuh ke gerakan revolusi.', relasi: [{ nama: 'Chiang Kai-shek', jenis: 'penerus yang melanjutkan kepemimpinan partai yang ia dirikan' }] },
  { nama: 'Jomo Kenyatta', namaEn: 'Jomo Kenyatta', lahir: { tahun: 1897, negara: 'Kenya' }, wafat: 1978, bidang: 'Politik', pencapaian: ['Memimpin Kenya meraih kemerdekaan dari Inggris pada 1963', 'Menjadi presiden pertama Kenya', 'Dikenal sebagai bapak pendiri bangsa Kenya modern'], kutipan: 'Kita semua sepakat bahwa kita bebas melakukan pembangunan tanpa campur tangan asing.', trivia: 'Sempat dipenjara selama bertahun-tahun oleh pemerintah kolonial Inggris atas tuduhan memimpin gerakan Mau Mau.', relasi: [{ nama: 'Oginga Odinga', jenis: 'wakil presiden pertama Kenya di bawah kepemimpinannya' }] },
  { nama: 'Amelia Earhart', namaEn: 'Amelia Earhart', lahir: { tahun: 1897, negara: 'Amerika Serikat' }, wafat: 1937, bidang: 'Penerbangan', pencapaian: ['Menjadi wanita pertama yang terbang solo melintasi Samudra Atlantik pada 1932', 'Memecahkan berbagai rekor penerbangan wanita pada masanya', 'Menjadi ikon pemberdayaan perempuan di dunia penerbangan awal abad ke-20'], kutipan: 'Petualangan itu sendiri sudah layak dijalani.', trivia: 'Ia hilang bersama pesawatnya saat mencoba mengelilingi dunia pada 1937 dan tak pernah ditemukan hingga kini.', relasi: [{ nama: 'Fred Noonan', jenis: 'navigator yang menyertainya dalam penerbangan terakhirnya' }] },
  { nama: 'Cut Nyak Dhien', namaEn: 'Cut Nyak Dhien', lahir: { tahun: 1848, negara: 'Aceh (Indonesia)' }, wafat: 1908, bidang: 'Aktivisme/Militer', pencapaian: ['Memimpin perlawanan rakyat Aceh melawan kolonial Belanda selama puluhan tahun', 'Melanjutkan perjuangan setelah suaminya, Teuku Umar, gugur di medan perang', 'Menjadi salah satu pahlawan nasional Indonesia dari kalangan perempuan'], kutipan: 'Lebih baik hancur lebur daripada tunduk kepada penjajah.', trivia: 'Diasingkan Belanda ke Sumedang, Jawa Barat, hingga akhir hayatnya karena dianggap masih berpengaruh di Aceh.', relasi: [{ nama: 'Teuku Umar', jenis: 'suami sekaligus rekan seperjuangan dalam Perang Aceh' }] },
  { nama: 'Wangari Maathai', namaEn: 'Wangari Maathai', lahir: { tahun: 1940, negara: 'Kenya' }, wafat: 2011, bidang: 'Aktivisme Lingkungan', pencapaian: ['Mendirikan Green Belt Movement yang telah menanam puluhan juta pohon di Afrika', 'Menjadi wanita Afrika pertama yang meraih Hadiah Nobel Perdamaian (2004)', 'Mengaitkan pelestarian lingkungan dengan demokrasi dan hak-hak perempuan'], kutipan: 'Sampai kau menanam pohon, kau tidak benar-benar tahu betapa manisnya air dan betapa segarnya udara.', trivia: 'Ia adalah wanita di Afrika Timur dan Tengah pertama yang meraih gelar doktor.', relasi: [{ nama: 'Al Gore', jenis: 'sesama peraih Nobel Perdamaian yang juga aktif isu lingkungan' }] },
  { nama: 'Katherine Johnson', namaEn: 'Katherine Johnson', lahir: { tahun: 1918, negara: 'Amerika Serikat' }, wafat: 2020, bidang: 'Matematika/Antariksa', pencapaian: ['Menghitung lintasan penerbangan luar angkasa untuk misi-misi awal NASA termasuk misi John Glenn', 'Menjadi salah satu matematikawan kulit hitam pertama yang bekerja di NASA', 'Perhitungannya turut memastikan keberhasilan misi pendaratan di Bulan Apollo 11'], kutipan: 'Perempuan selalu melakukan pekerjaan yang sama dengan pria, kami hanya perlu diberi kesempatan.', trivia: "Kisahnya diangkat dalam film 'Hidden Figures' yang mengangkat peran ilmuwan kulit hitam di NASA.", relasi: [{ nama: 'John Glenn', jenis: 'astronot yang secara khusus memintanya memverifikasi ulang perhitungan orbitnya' }] },
  { nama: 'Indira Gandhi', namaEn: 'Indira Gandhi', lahir: { tahun: 1917, negara: 'India' }, wafat: 1984, bidang: 'Politik', pencapaian: ['Menjadi Perdana Menteri wanita pertama India', 'Memimpin India selama total 15 tahun dalam beberapa periode', 'Memimpin India melalui perang dengan Pakistan pada 1971'], kutipan: 'Kekuatan sejati tidak butuh persetujuan; ia hanya perlu keyakinan.', trivia: 'Ia bukan kerabat Mahatma Gandhi meski memiliki nama belakang yang sama.', relasi: [{ nama: 'Jawaharlal Nehru', jenis: 'ayah sekaligus Perdana Menteri India pertama' }] },
  { nama: 'Sor Juana Ines de la Cruz', namaEn: 'Sor Juana Ines de la Cruz', lahir: { tahun: 1648, negara: 'Meksiko' }, wafat: 1695, bidang: 'Sastra', pencapaian: ['Menjadi salah satu penyair dan penulis paling berpengaruh di era kolonial Amerika Latin', 'Menulis pembelaan hak perempuan atas pendidikan dalam suratnya yang terkenal', 'Menguasai berbagai bidang ilmu meski hidup dalam biara pada masa itu'], kutipan: 'Aku tidak belajar untuk mengajar orang lain, tapi agar ketidaktahuanku sendiri lebih sedikit.', trivia: 'Ia belajar membaca sejak usia tiga tahun dan menguasai bahasa Latin secara otodidak.', relasi: [{ nama: 'Carlos de Sigüenza y Gongora', jenis: 'sahabat intelektual sezamannya di Meksiko kolonial' }] },
  { nama: 'Wu Zetian', namaEn: 'Wu Zetian', lahir: { tahun: 624, negara: 'China' }, wafat: 705, bidang: 'Politik', pencapaian: ['Menjadi satu-satunya wanita yang secara resmi memerintah China sebagai kaisar', 'Mendirikan Dinasti Zhou yang berlangsung singkat namun berpengaruh', 'Memperluas sistem ujian negara untuk merekrut pejabat berdasar kemampuan, bukan keturunan'], kutipan: 'Kekuasaan bukan diberikan, ia direbut oleh yang paling teguh niatnya.', trivia: 'Ia memulai kariernya sebagai selir istana sebelum akhirnya menjadi penguasa tunggal China.', relasi: [{ nama: 'Kaisar Gaozong', jenis: 'suami sekaligus kaisar sebelumnya yang kekuasaannya ia lanjutkan' }] },
  { nama: 'Simone de Beauvoir', namaEn: 'Simone de Beauvoir', lahir: { tahun: 1908, negara: 'Prancis' }, wafat: 1986, bidang: 'Filsafat/Sastra', pencapaian: ["Menulis 'The Second Sex', karya fundamental dalam teori feminisme modern", 'Menjadi salah satu tokoh utama gerakan eksistensialisme Prancis', 'Aktif menulis novel, esai, dan otobiografi sepanjang kariernya'], kutipan: 'Seseorang tidak dilahirkan, melainkan menjadi, seorang perempuan.', trivia: 'Menjalin hubungan intelektual jangka panjang dengan filsuf Jean-Paul Sartre tanpa pernah menikah.', relasi: [{ nama: 'Jean-Paul Sartre', jenis: 'pasangan intelektual sekaligus sesama filsuf eksistensialis' }] },
  { nama: 'Benazir Bhutto', namaEn: 'Benazir Bhutto', lahir: { tahun: 1953, negara: 'Pakistan' }, wafat: 2007, bidang: 'Politik', pencapaian: ['Menjadi Perdana Menteri wanita pertama di negara mayoritas Muslim', 'Menjabat dua periode sebagai Perdana Menteri Pakistan', 'Aktif memperjuangkan demokrasi di tengah gejolak politik Pakistan'], kutipan: 'Demokrasi adalah balas dendam terbaik.', trivia: 'Ia dibunuh dalam serangan saat kampanye pemilu 2007.', relasi: [{ nama: 'Zulfikar Ali Bhutto', jenis: 'ayah sekaligus mantan Perdana Menteri Pakistan' }] },
  { nama: 'Valentina Tereshkova', namaEn: 'Valentina Tereshkova', lahir: { tahun: 1937, negara: 'Uni Soviet (Rusia)' }, wafat: null, bidang: 'Penjelajahan Antariksa', pencapaian: ['Menjadi wanita pertama yang terbang ke luar angkasa pada misi Vostok 6 tahun 1963', 'Mengorbit Bumi sebanyak 48 kali dalam misinya', 'Tetap menjadi satu-satunya wanita yang pernah menjalankan misi luar angkasa solo'], kutipan: 'Sekali kau pernah terbang ke luar angkasa, kau menyadari betapa kecilnya Bumi kita.', trivia: 'Sebelum jadi kosmonaut, ia adalah pekerja pabrik tekstil dan penerjun payung amatir.', relasi: [{ nama: 'Yuri Gagarin', jenis: 'sesama kosmonaut Soviet perintis penerbangan luar angkasa' }] },
  { nama: 'Aung San Suu Kyi', namaEn: 'Aung San Suu Kyi', lahir: { tahun: 1945, negara: 'Myanmar' }, wafat: null, bidang: 'Politik/Aktivisme', pencapaian: ['Memimpin gerakan pro-demokrasi Myanmar selama puluhan tahun', 'Menerima Hadiah Nobel Perdamaian 1991 atas perjuangannya tanpa kekerasan', 'Menjalani tahanan rumah selama total sekitar 15 tahun oleh junta militer'], kutipan: 'Bukan kekuasaan yang merusak, melainkan ketakutan yang menyebabkan korupsi.', trivia: 'Ayahnya, Aung San, adalah pahlawan kemerdekaan Myanmar yang dibunuh saat ia masih kecil.', relasi: [{ nama: 'Aung San', jenis: 'ayah sekaligus pahlawan kemerdekaan Myanmar' }] },
  { nama: 'Nawal El Saadawi', namaEn: 'Nawal El Saadawi', lahir: { tahun: 1931, negara: 'Mesir' }, wafat: 2021, bidang: 'Aktivisme/Sastra', pencapaian: ['Menjadi salah satu penulis feminis paling berpengaruh di dunia Arab', 'Menentang praktik sunat perempuan lewat tulisan dan aktivismenya', 'Menulis puluhan buku yang diterjemahkan ke berbagai bahasa dunia'], kutipan: 'Menulis bagiku bukan pilihan, melainkan cara bertahan hidup.', trivia: 'Ia pernah dipenjara oleh pemerintah Mesir karena tulisannya yang kritis.', relasi: [{ nama: 'Simone de Beauvoir', jenis: 'sesama tokoh feminis yang pemikirannya turut memengaruhinya' }] },
  { nama: 'Sirimavo Bandaranaike', namaEn: 'Sirimavo Bandaranaike', lahir: { tahun: 1916, negara: 'Sri Lanka' }, wafat: 2000, bidang: 'Politik', pencapaian: ['Menjadi kepala pemerintahan wanita pertama di dunia pada 1960', 'Menjabat Perdana Menteri Sri Lanka dalam tiga periode berbeda', 'Meletakkan dasar bagi keterlibatan perempuan dalam politik puncak dunia'], kutipan: 'Kepemimpinan bukan soal gender, tapi soal keberanian mengambil tanggung jawab.', trivia: 'Ia meneruskan karier politik mendiang suaminya, Perdana Menteri Solomon Bandaranaike, yang terbunuh.', relasi: [{ nama: 'Solomon Bandaranaike', jenis: 'suami sekaligus Perdana Menteri Sri Lanka sebelumnya' }] },
  { nama: 'Dewi Sartika', namaEn: 'Dewi Sartika', lahir: { tahun: 1884, negara: 'Indonesia' }, wafat: 1947, bidang: 'Pendidikan', pencapaian: ['Mendirikan Sakola Istri, sekolah untuk perempuan pribumi pertama di Jawa Barat', 'Memelopori pendidikan formal bagi perempuan Indonesia di masa kolonial', 'Menjadi pahlawan nasional Indonesia atas jasanya di bidang pendidikan'], kutipan: 'Pendidikan bagi perempuan adalah kunci kemajuan bangsa.', trivia: 'Ia mendirikan sekolahnya pada usia sekitar 20 tahun dengan modal dan fasilitas yang sangat terbatas.', relasi: [{ nama: 'Raden Ajeng Kartini', jenis: 'sesama pelopor pendidikan perempuan di masa kolonial' }] },
  { nama: 'Michelle Obama', namaEn: 'Michelle Obama', lahir: { tahun: 1964, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Advokasi/Penulis', pencapaian: ['Menjadi Ibu Negara Amerika Serikat periode 2009-2017', "Memelopori kampanye gizi anak 'Let's Move!'", "Menulis memoar 'Becoming' yang menjadi buku terlaris dunia"], kutipan: 'Saat mereka merendahkan, kita meninggikan.', trivia: 'Ia meraih gelar sarjana hukum dari Harvard sebelum bertemu Barack Obama di firma hukum tempatnya bekerja.', relasi: [{ nama: 'Barack Obama', jenis: 'suami sekaligus mantan Presiden Amerika Serikat' }] },
  { nama: 'Sheikh Hasina', namaEn: 'Sheikh Hasina', lahir: { tahun: 1947, negara: 'Bangladesh' }, wafat: null, bidang: 'Politik', pencapaian: ['Menjabat sebagai Perdana Menteri Bangladesh dalam beberapa periode', 'Memimpin salah satu periode pemerintahan terlama dalam sejarah Bangladesh modern', 'Aktif dalam pembangunan ekonomi dan infrastruktur Bangladesh'], kutipan: 'Perjuangan bagi rakyat tidak pernah benar-benar selesai.', trivia: 'Ayahnya, Sheikh Mujibur Rahman, adalah bapak pendiri sekaligus presiden pertama Bangladesh.', relasi: [{ nama: 'Sheikh Mujibur Rahman', jenis: 'ayah sekaligus presiden pertama Bangladesh' }] },
  { nama: 'Harriet Tubman', namaEn: 'Harriet Tubman', lahir: { tahun: 1822, negara: 'Amerika Serikat' }, wafat: 1913, bidang: 'Aktivisme', pencapaian: ['Membebaskan diri dari perbudakan lalu berulang kali kembali membebaskan puluhan budak lain lewat Underground Railroad', 'Menjadi mata-mata dan pemandu untuk militer Union saat Perang Saudara Amerika', 'Aktif memperjuangkan hak pilih perempuan di masa tuanya'], kutipan: 'Aku pernah bicara dengan Tuhan, dan Ia bicara padaku setiap pagi.', trivia: 'Wajahnya direncanakan menggantikan Andrew Jackson di uang kertas 20 dolar Amerika.', relasi: [{ nama: 'Frederick Douglass', jenis: 'sesama tokoh anti-perbudakan sezamannya' }] },
  { nama: 'Sri Mulyani Indrawati', namaEn: 'Sri Mulyani Indrawati', lahir: { tahun: 1962, negara: 'Indonesia' }, wafat: null, bidang: 'Ekonomi/Politik', pencapaian: ['Menjabat Menteri Keuangan Indonesia dalam beberapa periode berbeda', 'Pernah menjabat Direktur Pelaksana Bank Dunia, posisi tertinggi yang pernah diraih orang Indonesia di lembaga itu', 'Dikenal atas reformasi tata kelola keuangan negara yang ia jalankan'], kutipan: 'Integritas adalah modal paling mahal dalam mengelola keuangan negara.', trivia: 'Ia sempat meninggalkan jabatan menteri untuk bekerja di Bank Dunia sebelum kembali menjabat menteri di kabinet berikutnya.', relasi: [{ nama: 'Boediono', jenis: 'mantan Wakil Presiden yang juga sesama ekonom di pemerintahan' }] },
  { nama: 'Cleopatra', namaEn: 'Cleopatra VII', lahir: { tahun: -69, negara: 'Mesir' }, wafat: -30, bidang: 'Politik', pencapaian: ['Menjadi firaun terakhir Mesir Kuno dari Dinasti Ptolemaik', 'Menguasai beberapa bahasa termasuk bahasa Mesir kuno, tidak seperti penguasa Ptolemaik sebelumnya', 'Menjalin aliansi politik dengan dua tokoh besar Romawi, Julius Caesar dan Mark Antony'], kutipan: 'Aku tidak akan diarak sebagai budak.', trivia: 'Konon ia mengakhiri hidupnya dengan gigitan ular berbisa setelah kekalahan dari Romawi.', relasi: [{ nama: 'Julius Caesar', jenis: 'sekutu politik sekaligus pasangan' }] },
  { nama: 'Wolfgang Amadeus Mozart', namaEn: 'Wolfgang Amadeus Mozart', lahir: { tahun: 1756, negara: 'Austria' }, wafat: 1791, bidang: 'Musik Klasik', pencapaian: ['Menggubah lebih dari 600 karya musik sepanjang hidupnya yang singkat', 'Mulai mengomposisi musik sejak usia lima tahun sebagai anak ajaib', "Karyanya seperti 'The Magic Flute' dan Requiem tetap dipentaskan hingga kini"], kutipan: 'Musik bukan di dalam nada, melainkan di dalam keheningan di antaranya.', trivia: 'Ia wafat di usia 35 tahun dalam keadaan miskin dan dimakamkan di kuburan biasa tanpa tanda khusus.', relasi: [{ nama: 'Joseph Haydn', jenis: 'sahabat sekaligus sesama komponis besar era Klasik' }] },
  { nama: 'Raden Saleh', namaEn: 'Raden Saleh', lahir: { tahun: 1811, negara: 'Indonesia' }, wafat: 1880, bidang: 'Seni Lukis', pencapaian: ['Menjadi pelukis modern pertama Indonesia yang diakui di kancah internasional', 'Belajar melukis di Eropa dan menggabungkan gaya romantisisme Eropa dengan tema Nusantara', "Melukis karya terkenal 'Penangkapan Pangeran Diponegoro'"], kutipan: 'Lukisan adalah caraku bicara tentang tanah airku kepada dunia.', trivia: 'Ia tinggal dan belajar di Eropa selama lebih dari 20 tahun sebelum kembali ke Hindia Belanda.', relasi: [{ nama: 'Pangeran Diponegoro', jenis: 'tokoh yang penangkapannya ia abadikan dalam lukisan paling terkenalnya' }] },
  { nama: 'Alexander Graham Bell', namaEn: 'Alexander Graham Bell', lahir: { tahun: 1847, negara: 'Skotlandia' }, wafat: 1922, bidang: 'Teknologi', pencapaian: ['Dikreditkan sebagai penemu telepon yang bisa dipatenkan pertama pada 1876', 'Mendirikan Bell Telephone Company yang jadi cikal bakal industri telekomunikasi modern', 'Aktif juga dalam riset penerbangan dan alat bantu dengar'], kutipan: 'Kadang kita begitu sibuk menatap pintu yang tertutup hingga tak melihat pintu lain yang terbuka.', trivia: 'Ia juga aktif mengajar tunarungu, terinspirasi dari ibu dan istrinya yang tunarungu.', relasi: [{ nama: 'Thomas Watson', jenis: 'asisten yang menerima panggilan telepon pertama dalam sejarah darinya' }] },
  { nama: 'Tim Berners-Lee', namaEn: 'Tim Berners-Lee', lahir: { tahun: 1955, negara: 'Inggris' }, wafat: null, bidang: 'Teknologi', pencapaian: ['Menciptakan World Wide Web pada 1989 saat bekerja di CERN', 'Mengembangkan HTML, HTTP, dan URL, fondasi dasar internet modern', 'Memilih tidak mematenkan penemuannya agar Web bisa dipakai bebas oleh semua orang'], kutipan: 'Web ini untuk semua orang.', trivia: 'Ia sengaja tidak mengambil keuntungan finansial dari penemuannya demi menjaga Web tetap terbuka dan gratis.', relasi: [{ nama: 'Robert Cailliau', jenis: 'rekan kerja di CERN yang turut mengembangkan World Wide Web' }] },
  { nama: 'Guglielmo Marconi', namaEn: 'Guglielmo Marconi', lahir: { tahun: 1874, negara: 'Italia' }, wafat: 1937, bidang: 'Teknologi', pencapaian: ['Mengembangkan sistem komunikasi radio nirkabel jarak jauh pertama yang praktis', 'Berhasil mengirim sinyal radio melintasi Samudra Atlantik pada 1901', 'Meraih Hadiah Nobel Fisika 1909 atas kontribusinya pada telegrafi nirkabel'], kutipan: 'Kadang penemuan besar lahir bukan dari kejeniusan, tapi dari keteguhan mencoba berulang kali.', trivia: 'Teknologi radionya berperan menyelamatkan ratusan penumpang kapal Titanic yang mengirim sinyal darurat.', relasi: [{ nama: 'Nikola Tesla', jenis: 'sesama perintis teknologi radio yang klaim penemuannya sempat diperdebatkan' }] },
  { nama: 'Wright Bersaudara', namaEn: 'Wright Brothers', lahir: { tahun: 1871, negara: 'Amerika Serikat' }, wafat: 1948, bidang: 'Penerbangan', pencapaian: ['Merancang dan menerbangkan pesawat bermesin pertama yang berhasil terbang terkendali pada 1903', 'Mengembangkan sistem kendali tiga sumbu yang jadi dasar desain pesawat modern', 'Mendirikan perusahaan pesawat terbang pertama di Amerika Serikat'], kutipan: 'Jika kau mencari rahasia keberhasilan kami, semuanya ada pada satu hal: tidak pernah berhenti mempelajari masalah terbang.', trivia: 'Keduanya awalnya adalah pemilik toko sepeda sebelum beralih total ke riset penerbangan.', relasi: [{ nama: 'Octave Chanute', jenis: 'insinyur senior yang menjadi mentor dan penasihat mereka' }] },
  { nama: 'Ibnu Sina', namaEn: 'Avicenna', lahir: { tahun: 980, negara: 'Persia (Bukhara)' }, wafat: 1037, bidang: 'Kedokteran/Filsafat', pencapaian: ["Menulis 'Canon of Medicine', buku kedokteran yang jadi rujukan utama di Eropa dan dunia Islam selama berabad-abad", 'Menyumbang pemikiran besar di bidang filsafat, logika, dan astronomi', 'Menjadi salah satu ilmuwan paling berpengaruh pada Zaman Keemasan Islam'], kutipan: 'Dunia terbagi menjadi mereka yang berpikir dan mereka yang tidak; keduanya butuh yang lain untuk mengerti.', trivia: "Ia sudah hafal Al-Qur'an dan menguasai banyak bidang ilmu sebelum usia 18 tahun.", relasi: [{ nama: 'Al-Biruni', jenis: 'cendekiawan sezaman yang kerap berkorespondensi dengannya soal sains' }] },
  { nama: 'Carl Sagan', namaEn: 'Carl Sagan', lahir: { tahun: 1934, negara: 'Amerika Serikat' }, wafat: 1996, bidang: 'Astronomi', pencapaian: ["Membuat dan memandu serial dokumenter sains 'Cosmos' yang ditonton jutaan orang di seluruh dunia", 'Berperan besar dalam misi eksplorasi antariksa NASA termasuk misi Voyager', 'Menulis banyak buku sains populer yang mempermudah publik memahami astronomi'], kutipan: 'Kita adalah cara alam semesta mengenal dirinya sendiri.', trivia: "Ia mengusulkan ide 'Pale Blue Dot', potret Bumi dari kejauhan luar angkasa yang diambil wahana Voyager 1.", relasi: [{ nama: 'Ann Druyan', jenis: 'istri sekaligus rekan penulis dalam banyak proyek sainsnya' }] },
  { nama: 'Louis Pasteur', namaEn: 'Louis Pasteur', lahir: { tahun: 1822, negara: 'Prancis' }, wafat: 1895, bidang: 'Kimia/Mikrobiologi', pencapaian: ['Mengembangkan teknik pasteurisasi untuk membunuh mikroba berbahaya dalam makanan dan minuman', 'Mengembangkan vaksin rabies pertama yang efektif', 'Membuktikan teori kuman penyakit (germ theory) yang mengubah dunia kedokteran modern'], kutipan: 'Kebetulan hanya memihak pikiran yang sudah siap.', trivia: 'Vaksin rabiesnya pertama kali diujikan pada manusia untuk menyelamatkan seorang anak yang digigit anjing gila.', relasi: [{ nama: 'Robert Koch', jenis: 'ilmuwan sezaman yang turut mengembangkan teori kuman penyakit' }] },
  { nama: 'Rosalind Franklin', namaEn: 'Rosalind Franklin', lahir: { tahun: 1920, negara: 'Inggris' }, wafat: 1958, bidang: 'Kimia/Biologi', pencapaian: ["Menghasilkan foto difraksi sinar-X 'Photo 51' yang jadi kunci penemuan struktur DNA", 'Melakukan riset penting tentang struktur virus dan batu bara sepanjang kariernya', 'Karyanya menjadi dasar penting bagi model DNA heliks ganda Watson dan Crick'], kutipan: 'Sains dan kehidupan sehari-hari tidak bisa dan tidak boleh dipisahkan.', trivia: 'Kontribusinya pada penemuan struktur DNA baru diakui luas setelah ia wafat, tanpa sempat menerima Nobel yang diberikan pada Watson, Crick, dan Wilkins.', relasi: [{ nama: 'James Watson', jenis: 'ilmuwan yang risetnya soal DNA memanfaatkan data foto difraksinya' }] },
  { nama: 'Werner Heisenberg', namaEn: 'Werner Heisenberg', lahir: { tahun: 1901, negara: 'Jerman' }, wafat: 1976, bidang: 'Fisika', pencapaian: ['Merumuskan prinsip ketidakpastian yang jadi dasar mekanika kuantum modern', 'Meraih Hadiah Nobel Fisika 1932 atas kontribusinya pada mekanika kuantum', 'Mengembangkan salah satu formulasi matematis pertama mekanika kuantum'], kutipan: 'Apa yang kita amati bukanlah alam itu sendiri, melainkan alam yang terungkap lewat metode pengamatan kita.', trivia: 'Prinsip ketidakpastiannya menyatakan posisi dan momentum partikel tak bisa diukur bersamaan secara pasti.', relasi: [{ nama: 'Niels Bohr', jenis: 'mentor sekaligus rekan diskusi utama dalam pengembangan mekanika kuantum' }] },
  { nama: 'Erwin Schrödinger', namaEn: 'Erwin Schrödinger', lahir: { tahun: 1887, negara: 'Austria' }, wafat: 1961, bidang: 'Fisika', pencapaian: ['Merumuskan persamaan gelombang yang jadi dasar mekanika kuantum modern', 'Meraih Hadiah Nobel Fisika 1933 atas kontribusinya pada teori atom', "Mempopulerkan eksperimen pemikiran 'kucing Schrödinger' untuk menjelaskan paradoks kuantum"], kutipan: 'Keseluruhan ilmu bertujuan mengoordinasikan pengalaman kita dan menyusunnya jadi sistem logis.', trivia: 'Eksperimen pemikiran kucingnya awalnya dimaksudkan sebagai kritik, bukan penjelasan, atas mekanika kuantum.', relasi: [{ nama: 'Werner Heisenberg', jenis: 'rekan sekaligus rival dalam merumuskan fondasi mekanika kuantum' }] },
  { nama: 'Max Planck', namaEn: 'Max Planck', lahir: { tahun: 1858, negara: 'Jerman' }, wafat: 1947, bidang: 'Fisika', pencapaian: ['Merumuskan teori kuantum yang menjadi awal mula fisika kuantum modern', 'Meraih Hadiah Nobel Fisika 1918 atas penemuan kuanta energi', 'Konstanta Planck yang ia temukan jadi salah satu konstanta fundamental fisika'], kutipan: 'Sains maju satu pemakaman demi satu pemakaman.', trivia: 'Ia awalnya ragu mempublikasikan idenya tentang kuanta karena dianggap terlalu radikal pada masanya.', relasi: [{ nama: 'Albert Einstein', jenis: 'ilmuwan yang mengembangkan lebih jauh gagasan kuantumnya' }] },
  { nama: 'Richard Feynman', namaEn: 'Richard Feynman', lahir: { tahun: 1918, negara: 'Amerika Serikat' }, wafat: 1988, bidang: 'Fisika', pencapaian: ['Mengembangkan diagram Feynman yang menyederhanakan perhitungan elektrodinamika kuantum', 'Meraih Hadiah Nobel Fisika 1965 atas kontribusinya pada elektrodinamika kuantum', 'Dikenal sebagai pengajar fisika populer lewat buku dan kuliahnya yang khas'], kutipan: 'Aku pikir aku bisa dengan aman mengatakan bahwa tidak ada orang yang benar-benar memahami mekanika kuantum.', trivia: 'Ia turut menjadi anggota tim investigasi kecelakaan pesawat ulang-alik Challenger tahun 1986.', relasi: [{ nama: 'Murray Gell-Mann', jenis: 'rekan fisikawan sekaligus rival intelektual di Caltech' }] },
  { nama: 'Dmitri Mendeleev', namaEn: 'Dmitri Mendeleev', lahir: { tahun: 1834, negara: 'Rusia' }, wafat: 1907, bidang: 'Kimia', pencapaian: ['Menyusun tabel periodik unsur kimia yang jadi dasar kimia modern', 'Berhasil memprediksi keberadaan unsur-unsur yang belum ditemukan pada masanya', 'Karya tabel periodiknya tetap dipakai dan dikembangkan hingga sekarang'], kutipan: 'Unsur-unsur, jika disusun berdasarkan berat atomnya, menunjukkan pengulangan sifat yang jelas.', trivia: 'Ia konon menyusun idenya tentang tabel periodik setelah bermimpi melihat unsur-unsur tersusun rapi.', relasi: [{ nama: 'Lothar Meyer', jenis: 'ilmuwan Jerman yang mengembangkan tabel periodik serupa secara independen' }] },
  { nama: 'Antoine Lavoisier', namaEn: 'Antoine Lavoisier', lahir: { tahun: 1743, negara: 'Prancis' }, wafat: 1794, bidang: 'Kimia', pencapaian: ['Merumuskan hukum kekekalan massa dalam reaksi kimia', 'Membantah teori flogiston dan menjelaskan peran oksigen dalam pembakaran', "Dijuluki 'Bapak Kimia Modern' atas metode ilmiahnya yang sistematis"], kutipan: 'Tidak ada yang hilang, tidak ada yang tercipta, semuanya berubah bentuk.', trivia: 'Ia dieksekusi lewat guillotine pada masa Revolusi Prancis meski jasanya di bidang sains sangat besar.', relasi: [{ nama: 'Marie-Anne Paulze Lavoisier', jenis: 'istri sekaligus asisten riset yang menerjemahkan dan mengilustrasikan karyanya' }] },
  { nama: 'Michael Faraday', namaEn: 'Michael Faraday', lahir: { tahun: 1791, negara: 'Inggris' }, wafat: 1867, bidang: 'Fisika/Kimia', pencapaian: ['Menemukan prinsip induksi elektromagnetik yang jadi dasar generator dan motor listrik modern', 'Menemukan hukum elektrolisis dalam bidang kimia', 'Berkontribusi besar pada pemahaman medan listrik dan magnet'], kutipan: 'Tidak ada yang terlalu mengagumkan untuk jadi kenyataan, jika sesuai dengan hukum alam.', trivia: 'Ia hanya menempuh pendidikan formal minim namun jadi salah satu ilmuwan eksperimental terbesar sepanjang masa.', relasi: [{ nama: 'James Clerk Maxwell', jenis: 'ilmuwan yang merumuskan penemuan-penemuannya ke dalam persamaan matematis' }] },
  { nama: 'James Clerk Maxwell', namaEn: 'James Clerk Maxwell', lahir: { tahun: 1831, negara: 'Skotlandia' }, wafat: 1879, bidang: 'Fisika', pencapaian: ['Merumuskan persamaan Maxwell yang menyatukan listrik, magnet, dan cahaya dalam satu teori elektromagnetik', 'Membuktikan secara matematis bahwa cahaya adalah gelombang elektromagnetik', 'Meletakkan dasar teoretis bagi banyak teknologi komunikasi modern'], kutipan: 'Satu-satunya hukum materi adalah hukum yang belum kita ketahui saja.', trivia: 'Persamaannya kelak menjadi dasar penting yang menginspirasi teori relativitas Einstein.', relasi: [{ nama: 'Michael Faraday', jenis: 'ilmuwan eksperimental yang temuannya ia rumuskan secara matematis' }] },
  { nama: 'Alexander Fleming', namaEn: 'Alexander Fleming', lahir: { tahun: 1881, negara: 'Skotlandia' }, wafat: 1955, bidang: 'Kedokteran', pencapaian: ['Menemukan penisilin secara tidak sengaja pada 1928, antibiotik modern pertama', 'Meraih Hadiah Nobel Fisiologi atau Kedokteran 1945 bersama dua ilmuwan lain', 'Penemuannya membuka era baru pengobatan infeksi bakteri'], kutipan: 'Kadang orang menemukan sesuatu yang tidak mereka cari.', trivia: 'Penemuan penisilinnya bermula dari jamur yang tumbuh tak sengaja di cawan petri yang lupa ia bersihkan.', relasi: [{ nama: 'Howard Florey', jenis: 'ilmuwan yang mengembangkan penisilin hingga bisa diproduksi massal' }] },
  { nama: 'Edward Jenner', namaEn: 'Edward Jenner', lahir: { tahun: 1749, negara: 'Inggris' }, wafat: 1823, bidang: 'Kedokteran', pencapaian: ['Mengembangkan vaksin cacar pertama di dunia pada 1796', 'Meletakkan dasar ilmu imunologi dan vaksinasi modern', 'Penemuannya berperan besar dalam pemberantasan penyakit cacar secara global'], kutipan: 'Aku berharap suatu hari praktik menularkan cacar sapi pada manusia akan menghapus cacar dari muka bumi.', trivia: 'Eksperimen vaksin pertamanya dilakukan pada seorang anak berusia delapan tahun, James Phipps.', relasi: [{ nama: 'Louis Pasteur', jenis: 'ilmuwan yang mengembangkan lebih lanjut prinsip vaksinasi setelahnya' }] },
  { nama: 'James Watson', namaEn: 'James Watson', lahir: { tahun: 1928, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Biologi', pencapaian: ['Turut menemukan struktur heliks ganda DNA bersama Francis Crick pada 1953', 'Meraih Hadiah Nobel Fisiologi atau Kedokteran 1962 atas penemuan struktur DNA', "Menulis buku 'The Double Helix' yang mengisahkan proses penemuan tersebut"], kutipan: 'Gen bukan takdir.', trivia: 'Penemuan strukturnya sangat bergantung pada data foto difraksi sinar-X milik Rosalind Franklin.', relasi: [{ nama: 'Francis Crick', jenis: 'rekan penemu struktur DNA heliks ganda' }] },
  { nama: 'Francis Crick', namaEn: 'Francis Crick', lahir: { tahun: 1916, negara: 'Inggris' }, wafat: 2004, bidang: 'Biologi', pencapaian: ['Turut menemukan struktur heliks ganda DNA bersama James Watson pada 1953', 'Meraih Hadiah Nobel Fisiologi atau Kedokteran 1962 atas penemuan struktur DNA', 'Merumuskan konsep dogma sentral biologi molekuler'], kutipan: 'Jika kau ingin sukses dalam sains, kau perlu berpikir sedikit gila.', trivia: 'Sebelum meneliti DNA, ia awalnya belajar fisika sebelum beralih ke bidang biologi molekuler.', relasi: [{ nama: 'James Watson', jenis: 'rekan penemu struktur DNA heliks ganda' }] },
  { nama: 'Enrico Fermi', namaEn: 'Enrico Fermi', lahir: { tahun: 1901, negara: 'Italia' }, wafat: 1954, bidang: 'Fisika', pencapaian: ['Membangun reaktor nuklir buatan manusia pertama di dunia pada 1942', 'Meraih Hadiah Nobel Fisika 1938 atas riset radioaktivitas buatan', 'Berperan penting dalam Proyek Manhattan pengembangan bom atom'], kutipan: 'Ada dua kemungkinan: entah kita akan begitu bodoh atau begitu pintar, dan hasilnya sangat menentukan.', trivia: 'Unsur kimia fermium dinamai untuk menghormatinya.', relasi: [{ nama: 'J. Robert Oppenheimer', jenis: 'rekan ilmuwan dalam Proyek Manhattan' }] },
  { nama: 'J. Robert Oppenheimer', namaEn: 'J. Robert Oppenheimer', lahir: { tahun: 1904, negara: 'Amerika Serikat' }, wafat: 1967, bidang: 'Fisika', pencapaian: ['Memimpin Proyek Manhattan yang mengembangkan bom atom pertama', "Dijuluki 'Bapak Bom Atom' meski kemudian menyesali dampaknya", 'Berkontribusi besar pada perkembangan fisika teoretis dan kuantum'], kutipan: 'Sekarang aku menjadi Maut, sang penghancur dunia.', trivia: 'Izin keamanannya dicabut pemerintah AS di era Perang Dingin karena kecurigaan politik.', relasi: [{ nama: 'Enrico Fermi', jenis: 'rekan ilmuwan dalam Proyek Manhattan' }] },
  { nama: 'Barbara McClintock', namaEn: 'Barbara McClintock', lahir: { tahun: 1902, negara: 'Amerika Serikat' }, wafat: 1992, bidang: 'Genetika', pencapaian: ['Menemukan elemen genetik yang bisa berpindah posisi (transposon) dalam kromosom jagung', 'Meraih Hadiah Nobel Fisiologi atau Kedokteran 1983 seorang diri, tanpa pembagi', 'Menjadi wanita pertama yang meraih Nobel Kedokteran/Fisiologi tanpa berbagi dengan orang lain'], kutipan: 'Jika kau tahu kau berada di jalur yang benar, jika kau tahu itu, tidak ada yang bisa menghentikanmu.', trivia: "Temuannya soal 'gen loncat' sempat diabaikan komunitas ilmiah selama puluhan tahun sebelum diakui luas.", relasi: [{ nama: 'Thomas Hunt Morgan', jenis: 'genetikawan senior yang membimbing awal kariernya' }] },
  { nama: 'Franklin D. Roosevelt', namaEn: 'Franklin D. Roosevelt', lahir: { tahun: 1882, negara: 'Amerika Serikat' }, wafat: 1945, bidang: 'Politik', pencapaian: ['Menjadi satu-satunya presiden Amerika Serikat yang menjabat empat periode', 'Memimpin AS keluar dari Depresi Besar lewat kebijakan New Deal', 'Memimpin AS selama sebagian besar Perang Dunia II'], kutipan: 'Satu-satunya hal yang perlu kita takutkan adalah rasa takut itu sendiri.', trivia: 'Ia menjalani sebagian besar masa kepresidenannya dengan kelumpuhan akibat polio, yang jarang ditampilkan ke publik saat itu.', relasi: [{ nama: 'Winston Churchill', jenis: 'sekutu dekat selama Perang Dunia II' }] },
  { nama: 'Thomas Jefferson', namaEn: 'Thomas Jefferson', lahir: { tahun: 1743, negara: 'Amerika Serikat' }, wafat: 1826, bidang: 'Politik', pencapaian: ['Menjadi penulis utama Deklarasi Kemerdekaan Amerika Serikat 1776', 'Menjabat sebagai Presiden ketiga Amerika Serikat', 'Mendirikan University of Virginia dan aktif di berbagai bidang keilmuan'], kutipan: 'Aku menyukai mimpi masa depan lebih daripada sejarah masa lalu.', trivia: 'Ia wafat tepat pada 4 Juli, 50 tahun setelah Deklarasi Kemerdekaan ia tulis, di hari yang sama dengan John Adams.', relasi: [{ nama: 'John Adams', jenis: 'rekan sekaligus rival politik yang wafat di hari yang sama dengannya' }] },
  { nama: 'George Washington', namaEn: 'George Washington', lahir: { tahun: 1732, negara: 'Amerika Serikat' }, wafat: 1799, bidang: 'Politik/Militer', pencapaian: ['Memimpin pasukan Amerika meraih kemerdekaan dari Inggris sebagai panglima tertinggi', 'Menjadi Presiden pertama Amerika Serikat', 'Menolak menjabat lebih dari dua periode, menetapkan tradisi transisi kekuasaan damai'], kutipan: 'Kejujuran selalu jadi kebijakan terbaik.', trivia: 'Ia menolak tawaran untuk dijadikan raja setelah kemenangan Perang Kemerdekaan Amerika.', relasi: [{ nama: 'Alexander Hamilton', jenis: 'menteri keuangan pertama sekaligus penasihat dekat di kabinetnya' }] },
  { nama: 'John F. Kennedy', namaEn: 'John F. Kennedy', lahir: { tahun: 1917, negara: 'Amerika Serikat' }, wafat: 1963, bidang: 'Politik', pencapaian: ['Menjadi Presiden Amerika Serikat termuda yang terpilih lewat pemilu', 'Mencanangkan program antariksa yang membawa manusia mendarat di Bulan', 'Memimpin AS melalui masa krisis rudal Kuba tanpa memicu perang nuklir'], kutipan: 'Jangan tanya apa yang negara bisa berikan padamu, tanyakan apa yang bisa kau berikan pada negaramu.', trivia: 'Ia dibunuh dalam sebuah kunjungan ke Dallas pada 1963, salah satu peristiwa paling terkenal abad ke-20.', relasi: [{ nama: 'Lyndon B. Johnson', jenis: 'wakil presiden yang menggantikannya setelah pembunuhannya' }] },
  { nama: 'Vladimir Lenin', namaEn: 'Vladimir Lenin', lahir: { tahun: 1870, negara: 'Rusia' }, wafat: 1924, bidang: 'Politik', pencapaian: ['Memimpin Revolusi Bolshevik 1917 yang menggulingkan pemerintahan Rusia', 'Mendirikan negara komunis pertama di dunia, Uni Soviet', 'Merumuskan dasar ideologi Marxisme-Leninisme'], kutipan: 'Kadang sejarah butuh cambukan agar berjalan lebih cepat.', trivia: 'Jenazahnya dibalsem dan masih dipamerkan di mausoleum Lapangan Merah Moskow hingga kini.', relasi: [{ nama: 'Joseph Stalin', jenis: 'penerus kepemimpinan Uni Soviet setelahnya' }] },
  { nama: 'Mao Zedong', namaEn: 'Mao Zedong', lahir: { tahun: 1893, negara: 'China' }, wafat: 1976, bidang: 'Politik', pencapaian: ['Memimpin Partai Komunis China meraih kekuasaan pada 1949', 'Menjadi pemimpin tertinggi Republik Rakyat China selama beberapa dekade', 'Meluncurkan berbagai kebijakan besar termasuk Lompatan Jauh ke Depan dan Revolusi Kebudayaan'], kutipan: 'Kekuasaan politik lahir dari moncong senjata.', trivia: "Kutipan-kutipannya dihimpun dalam 'Buku Merah Kecil' yang dicetak dalam jumlah sangat besar.", relasi: [{ nama: 'Zhou Enlai', jenis: 'perdana menteri sekaligus rekan dekat di kepemimpinan Partai Komunis China' }] },
  { nama: 'Alexander Agung', namaEn: 'Alexander the Great', lahir: { tahun: -356, negara: 'Makedonia' }, wafat: -323, bidang: 'Militer/Kepemimpinan', pencapaian: ['Membangun salah satu kekaisaran terluas dalam sejarah dunia kuno sebelum usia 30 tahun', 'Tidak pernah kalah dalam pertempuran besar sepanjang kariernya sebagai panglima', 'Menyebarkan budaya Yunani hingga ke Mesir dan Asia lewat penaklukannya'], kutipan: 'Tidak ada yang mustahil bagi mereka yang mau mencoba.', trivia: 'Ia dididik langsung oleh filsuf Aristoteles sejak remaja.', relasi: [{ nama: 'Aristoteles', jenis: 'guru sekaligus filsuf yang mendidiknya sejak muda' }] },
  { nama: 'Suleiman yang Agung', namaEn: 'Suleiman the Magnificent', lahir: { tahun: 1494, negara: 'Kesultanan Utsmaniyah (Turki)' }, wafat: 1566, bidang: 'Politik', pencapaian: ['Memimpin Kesultanan Utsmaniyah pada masa puncak kejayaannya', 'Memperluas wilayah kekuasaan Utsmaniyah hingga ke Eropa Tengah', "Merombak sistem hukum kesultanan hingga dijuluki 'Sang Pemberi Hukum'"], kutipan: 'Aku, Sultan Suleiman, yang namanya dibacakan dalam doa di seluruh kota-kota suci Islam.', trivia: 'Masa pemerintahannya dianggap sebagai puncak keemasan seni, arsitektur, dan sastra Utsmaniyah.', relasi: [{ nama: 'Hurrem Sultan', jenis: 'istri yang berpengaruh besar dalam urusan politik istananya' }] },
  { nama: 'Kublai Khan', namaEn: 'Kublai Khan', lahir: { tahun: 1215, negara: 'Mongolia' }, wafat: 1294, bidang: 'Politik/Militer', pencapaian: ['Mendirikan Dinasti Yuan dan menjadi kaisar pertama China di bawah kekuasaan Mongol', 'Menyatukan seluruh daratan China di bawah satu pemerintahan', 'Membangun ibu kota Khanbaliq yang kini menjadi Beijing'], kutipan: 'Sebuah kerajaan dimenangkan di atas kuda, tapi tidak bisa diperintah di atas kuda.', trivia: 'Ia menjamu penjelajah Marco Polo di istananya selama bertahun-tahun.', relasi: [{ nama: 'Marco Polo', jenis: 'penjelajah Eropa yang tinggal di istananya selama bertahun-tahun' }] },
  { nama: 'Catherine yang Agung', namaEn: 'Catherine the Great', lahir: { tahun: 1729, negara: 'Rusia' }, wafat: 1796, bidang: 'Politik', pencapaian: ['Memimpin Rusia selama 34 tahun, salah satu masa pemerintahan terpanjang dalam sejarah Rusia', 'Memperluas wilayah Kekaisaran Rusia secara signifikan', 'Mendorong reformasi pendidikan dan modernisasi budaya di Rusia'], kutipan: 'Aku akan menjadi penguasa, atau mati mencobanya.', trivia: 'Ia lahir sebagai putri Jerman sebelum menikah ke keluarga kerajaan Rusia dan akhirnya naik takhta sendiri.', relasi: [{ nama: 'Peter yang Agung', jenis: 'pendahulu yang kebijakan modernisasinya ia lanjutkan' }] },
  { nama: 'Peter yang Agung', namaEn: 'Peter the Great', lahir: { tahun: 1672, negara: 'Rusia' }, wafat: 1725, bidang: 'Politik', pencapaian: ['Memodernisasi Rusia secara besar-besaran mengikuti model Eropa Barat', 'Mendirikan kota Saint Petersburg sebagai ibu kota baru Rusia', 'Membangun angkatan laut Rusia dari nol menjadi kekuatan besar'], kutipan: 'Aku memerlukan waktu 20 tahun untuk mengubah Rusia, tapi hanya butuh satu hari untuk mengubah namaku.', trivia: 'Ia pernah menyamar dan bekerja langsung sebagai tukang kayu di galangan kapal Eropa untuk mempelajari teknologi perkapalan.', relasi: [{ nama: 'Catherine yang Agung', jenis: 'penerus yang melanjutkan kebijakan modernisasi Rusia' }] },
  { nama: 'Ho Chi Minh', namaEn: 'Ho Chi Minh', lahir: { tahun: 1890, negara: 'Vietnam' }, wafat: 1969, bidang: 'Politik', pencapaian: ['Memimpin gerakan kemerdekaan Vietnam dari kekuasaan kolonial Prancis', 'Mendirikan Republik Demokratik Vietnam pada 1945', 'Menjadi simbol perjuangan revolusi dan persatuan Vietnam'], kutipan: 'Tidak ada yang lebih berharga daripada kemerdekaan dan kebebasan.', trivia: 'Ia menggunakan banyak nama samaran sepanjang hidupnya sebelum dikenal sebagai Ho Chi Minh.', relasi: [{ nama: 'Vo Nguyen Giap', jenis: 'jenderal sekaligus rekan seperjuangan dalam perang kemerdekaan Vietnam' }] },
  { nama: 'Johann Sebastian Bach', namaEn: 'Johann Sebastian Bach', lahir: { tahun: 1685, negara: 'Jerman' }, wafat: 1750, bidang: 'Musik Klasik', pencapaian: ['Menggubah ribuan karya musik termasuk konserto, kantata, dan karya organ', 'Dianggap salah satu komponis terbesar dalam sejarah musik Barat', 'Karya-karyanya seperti Brandenburg Concertos tetap dipentaskan luas hingga kini'], kutipan: 'Aku bekerja keras; siapa pun yang bekerja sekeras itu akan mencapai hal yang sama.', trivia: 'Sebagian besar karyanya baru mendapat pengakuan luas hampir seabad setelah ia wafat.', relasi: [{ nama: 'Carl Philipp Emanuel Bach', jenis: 'putra sekaligus komponis yang melanjutkan tradisi musik keluarganya' }] },
  { nama: 'Fyodor Dostoevsky', namaEn: 'Fyodor Dostoevsky', lahir: { tahun: 1821, negara: 'Rusia' }, wafat: 1881, bidang: 'Sastra', pencapaian: ["Menulis novel-novel klasik seperti 'Crime and Punishment' dan 'The Brothers Karamazov'", 'Karyanya mengeksplorasi psikologi manusia dan dilema moral secara mendalam', 'Menjadi salah satu penulis paling berpengaruh dalam sastra dunia'], kutipan: 'Untuk hidup bahagia, kita harus sering merenungkan kematian.', trivia: 'Ia sempat dijatuhi hukuman mati dan hanya diampuni di detik-detik terakhir sebelum eksekusi.', relasi: [{ nama: 'Leo Tolstoy', jenis: 'sesama penulis besar Rusia sezamannya' }] },
  { nama: 'Leo Tolstoy', namaEn: 'Leo Tolstoy', lahir: { tahun: 1828, negara: 'Rusia' }, wafat: 1910, bidang: 'Sastra', pencapaian: ["Menulis novel epik 'War and Peace' dan 'Anna Karenina'", 'Dianggap salah satu novelis terbesar sepanjang masa', 'Pemikirannya soal anti-kekerasan turut memengaruhi tokoh seperti Mahatma Gandhi'], kutipan: 'Semua orang berpikir mengubah dunia, tapi tak ada yang berpikir mengubah dirinya sendiri.', trivia: 'Ia meninggalkan rumah dan kekayaannya di usia tua untuk menjalani hidup sederhana sebelum wafat di stasiun kereta.', relasi: [{ nama: 'Mahatma Gandhi', jenis: 'tokoh yang pemikiran anti-kekerasannya terinspirasi tulisannya' }] },
  { nama: 'Jane Austen', namaEn: 'Jane Austen', lahir: { tahun: 1775, negara: 'Inggris' }, wafat: 1817, bidang: 'Sastra', pencapaian: ["Menulis novel klasik seperti 'Pride and Prejudice' dan 'Sense and Sensibility'", 'Karyanya dikenal lewat kritik sosial halus terhadap kelas dan pernikahan di masyarakat Inggris', 'Tetap menjadi salah satu penulis paling banyak dibaca dan diadaptasi hingga kini'], kutipan: 'Aku telah bersumpah untuk menjadi wanita yang sangat bijaksana, hebat menulis surat, dan sangat mencintai keluargaku.', trivia: 'Ia menerbitkan karya-karyanya secara anonim semasa hidup, tanpa nama aslinya tercantum.', relasi: [{ nama: 'Cassandra Austen', jenis: 'kakak sekaligus orang terdekat yang menyimpan banyak suratnya' }] },
  { nama: 'Ernest Hemingway', namaEn: 'Ernest Hemingway', lahir: { tahun: 1899, negara: 'Amerika Serikat' }, wafat: 1961, bidang: 'Sastra', pencapaian: ["Menulis novel terkenal seperti 'The Old Man and the Sea' dan 'A Farewell to Arms'", 'Meraih Hadiah Nobel Sastra 1954 atas gaya penulisannya yang ringkas dan kuat', "Dikenal atas gaya penulisan 'iceberg theory' yang minim kata namun sarat makna"], kutipan: 'Dunia mematahkan setiap orang, dan setelahnya banyak yang menjadi lebih kuat di titik yang patah.', trivia: 'Ia sempat menjadi jurnalis perang dan mengalami beberapa kali kecelakaan hampir fatal sepanjang hidupnya.', relasi: [{ nama: 'F. Scott Fitzgerald', jenis: 'sahabat sekaligus sesama penulis besar Amerika sezamannya' }] },
  { nama: 'Pablo Neruda', namaEn: 'Pablo Neruda', lahir: { tahun: 1904, negara: 'Chili' }, wafat: 1973, bidang: 'Sastra', pencapaian: ["Menulis puluhan kumpulan puisi termasuk 'Twenty Love Poems and a Song of Despair'", 'Meraih Hadiah Nobel Sastra 1971', 'Aktif sebagai diplomat dan politisi selain sebagai penyair'], kutipan: 'Kau bisa memotong semua bunga, tapi kau tak bisa menghentikan musim semi datang.', trivia: 'Nama penanya, Pablo Neruda, diambil dari penulis Ceko Jan Neruda, bukan nama aslinya.', relasi: [{ nama: 'Gabriel Garcia Marquez', jenis: 'sesama penulis besar Amerika Latin yang mengaguminya' }] },
  { nama: 'Gabriel Garcia Marquez', namaEn: 'Gabriel Garcia Marquez', lahir: { tahun: 1927, negara: 'Kolombia' }, wafat: 2014, bidang: 'Sastra', pencapaian: ["Menulis novel 'One Hundred Years of Solitude', karya penting gerakan realisme magis", 'Meraih Hadiah Nobel Sastra 1982', 'Menjadi salah satu penulis Amerika Latin paling berpengaruh di dunia'], kutipan: 'Kehidupan bukanlah yang dijalani seseorang, melainkan yang diingat dan bagaimana ia mengingatnya untuk diceritakan.', trivia: 'Ia awalnya bekerja sebagai jurnalis sebelum menulis novel-novel besarnya.', relasi: [{ nama: 'Pablo Neruda', jenis: 'sesama penulis besar Amerika Latin yang mengilhaminya' }] },
  { nama: 'Rabindranath Tagore', namaEn: 'Rabindranath Tagore', lahir: { tahun: 1861, negara: 'India' }, wafat: 1941, bidang: 'Sastra', pencapaian: ['Menjadi orang Asia pertama yang meraih Hadiah Nobel Sastra pada 1913', 'Menulis lagu kebangsaan India dan Bangladesh', 'Mendirikan lembaga pendidikan Visva-Bharati yang menekankan seni dan budaya'], kutipan: 'Kamu tak bisa menyeberangi lautan hanya dengan berdiri dan menatap air.', trivia: 'Ia menggubah lagu kebangsaan untuk dua negara berbeda, India dan Bangladesh.', relasi: [{ nama: 'Mahatma Gandhi', jenis: 'sahabat sekaligus tokoh pergerakan kemerdekaan India sezamannya' }] },
  { nama: 'Salvador Dali', namaEn: 'Salvador Dali', lahir: { tahun: 1904, negara: 'Spanyol' }, wafat: 1989, bidang: 'Seni', pencapaian: ['Menjadi tokoh utama gerakan seni Surealisme', "Melukis karya ikonik 'The Persistence of Memory' dengan jam-jam meleleh", 'Dikenal juga lewat gaya kumis khasnya dan perilaku eksentriknya di depan publik'], kutipan: 'Jangan takut akan kesempurnaan, kau tidak akan pernah mencapainya.', trivia: 'Ia juga aktif berkarya di bidang film, patung, dan desain, tidak hanya lukisan.', relasi: [{ nama: 'Federico Garcia Lorca', jenis: 'sahabat dekat sekaligus penyair Spanyol sezamannya' }] },
  { nama: 'Claude Monet', namaEn: 'Claude Monet', lahir: { tahun: 1840, negara: 'Prancis' }, wafat: 1926, bidang: 'Seni', pencapaian: ['Menjadi salah satu pendiri dan tokoh utama gerakan Impresionisme', "Melukis seri lukisan 'Water Lilies' yang ikonik di taman rumahnya sendiri", 'Karyanya menekankan permainan cahaya dan warna alami dibanding detail realistis'], kutipan: 'Aku mungkin berhutang jadi pelukis pada bunga-bunga.', trivia: "Nama gerakan Impresionisme sendiri diambil dari salah satu lukisannya, 'Impression, Sunrise'.", relasi: [{ nama: 'Pierre-Auguste Renoir', jenis: 'sahabat sekaligus sesama pendiri gerakan Impresionisme' }] },
  { nama: 'Henry Ford', namaEn: 'Henry Ford', lahir: { tahun: 1863, negara: 'Amerika Serikat' }, wafat: 1947, bidang: 'Bisnis/Teknologi', pencapaian: ['Mendirikan Ford Motor Company dan mempopulerkan mobil Model T', 'Menyempurnakan sistem lini produksi (assembly line) massal', 'Membuat mobil terjangkau bagi kalangan masyarakat luas untuk pertama kalinya'], kutipan: 'Apakah kau berpikir bisa atau tidak bisa, kau selalu benar.', trivia: 'Ia menggandakan upah pekerjanya menjadi 5 dolar sehari, jauh di atas standar industri saat itu.', relasi: [{ nama: 'Thomas Edison', jenis: 'mentor sekaligus sahabat dekat sepanjang hidupnya' }] },
  { nama: 'Jeff Bezos', namaEn: 'Jeff Bezos', lahir: { tahun: 1964, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Bisnis/Teknologi', pencapaian: ['Mendirikan Amazon yang berkembang dari toko buku daring menjadi raksasa e-commerce dunia', 'Mendirikan perusahaan antariksa swasta Blue Origin', 'Menjadi salah satu orang terkaya di dunia lewat kesuksesan Amazon'], kutipan: 'Jika kau tidak nyaman berinvestasi dalam eksperimen berani, jangan berharap hasil terobosan.', trivia: 'Ia memulai Amazon dari garasi rumahnya di Seattle pada 1994.', relasi: [{ nama: 'MacKenzie Scott', jenis: 'mantan istri yang turut membantu di masa-masa awal Amazon' }] },
  { nama: 'Warren Buffett', namaEn: 'Warren Buffett', lahir: { tahun: 1930, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Bisnis/Investasi', pencapaian: ['Memimpin Berkshire Hathaway menjadi salah satu perusahaan investasi paling sukses di dunia', 'Dikenal sebagai salah satu investor paling sukses sepanjang sejarah', 'Berjanji menyumbangkan sebagian besar kekayaannya untuk kegiatan filantropi'], kutipan: 'Aturan nomor satu investasi: jangan pernah rugi. Aturan nomor dua: jangan lupa aturan nomor satu.', trivia: 'Meski salah satu orang terkaya dunia, ia dikenal hidup sangat sederhana dan masih tinggal di rumah yang dibelinya puluhan tahun lalu.', relasi: [{ nama: 'Bill Gates', jenis: "sahabat dekat yang bersamanya mendirikan gerakan filantropi 'Giving Pledge'" }] },
  { nama: 'Desmond Tutu', namaEn: 'Desmond Tutu', lahir: { tahun: 1931, negara: 'Afrika Selatan' }, wafat: 2021, bidang: 'Aktivisme', pencapaian: ['Aktif memimpin perlawanan damai terhadap sistem apartheid di Afrika Selatan', 'Meraih Hadiah Nobel Perdamaian 1984 atas perjuangannya', 'Memimpin Komisi Kebenaran dan Rekonsiliasi Afrika Selatan pasca-apartheid'], kutipan: 'Jika kau netral dalam situasi ketidakadilan, kau memilih pihak si penindas.', trivia: "Ia dikenal luas dengan julukan akrab 'The Arch' oleh banyak orang di Afrika Selatan.", relasi: [{ nama: 'Nelson Mandela', jenis: 'rekan seperjuangan anti-apartheid' }] },
  { nama: 'Anne Frank', namaEn: 'Anne Frank', lahir: { tahun: 1929, negara: 'Jerman' }, wafat: 1945, bidang: 'Sastra/Sejarah', pencapaian: ['Menulis buku harian yang mendokumentasikan kehidupan bersembunyi dari Nazi selama Perang Dunia II', 'Buku hariannya diterbitkan setelah wafat dan diterjemahkan ke puluhan bahasa', 'Menjadi salah satu simbol paling dikenal dunia dari korban Holocaust'], kutipan: 'Meski begitu, aku masih percaya bahwa manusia pada dasarnya baik hati.', trivia: 'Ia wafat di kamp konsentrasi Bergen-Belsen hanya beberapa minggu sebelum kamp itu dibebaskan.', relasi: [{ nama: 'Otto Frank', jenis: 'ayah sekaligus satu-satunya anggota keluarga yang selamat, yang menerbitkan buku hariannya' }] },
  { nama: 'Susan B. Anthony', namaEn: 'Susan B. Anthony', lahir: { tahun: 1820, negara: 'Amerika Serikat' }, wafat: 1906, bidang: 'Aktivisme', pencapaian: ['Memimpin gerakan hak pilih perempuan di Amerika Serikat selama puluhan tahun', 'Mendirikan organisasi nasional untuk memperjuangkan hak suara perempuan', 'Perjuangannya membuka jalan bagi amandemen konstitusi AS yang memberi hak pilih perempuan'], kutipan: 'Kegagalan itu mustahil.', trivia: 'Ia sempat ditangkap dan diadili karena nekat memberikan suara dalam pemilu meski perempuan belum punya hak pilih saat itu.', relasi: [{ nama: 'Elizabeth Cady Stanton', jenis: 'sahabat sekaligus rekan seperjuangan gerakan hak pilih perempuan' }] },
  { nama: 'Muhammad Ali', namaEn: 'Muhammad Ali', lahir: { tahun: 1942, negara: 'Amerika Serikat' }, wafat: 2016, bidang: 'Olahraga (Tinju)', pencapaian: ['Menjadi juara dunia tinju kelas berat sebanyak tiga kali', "Dikenal lewat gaya bertarung cepat dan kepercayaan diri khasnya, 'melayang seperti kupu-kupu, menyengat seperti lebah'", 'Aktif sebagai aktivis hak sipil dan menolak wajib militer atas dasar keyakinan pribadinya'], kutipan: 'Yang mustahil hanyalah pendapat.', trivia: 'Ia sempat dicabut gelar juara dunianya selama beberapa tahun karena menolak wajib militer Perang Vietnam.', relasi: [{ nama: 'Joe Frazier', jenis: 'rival tinju dalam beberapa pertarungan paling terkenal sepanjang sejarah' }] },
  { nama: 'Pele', namaEn: 'Pele', lahir: { tahun: 1940, negara: 'Brasil' }, wafat: 2022, bidang: 'Olahraga (Sepak Bola)', pencapaian: ['Memenangkan Piala Dunia FIFA tiga kali bersama Timnas Brasil, satu-satunya pemain dengan capaian itu', 'Mencetak lebih dari 1000 gol sepanjang kariernya', 'Dianggap salah satu pesepak bola terhebat sepanjang sejarah'], kutipan: 'Kesuksesan bukan kebetulan; ia adalah kerja keras, ketekunan, belajar, dan pengorbanan.', trivia: 'Ia mulai bermain sepak bola jalanan tanpa alas kaki di masa kecilnya karena keluarganya sangat miskin.', relasi: [{ nama: 'Diego Maradona', jenis: 'rival sekaligus sesama legenda sepak bola dunia' }] },
  { nama: 'Usain Bolt', namaEn: 'Usain Bolt', lahir: { tahun: 1986, negara: 'Jamaika' }, wafat: null, bidang: 'Olahraga (Atletik)', pencapaian: ['Memegang rekor dunia lari 100 meter dan 200 meter', 'Meraih delapan medali emas Olimpiade sepanjang kariernya', 'Dijuluki manusia tercepat di dunia'], kutipan: 'Aku tidak berpikir batasan sebelum aku mencapainya.', trivia: "Nama julukannya, 'Lightning Bolt', diambil dari selebrasi khasnya menirukan petir setiap kali menang.", relasi: [{ nama: 'Michael Johnson', jenis: 'pemegang rekor dunia sebelumnya yang catatannya ia pecahkan' }] },
  { nama: 'Lionel Messi', namaEn: 'Lionel Messi', lahir: { tahun: 1987, negara: 'Argentina' }, wafat: null, bidang: 'Olahraga (Sepak Bola)', pencapaian: ["Memenangkan Ballon d'Or sebagai pesepak bola terbaik dunia lebih banyak dari pemain mana pun", 'Membawa Timnas Argentina juara Piala Dunia FIFA 2022', 'Menghabiskan sebagian besar kariernya di klub FC Barcelona sebelum pindah ke luar negeri'], kutipan: 'Kau harus berjuang untuk mencapai mimpimu; pengorbanan memberimu kesempatan untuk menikmati apa yang telah kau raih.', trivia: 'Ia sempat mengalami gangguan hormon pertumbuhan di masa kecil yang perawatannya dibiayai klub Barcelona.', relasi: [{ nama: 'Cristiano Ronaldo', jenis: 'rival abadi dalam persaingan pesepak bola terbaik dunia' }] },
  { nama: 'Ki Hajar Dewantara', namaEn: 'Ki Hajar Dewantara', lahir: { tahun: 1889, negara: 'Indonesia' }, wafat: 1959, bidang: 'Pendidikan', pencapaian: ['Mendirikan Taman Siswa, lembaga pendidikan yang membuka akses belajar bagi pribumi', 'Menjadi Menteri Pendidikan pertama Indonesia setelah kemerdekaan', "Merumuskan filosofi pendidikan 'Ing ngarso sung tulodo, ing madya mangun karso, tut wuri handayani'"], kutipan: 'Setiap orang bisa jadi guru, dan setiap rumah adalah sekolah.', trivia: 'Hari lahirnya, 2 Mei, diperingati sebagai Hari Pendidikan Nasional Indonesia.', relasi: [{ nama: 'Douwes Dekker', jenis: 'sesama tokoh pergerakan nasional yang bersamanya membentuk Tiga Serangkai' }] },

];

function norm(s) {
  return String(s || '').toLowerCase().trim();
}

function findTokoh(query) {
  const q = norm(query);
  if (!q) return null;
  let found = TOKOH.find((t) => norm(t.nama) === q || norm(t.namaEn) === q);
  if (found) return found;
  found = TOKOH.find((t) => q.includes(norm(t.nama)) || norm(t.nama).includes(q) || q.includes(norm(t.namaEn)));
  return found || null;
}

function fmtTahun(t) {
  if (t == null) return 'sekarang (masih hidup)';
  return t < 0 ? Math.abs(t) + ' SM' : String(t);
}

function composeTokoh(t) {
  const wafatStr = t.wafat == null ? 'Masih hidup hingga sekarang.' : 'Wafat tahun ' + fmtTahun(t.wafat) + '.';
  return (
    `${t.nama} (${t.bidang}) — lahir tahun ${fmtTahun(t.lahir.tahun)} di ${t.lahir.negara}. ${wafatStr}\n\n` +
    'Pencapaian utama:\n' + t.pencapaian.map((p) => '• ' + p).join('\n') + '\n\n' +
    'Kutipan: "' + t.kutipan + '"\n\n' +
    'Trivia: ' + t.trivia
  );
}

function tryProfil(text) {
  const m = text.match(/^(siapa\s+itu|siapa|ceritakan\s+tentang|biografi(\s+dari)?)\s+(.+?)\??$/i);
  if (!m) return null;
  const t = findTokoh(m[3]);
  if (!t) return null;
  return composeTokoh(t);
}

function tryPencapaian(text) {
  const m = text.match(/^apa\s+(saja\s+)?pencapaian\s+(.+?)\??$|^prestasi\s+(.+?)\s+apa\s+saja\??$/i);
  if (!m) return null;
  const name = m[2] || m[3];
  const t = findTokoh(name);
  if (!t) return null;
  return t.nama + ' — pencapaian utama:\n' + t.pencapaian.map((p) => '• ' + p).join('\n');
}

function tryKutipan(text) {
  const m = text.match(/^kutipan\s+(terkenal\s+)?(dari\s+)?(.+?)\??$|^quote\s+dari\s+(.+?)\??$/i);
  if (!m) return null;
  const name = m[3] || m[4];
  const t = findTokoh(name);
  if (!t) return null;
  return t.nama + ' pernah berkata: "' + t.kutipan + '"';
}

function tryTrivia(text) {
  const m = text.match(/^(fakta\s+unik|trivia)\s+(tentang\s+|dari\s+)?(.+?)\??$/i);
  if (!m) return null;
  const t = findTokoh(m[3]);
  if (!t) return null;
  return 'Fakta unik tentang ' + t.nama + ': ' + t.trivia;
}

function tryRelasi(text) {
  const m = text.match(/^siapa\s+yang\s+berhubungan\s+dengan\s+(.+?)\??$|^hubungan\s+(.+?)\s+dengan\s+siapa\??$/i);
  if (!m) return null;
  const name = m[1] || m[2];
  const t = findTokoh(name);
  if (!t || !t.relasi.length) return null;
  return t.nama + ' berhubungan dengan: ' + t.relasi.map((r) => r.nama + ' (' + r.jenis + ')').join(', ') + '.';
}

function tryTokoh(text) {
  const t = String(text || '').trim();
  if (!t) return null;
  return tryPencapaian(t) || tryKutipan(t) || tryTrivia(t) || tryRelasi(t) || tryProfil(t) || null;
}

export const tokohStore = Object.freeze({
  TOKOH,
  findTokoh,
  composeTokoh,
  tryProfil,
  tryPencapaian,
  tryKutipan,
  tryTrivia,
  tryRelasi,
  tryTokoh,
});
