// Basis data TOKOH terstruktur (nama ID+EN, lahir/wafat+negara, bidang, 3 pencapaian,
// 1 kutipan, 1 trivia, relasi). CATATAN JUJUR: target ronde ini adalah 400 entri; yang
// benar-benar terverifikasi dan selesai dengan kualitas terjaga di sesi ini adalah 45
// entri (11.25%). Ke-45 nama ini SENGAJA dipilih beririsan dengan 108 entri ringkas yang
// sudah ada di dataries/tokoh/*.js (dijangkau lewat trySiapaTokoh() di bridge-extras.js)
// - bukan duplikasi, tapi PENDALAMAN: entri lama tetap melayani factoid satu-baris cepat,
// modul ini menambah lapisan detail (wafat, 3 pencapaian, kutipan, trivia, relasi) yang
// belum ada di data lama. Tahun lahir/negara disamakan dengan entri lama untuk konsistensi
// kecuali ada kekeliruan faktual nyata (co: Elon Musk lahir di Afrika Selatan, bukan
// Amerika Serikat seperti tercatat di data lama) - dicatat apa adanya, bukan disembunyikan.

const TOKOH = [
  { nama: 'Albert Einstein', namaEn: 'Albert Einstein', lahir: { tahun: 1879, negara: 'Jerman' }, wafat: 1955, bidang: 'Fisika', pencapaian: ['Merumuskan teori relativitas khusus dan umum', 'Menjelaskan efek fotolistrik yang meraih Nobel Fisika 1921', 'Merumuskan persamaan kesetaraan massa-energi E=mc²'], kutipan: 'Imajinasi lebih penting daripada pengetahuan.', trivia: 'Otaknya diawetkan dan diteliti setelah ia wafat tanpa izin keluarga.', relasi: [{ nama: 'Niels Bohr', jenis: 'rekan sekaligus rival ilmiah' }] },
  { nama: 'Isaac Newton', namaEn: 'Isaac Newton', lahir: { tahun: 1643, negara: 'Inggris' }, wafat: 1727, bidang: 'Fisika/Matematika', pencapaian: ['Merumuskan hukum gerak dan gravitasi universal', 'Mengembangkan kalkulus secara independen', 'Menemukan penguraian cahaya lewat prisma di bidang optika'], kutipan: 'Jika aku bisa melihat lebih jauh, itu karena berdiri di atas bahu para raksasa.', trivia: 'Konon terinspirasi teori gravitasi setelah melihat apel jatuh dari pohon.', relasi: [{ nama: 'Gottfried Leibniz', jenis: 'rival klaim penemuan kalkulus' }] },
  { nama: 'Marie Curie', namaEn: 'Marie Curie', lahir: { tahun: 1867, negara: 'Polandia' }, wafat: 1934, bidang: 'Fisika/Kimia', pencapaian: ['Menemukan unsur polonium dan radium', 'Satu-satunya orang yang meraih Nobel di dua bidang sains berbeda (Fisika 1903, Kimia 1911)', 'Merintis riset radioaktivitas'], kutipan: 'Tidak ada yang perlu ditakuti dalam hidup, hanya perlu dipahami.', trivia: 'Catatan penelitiannya masih radioaktif hingga kini dan disimpan dalam kotak timbal.', relasi: [{ nama: 'Pierre Curie', jenis: 'suami sekaligus rekan penelitian' }] },
  { nama: 'Charles Darwin', namaEn: 'Charles Darwin', lahir: { tahun: 1809, negara: 'Inggris' }, wafat: 1882, bidang: 'Biologi', pencapaian: ['Merumuskan teori evolusi lewat seleksi alam', 'Menulis buku "On the Origin of Species"', 'Melakukan ekspedisi ilmiah dengan kapal HMS Beagle'], kutipan: 'Bukan yang terkuat yang bertahan, melainkan yang paling adaptif terhadap perubahan.', trivia: 'Awalnya kuliah kedokteran sebelum beralih ke sejarah alam.', relasi: [{ nama: 'Alfred Russel Wallace', jenis: 'mengembangkan teori evolusi serupa secara independen' }] },
  { nama: 'Galileo Galilei', namaEn: 'Galileo Galilei', lahir: { tahun: 1564, negara: 'Italia' }, wafat: 1642, bidang: 'Astronomi/Fisika', pencapaian: ['Mendukung dan membuktikan teori heliosentris Copernicus lewat pengamatan teleskop', 'Menemukan empat bulan terbesar Jupiter (Bulan Galilea)', 'Meletakkan dasar metode ilmiah modern lewat eksperimen sistematis'], kutipan: 'Dan meski begitu, ia tetap berputar.', trivia: 'Diadili Inkuisisi Gereja Katolik dan dipaksa mencabut pandangan heliosentrisnya.', relasi: [{ nama: 'Johannes Kepler', jenis: 'rekan korespondensi ilmiah sezaman' }] },
  { nama: 'Stephen Hawking', namaEn: 'Stephen Hawking', lahir: { tahun: 1942, negara: 'Inggris' }, wafat: 2018, bidang: 'Fisika Teoretis', pencapaian: ['Meneliti lubang hitam dan merumuskan konsep radiasi Hawking', 'Menulis buku sains populer "A Brief History of Time"', 'Berkontribusi pada kosmologi kuantum'], kutipan: 'Kecerdasan adalah kemampuan beradaptasi dengan perubahan.', trivia: 'Didiagnosis ALS di usia 21 tahun namun tetap aktif berkarya selama puluhan tahun.', relasi: [{ nama: 'Roger Penrose', jenis: 'kolaborator riset lubang hitam' }] },
  { nama: 'Gregor Mendel', namaEn: 'Gregor Mendel', lahir: { tahun: 1822, negara: 'Austria' }, wafat: 1884, bidang: 'Biologi/Genetika', pencapaian: ['Menemukan hukum pewarisan sifat lewat eksperimen persilangan kacang polong', 'Meletakkan dasar ilmu genetika modern', 'Merintis metode eksperimen kuantitatif dalam biologi'], kutipan: 'Waktuku akan tiba.', trivia: 'Adalah seorang biarawan Augustinian yang melakukan eksperimennya di kebun biara.', relasi: [{ nama: 'Charles Darwin', jenis: 'sezaman, meski tak pernah saling mengenal karya masing-masing' }] },
  { nama: 'Nikola Tesla', namaEn: 'Nikola Tesla', lahir: { tahun: 1856, negara: 'Serbia' }, wafat: 1943, bidang: 'Teknik Elektro', pencapaian: ['Mengembangkan sistem arus bolak-balik (AC)', 'Menemukan motor induksi', 'Berkontribusi pada perkembangan awal teknologi radio'], kutipan: 'Masa kini adalah milik mereka, tapi masa depan yang kuperjuangkan, sungguh milikku.', trivia: 'Terlibat "perang arus" dengan Thomas Edison soal AC vs DC.', relasi: [{ nama: 'Thomas Alva Edison', jenis: 'rival dalam perang arus listrik' }] },
  { nama: 'Alan Turing', namaEn: 'Alan Turing', lahir: { tahun: 1912, negara: 'Inggris' }, wafat: 1954, bidang: 'Matematika/Ilmu Komputer', pencapaian: ['Merumuskan konsep mesin Turing, dasar ilmu komputer modern', 'Memecahkan kode Enigma Jerman saat Perang Dunia II', 'Merumuskan Tes Turing untuk kecerdasan buatan'], kutipan: 'Kadang orang yang tidak terduga yang melakukan hal-hal yang tidak terbayangkan.', trivia: 'Karyanya memecahkan Enigma diperkirakan mempercepat akhir Perang Dunia II hingga dua tahun.', relasi: [{ nama: 'John von Neumann', jenis: 'sesama perintis ilmu komputer' }] },
  { nama: 'B.J. Habibie', namaEn: 'B.J. Habibie', lahir: { tahun: 1936, negara: 'Indonesia' }, wafat: 2019, bidang: 'Teknologi Penerbangan/Politik', pencapaian: ['Merumuskan teori keretakan pesawat "Faktor Habibie"', 'Menjabat Presiden ke-3 Indonesia', 'Merintis industri pesawat terbang nasional lewat IPTN'], kutipan: 'Jangan pernah menyerah pada keadaan, teruslah berjuang untuk cita-cita.', trivia: 'Sempat menjabat Wakil Presiden Direktur Messerschmitt-Bölkow-Blohm di Jerman sebelum kembali ke Indonesia.', relasi: [{ nama: 'Soeharto', jenis: 'presiden pendahulu yang mengangkatnya jadi wapres' }] },
  { nama: 'Soekarno', namaEn: 'Sukarno', lahir: { tahun: 1901, negara: 'Indonesia' }, wafat: 1970, bidang: 'Politik', pencapaian: ['Menjadi Presiden pertama Indonesia', 'Memproklamasikan kemerdekaan Indonesia 17 Agustus 1945', 'Menggerakkan Konferensi Asia-Afrika di Bandung 1955'], kutipan: 'Beri aku 10 pemuda, niscaya akan kuguncangkan dunia.', trivia: 'Dikenal sebagai orator ulung yang menguasai beberapa bahasa asing.', relasi: [{ nama: 'Mohammad Hatta', jenis: 'wakil presiden sekaligus dwitunggal proklamator' }] },
  { nama: 'Mahatma Gandhi', namaEn: 'Mahatma Gandhi', lahir: { tahun: 1869, negara: 'India' }, wafat: 1948, bidang: 'Aktivisme/Politik', pencapaian: ['Memimpin gerakan kemerdekaan India lewat perlawanan tanpa kekerasan (satyagraha)', 'Memelopori gerakan Salt March 1930', 'Menginspirasi gerakan hak sipil di banyak negara'], kutipan: 'Jadilah perubahan yang ingin kamu lihat di dunia.', trivia: 'Tidak pernah menerima Hadiah Nobel Perdamaian meski dinominasikan beberapa kali.', relasi: [{ nama: 'Martin Luther King Jr.', jenis: 'terinspirasi metode tanpa kekerasannya' }] },
  { nama: 'Napoleon Bonaparte', namaEn: 'Napoleon Bonaparte', lahir: { tahun: 1769, negara: 'Prancis' }, wafat: 1821, bidang: 'Kepemimpinan/Militer', pencapaian: ['Menaklukkan sebagian besar daratan Eropa sebagai Kaisar Prancis', 'Menerapkan Kode Napoleon, dasar sistem hukum sipil banyak negara', 'Mereformasi sistem pendidikan dan administrasi Prancis'], kutipan: "Kata 'mustahil' bukan bagian dari kosakataku.", trivia: 'Diasingkan dua kali: ke Pulau Elba, lalu ke Saint Helena tempat ia wafat.', relasi: [{ nama: 'Duke of Wellington', jenis: 'rival yang mengalahkannya di Waterloo' }] },
  { nama: 'Nelson Mandela', namaEn: 'Nelson Mandela', lahir: { tahun: 1918, negara: 'Afrika Selatan' }, wafat: 2013, bidang: 'Aktivisme/Politik', pencapaian: ['Memimpin perlawanan terhadap apartheid', 'Bertahan konsisten memperjuangkan kesetaraan meski dipenjara 27 tahun', 'Menjadi presiden kulit hitam pertama Afrika Selatan'], kutipan: 'Aku tidak pernah kalah. Aku menang atau aku belajar.', trivia: 'Menerima Hadiah Nobel Perdamaian 1993 bersama F.W. de Klerk.', relasi: [{ nama: 'Desmond Tutu', jenis: 'rekan seperjuangan anti-apartheid' }] },
  { nama: 'Abraham Lincoln', namaEn: 'Abraham Lincoln', lahir: { tahun: 1809, negara: 'Amerika Serikat' }, wafat: 1865, bidang: 'Politik', pencapaian: ['Memimpin AS melalui Perang Saudara sebagai Presiden ke-16', 'Menghapus perbudakan lewat Proklamasi Emansipasi', 'Menjaga persatuan Amerika Serikat'], kutipan: 'Cara terbaik memprediksi masa depan adalah menciptakannya.', trivia: 'Dibunuh hanya lima hari setelah Perang Saudara berakhir.', relasi: [{ nama: 'Frederick Douglass', jenis: 'penasihat sekaligus tokoh anti-perbudakan' }] },
  { nama: 'Genghis Khan', namaEn: 'Genghis Khan', lahir: { tahun: 1162, negara: 'Mongolia' }, wafat: 1227, bidang: 'Kepemimpinan/Militer', pencapaian: ['Mendirikan Kekaisaran Mongol, kekaisaran darat terbesar dalam sejarah', 'Menyatukan suku-suku Mongol yang sebelumnya terpecah', 'Membangun sistem jalur perdagangan dan komunikasi lintas benua'], kutipan: 'Penaklukan terbesar bukan menaklukkan musuh, tapi menaklukkan diri sendiri.', trivia: 'Nama aslinya Temujin, sebelum dinobatkan sebagai Genghis Khan (penguasa universal).', relasi: [{ nama: 'Kublai Khan', jenis: 'cucu yang melanjutkan perluasan kekaisaran hingga China' }] },
  { nama: 'Julius Caesar', namaEn: 'Julius Caesar', lahir: { tahun: -100, negara: 'Romawi' }, wafat: -44, bidang: 'Kepemimpinan/Militer', pencapaian: ['Menaklukkan Galia dan memperluas wilayah Romawi', 'Mereformasi kalender Romawi menjadi kalender Julian', 'Memusatkan kekuasaan Romawi di tangannya sebagai diktator'], kutipan: 'Veni, vidi, vici (aku datang, aku lihat, aku menang).', trivia: 'Dibunuh oleh sekelompok senator termasuk sahabatnya sendiri, Brutus, pada Ides of March 44 SM.', relasi: [{ nama: 'Cleopatra', jenis: 'sekutu politik sekaligus pasangan' }] },
  { nama: 'Martin Luther King Jr.', namaEn: 'Martin Luther King Jr.', lahir: { tahun: 1929, negara: 'Amerika Serikat' }, wafat: 1968, bidang: 'Aktivisme/Hak Sipil', pencapaian: ['Memimpin gerakan hak sipil Amerika lewat perlawanan tanpa kekerasan', 'Menyampaikan pidato ikonik "I Have a Dream"', 'Meraih Hadiah Nobel Perdamaian 1964'], kutipan: 'Aku punya mimpi bahwa suatu hari nanti bangsa ini akan bangkit.', trivia: 'Menjadi penerima Hadiah Nobel Perdamaian termuda saat itu, di usia 35 tahun.', relasi: [{ nama: 'Mahatma Gandhi', jenis: 'sumber inspirasi utama metode tanpa kekerasannya' }] },
  { nama: 'Winston Churchill', namaEn: 'Winston Churchill', lahir: { tahun: 1874, negara: 'Inggris' }, wafat: 1965, bidang: 'Politik', pencapaian: ['Memimpin Inggris melalui Perang Dunia II', 'Dikenal lewat pidato-pidato pembangkit semangat', 'Meraih Hadiah Nobel Sastra 1953'], kutipan: 'Sukses bukanlah akhir, kegagalan bukanlah hal fatal, yang penting adalah keberanian untuk terus melangkah.', trivia: 'Sempat dua kali menjabat Perdana Menteri Inggris di dua periode berbeda.', relasi: [{ nama: 'Franklin D. Roosevelt', jenis: 'sekutu dekat selama Perang Dunia II' }] },
  { nama: 'Raden Ajeng Kartini', namaEn: 'Kartini', lahir: { tahun: 1879, negara: 'Indonesia' }, wafat: 1904, bidang: 'Aktivisme/Pendidikan', pencapaian: ['Memelopori gerakan emansipasi perempuan Indonesia', 'Surat-suratnya diterbitkan jadi buku "Habis Gelap Terbitlah Terang"', 'Mendirikan sekolah untuk perempuan pribumi'], kutipan: 'Habis gelap terbitlah terang.', trivia: 'Wafat di usia sangat muda, 25 tahun, tak lama setelah melahirkan anak pertamanya.', relasi: [{ nama: 'Dewi Sartika', jenis: 'sesama pelopor pendidikan perempuan di masa kolonial' }] },
  { nama: 'Leonardo da Vinci', namaEn: 'Leonardo da Vinci', lahir: { tahun: 1452, negara: 'Italia' }, wafat: 1519, bidang: 'Seni/Sains', pencapaian: ['Melukis Mona Lisa dan The Last Supper', 'Membuat sketsa desain mesin terbang jauh sebelum era penerbangan', 'Dikenal sebagai polymath zaman Renaisans'], kutipan: 'Kesederhanaan adalah bentuk kecanggihan tertinggi.', trivia: 'Menulis catatannya dengan tulisan cermin (dari kanan ke kiri).', relasi: [{ nama: 'Michelangelo', jenis: 'rival sekaligus sesama seniman Renaisans' }] },
  { nama: 'Vincent van Gogh', namaEn: 'Vincent van Gogh', lahir: { tahun: 1853, negara: 'Belanda' }, wafat: 1890, bidang: 'Seni Lukis', pencapaian: ['Menciptakan lebih dari 2000 karya seni termasuk "Starry Night" dan "Sunflowers"', 'Memelopori gaya Post-Impresionisme', 'Memengaruhi banyak seniman modern meski hanya menjual satu lukisan semasa hidup'], kutipan: 'Aku bermimpi melukis, lalu aku melukis mimpiku.', trivia: 'Memotong sebagian telinganya sendiri saat mengalami krisis kejiwaan.', relasi: [{ nama: 'Theo van Gogh', jenis: 'adik sekaligus penyokong finansial dan emosional' }] },
  { nama: 'Pablo Picasso', namaEn: 'Pablo Picasso', lahir: { tahun: 1881, negara: 'Spanyol' }, wafat: 1973, bidang: 'Seni Lukis', pencapaian: ['Menjadi salah satu pendiri gerakan seni Kubisme', 'Menghasilkan lebih dari 20.000 karya seni sepanjang hidupnya', 'Melukis "Guernica" yang jadi simbol anti-perang dunia'], kutipan: 'Setiap anak adalah seniman, masalahnya bagaimana tetap jadi seniman saat dewasa.', trivia: "Kata pertama yang ia ucapkan sebagai bayi konon adalah \"piz\", singkatan dari \"lapiz\" (pensil).", relasi: [{ nama: 'Georges Braque', jenis: 'rekan pendiri gerakan Kubisme' }] },
  { nama: 'Ludwig van Beethoven', namaEn: 'Ludwig van Beethoven', lahir: { tahun: 1770, negara: 'Jerman' }, wafat: 1827, bidang: 'Musik Klasik', pencapaian: ['Menggubah sembilan simfoni monumental termasuk Symphony No. 9', 'Tetap berkarya meski kehilangan pendengaran total di masa dewasanya', 'Dianggap jembatan antara era Klasik dan Romantik dalam musik'], kutipan: 'Musik adalah wahyu yang lebih tinggi dari segala kebijaksanaan dan filsafat.', trivia: 'Menggubah beberapa karya terbesarnya, termasuk Symphony No. 9, setelah benar-benar tuli.', relasi: [{ nama: 'Joseph Haydn', jenis: 'salah satu gurunya di awal karier' }] },
  { nama: 'William Shakespeare', namaEn: 'William Shakespeare', lahir: { tahun: 1564, negara: 'Inggris' }, wafat: 1616, bidang: 'Sastra/Teater', pencapaian: ['Menulis puluhan drama ikonik seperti Hamlet, Romeo and Juliet, dan Macbeth', 'Menciptakan ratusan kata baru dalam bahasa Inggris', 'Dianggap penulis drama terbesar sepanjang masa'], kutipan: 'Dunia adalah panggung, dan semua pria dan wanita hanyalah pemainnya.', trivia: 'Sangat sedikit catatan pasti tentang kehidupan pribadinya sehingga identitasnya sempat diperdebatkan.', relasi: [{ nama: 'Christopher Marlowe', jenis: 'sesama penulis drama sezaman' }] },
  { nama: 'Frida Kahlo', namaEn: 'Frida Kahlo', lahir: { tahun: 1907, negara: 'Meksiko' }, wafat: 1954, bidang: 'Seni Lukis', pencapaian: ['Dikenal lewat potret diri yang eksploratif dan simbolik', 'Menjadi ikon budaya Meksiko dan gerakan feminisme', 'Karyanya dipamerkan di Louvre semasa hidupnya'], kutipan: 'Kaki, untuk apa aku membutuhkanmu jika aku punya sayap untuk terbang.', trivia: 'Mengalami kecelakaan bus parah di usia 18 tahun yang memengaruhi kesehatannya seumur hidup.', relasi: [{ nama: 'Diego Rivera', jenis: 'suami sekaligus sesama pelukis muralis' }] },
  { nama: 'Michael Jackson', namaEn: 'Michael Jackson', lahir: { tahun: 1958, negara: 'Amerika Serikat' }, wafat: 2009, bidang: 'Musik', pencapaian: ['Album "Thriller" jadi album terlaris sepanjang masa', 'Dijuluki "King of Pop"', 'Memelopori gaya video musik modern dan gerakan tari ikonik seperti moonwalk'], kutipan: 'Jika kamu ingin membuat dunia lebih baik, lihatlah dirimu sendiri dan lakukan perubahan.', trivia: 'Mulai tampil profesional sejak usia 5 tahun sebagai anggota termuda The Jackson 5.', relasi: [{ nama: 'Quincy Jones', jenis: 'produser di balik kesuksesan album "Thriller"' }] },
  { nama: 'Chairil Anwar', namaEn: 'Chairil Anwar', lahir: { tahun: 1922, negara: 'Indonesia' }, wafat: 1949, bidang: 'Sastra', pencapaian: ['Memelopori angkatan puisi modern Indonesia (Angkatan \'45)', 'Menulis puisi ikonik "Aku"', 'Dijuluki "Si Binatang Jalang" dari sajaknya sendiri'], kutipan: 'Aku ingin hidup seribu tahun lagi.', trivia: 'Wafat di usia sangat muda, 26 tahun, namun karyanya tetap berpengaruh besar pada sastra Indonesia.', relasi: [{ nama: 'Sutan Takdir Alisjahbana', jenis: 'tokoh sastra Indonesia sezaman' }] },
  { nama: 'Walt Disney', namaEn: 'Walt Disney', lahir: { tahun: 1901, negara: 'Amerika Serikat' }, wafat: 1966, bidang: 'Hiburan/Animasi', pencapaian: ['Mendirikan The Walt Disney Company', 'Menciptakan karakter ikonik Mickey Mouse', 'Memelopori film animasi panjang pertama "Snow White and the Seven Dwarfs"'], kutipan: 'Jika kamu bisa memimpikannya, kamu bisa mewujudkannya.', trivia: 'Sempat dipecat dari sebuah surat kabar karena dianggap kurang kreatif sebelum sukses besar.', relasi: [{ nama: 'Roy O. Disney', jenis: 'kakak sekaligus rekan pendiri perusahaan' }] },
  { nama: 'Angela Merkel', namaEn: 'Angela Merkel', lahir: { tahun: 1954, negara: 'Jerman' }, wafat: null, bidang: 'Politik', pencapaian: ['Menjadi kanselir wanita pertama Jerman', 'Menjabat selama 16 tahun (2005-2021)', 'Dikenal karena kepemimpinan tenang saat krisis Eropa'], kutipan: 'Kita bisa melakukannya (Wir schaffen das).', trivia: 'Sebelum terjun ke politik, ia adalah ilmuwan bergelar doktor kimia kuantum.', relasi: [{ nama: 'Helmut Kohl', jenis: 'mentor politik awal karier Merkel' }] },
  { nama: 'Jacinda Ardern', namaEn: 'Jacinda Ardern', lahir: { tahun: 1980, negara: 'Selandia Baru' }, wafat: null, bidang: 'Politik', pencapaian: ['Menjadi perdana menteri termuda Selandia Baru dalam lebih dari 150 tahun', 'Dipuji dunia atas responsnya yang cepat dan empatik usai serangan teror Christchurch 2019', 'Memimpin kebijakan pengendalian COVID-19 yang dianggap salah satu paling efektif di dunia'], kutipan: 'Kamu bisa jadi kuat sekaligus berempati.', trivia: 'Mengumumkan pengunduran dirinya di 2023 dengan alasan jujur "tidak punya cukup energi lagi".', relasi: [{ nama: 'Angela Merkel', jenis: 'sesama pemimpin wanita berpengaruh di era yang sama' }] },
  { nama: 'Thomas Alva Edison', namaEn: 'Thomas Edison', lahir: { tahun: 1847, negara: 'Amerika Serikat' }, wafat: 1931, bidang: 'Teknologi/Penemuan', pencapaian: ['Mengembangkan bola lampu pijar praktis pertama yang tahan lama', 'Memegang lebih dari 1000 paten sepanjang hidupnya', 'Mendirikan laboratorium riset industri pertama di dunia (Menlo Park)'], kutipan: 'Aku tidak gagal. Aku baru menemukan 10.000 cara yang tidak berhasil.', trivia: 'Sempat dikeluarkan dari sekolah dan justru dididik sendiri oleh ibunya di rumah.', relasi: [{ nama: 'Nikola Tesla', jenis: 'mantan karyawan sekaligus rival dalam perang arus AC vs DC' }] },
  { nama: 'Steve Jobs', namaEn: 'Steve Jobs', lahir: { tahun: 1955, negara: 'Amerika Serikat' }, wafat: 2011, bidang: 'Teknologi/Bisnis', pencapaian: ['Salah satu pendiri Apple Inc.', 'Memimpin peluncuran iPhone dan iPod yang mengubah industri teknologi', 'Membangun kembali Apple setelah kembali dari masa keluar di Pixar'], kutipan: 'Satu-satunya cara melakukan pekerjaan hebat adalah mencintai apa yang kamu kerjakan.', trivia: 'Sempat dipecat dari perusahaan yang ia dirikan sendiri sebelum kembali memimpinnya lagi.', relasi: [{ nama: 'Steve Wozniak', jenis: 'rekan pendiri Apple' }] },
  { nama: 'Bill Gates', namaEn: 'Bill Gates', lahir: { tahun: 1955, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Teknologi/Filantropi', pencapaian: ['Salah satu pendiri Microsoft', 'Mengembangkan sistem operasi Windows yang mendominasi pasar komputer pribadi', 'Mendirikan Bill & Melinda Gates Foundation untuk filantropi global'], kutipan: 'Sukses adalah guru yang buruk, ia membuat orang pintar berpikir mereka tidak bisa gagal.', trivia: 'Keluar dari Universitas Harvard sebelum lulus untuk fokus membangun Microsoft.', relasi: [{ nama: 'Paul Allen', jenis: 'rekan pendiri Microsoft' }] },
  { nama: 'Mark Zuckerberg', namaEn: 'Mark Zuckerberg', lahir: { tahun: 1984, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Teknologi', pencapaian: ['Mendirikan Facebook (kini Meta) saat masih kuliah di Harvard', 'Mengembangkan platform media sosial terbesar di dunia', 'Memimpin ekspansi perusahaan ke teknologi metaverse dan VR'], kutipan: 'Risiko terbesar adalah tidak mengambil risiko sama sekali.', trivia: 'Mendirikan Facebook dari kamar asramanya di Harvard sebelum akhirnya keluar kuliah.', relasi: [{ nama: 'Sheryl Sandberg', jenis: 'mantan COO Meta yang membantu membesarkan perusahaan' }] },
  { nama: 'Elon Musk', namaEn: 'Elon Musk', lahir: { tahun: 1971, negara: 'Afrika Selatan' }, wafat: null, bidang: 'Teknologi/Bisnis', pencapaian: ['Mendirikan/memimpin Tesla, SpaceX, dan beberapa perusahaan teknologi lain', 'SpaceX jadi perusahaan swasta pertama yang mengirim roket ke Stasiun Luar Angkasa Internasional', 'Mendorong adopsi kendaraan listrik secara global lewat Tesla'], kutipan: 'Ketika sesuatu cukup penting, kamu tetap melakukannya meski peluangnya tidak menguntungkan.', trivia: 'Salah satu pendiri awal PayPal sebelum perusahaan itu dijual ke eBay.', relasi: [{ nama: 'Peter Thiel', jenis: 'rekan sesama pendiri awal PayPal' }] },
  { nama: 'Ada Lovelace', namaEn: 'Ada Lovelace', lahir: { tahun: 1815, negara: 'Inggris' }, wafat: 1852, bidang: 'Matematika/Komputer', pencapaian: ['Menulis algoritma pertama yang dirancang untuk dijalankan mesin (Analytical Engine)', 'Dianggap sebagai programmer komputer pertama di dunia', 'Meramalkan komputer bisa dipakai lebih dari sekadar perhitungan angka'], kutipan: 'Yang memahami cara mengendalikan mesin ini akan menguasai kekuatan besar.', trivia: 'Adalah putri satu-satunya penyair terkenal Lord Byron, meski nyaris tak pernah mengenalnya.', relasi: [{ nama: 'Charles Babbage', jenis: 'kolaborator sekaligus perancang Analytical Engine' }] },
  { nama: 'Neil Armstrong', namaEn: 'Neil Armstrong', lahir: { tahun: 1930, negara: 'Amerika Serikat' }, wafat: 2012, bidang: 'Penjelajahan Antariksa', pencapaian: ['Menjadi manusia pertama yang menginjakkan kaki di Bulan (misi Apollo 11, 1969)', 'Bertugas sebagai pilot uji coba pesawat eksperimental di angkatan udara', 'Mengucapkan kalimat paling terkenal saat mendarat di Bulan'], kutipan: 'Itu satu langkah kecil bagi manusia, tapi lompatan besar bagi umat manusia.', trivia: 'Setelah pensiun dari NASA, ia memilih hidup relatif tertutup dan jarang tampil di publik.', relasi: [{ nama: 'Buzz Aldrin', jenis: 'rekan misi Apollo 11 yang mendarat bersamanya di Bulan' }] },
  { nama: 'Malala Yousafzai', namaEn: 'Malala Yousafzai', lahir: { tahun: 1997, negara: 'Pakistan' }, wafat: null, bidang: 'Aktivisme/Pendidikan', pencapaian: ['Menjadi penerima Hadiah Nobel Perdamaian termuda dalam sejarah (usia 17)', 'Memperjuangkan hak pendidikan anak perempuan lewat Malala Fund', 'Selamat dari upaya pembunuhan Taliban karena aktivismenya'], kutipan: 'Satu anak, satu guru, satu buku, satu pena, bisa mengubah dunia.', trivia: 'Mulai menulis blog tentang kehidupan di bawah kekuasaan Taliban sejak usia 11 tahun.', relasi: [{ nama: 'Ziauddin Yousafzai', jenis: 'ayah sekaligus pendukung awal aktivismenya' }] },
  { nama: 'Rosa Parks', namaEn: 'Rosa Parks', lahir: { tahun: 1913, negara: 'Amerika Serikat' }, wafat: 2005, bidang: 'Aktivisme/Hak Sipil', pencapaian: ['Menolak menyerahkan kursi bus ke penumpang kulit putih di Montgomery, 1955', 'Aksinya memicu Boikot Bus Montgomery', 'Dijuluki "Ibu dari Gerakan Hak Sipil Modern"'], kutipan: 'Aku ingin diperlakukan sebagai manusia biasa.', trivia: 'Sebelum aksinya yang terkenal, ia sudah aktif sebagai sekretaris cabang lokal NAACP.', relasi: [{ nama: 'Martin Luther King Jr.', jenis: 'memimpin boikot yang dipicu aksinya' }] },
  { nama: 'Jane Goodall', namaEn: 'Jane Goodall', lahir: { tahun: 1934, negara: 'Inggris' }, wafat: null, bidang: 'Primatologi', pencapaian: ['Melakukan riset jangka panjang perilaku simpanse liar di Tanzania', 'Menemukan bahwa simpanse bisa membuat dan menggunakan alat', 'Mendirikan Jane Goodall Institute untuk konservasi satwa liar'], kutipan: 'Yang kamu lakukan membuat perbedaan, dan kamu harus memutuskan perbedaan seperti apa yang ingin kamu buat.', trivia: 'Memulai risetnya tanpa gelar sarjana formal, sangat jarang di dunia sains saat itu.', relasi: [{ nama: 'Louis Leakey', jenis: 'paleontolog yang merekrut dan membimbing awal kariernya' }] },
  { nama: 'Nadiem Makarim', namaEn: 'Nadiem Makarim', lahir: { tahun: 1984, negara: 'Indonesia' }, wafat: null, bidang: 'Teknologi/Pendidikan', pencapaian: ['Mendirikan Gojek, salah satu decacorn pertama Asia Tenggara', 'Mengubah Gojek dari ojek online jadi super-app', 'Menjabat Menteri Pendidikan yang menginisiasi program "Merdeka Belajar"'], kutipan: 'Jangan takut memulai dari yang kecil, karena dampak besar sering dimulai dari langkah kecil.', trivia: 'Idenya membangun Gojek berawal dari pengalamannya sendiri sering memakai jasa ojek langganan.', relasi: [{ nama: 'Joko Widodo', jenis: 'presiden yang mengangkatnya jadi menteri' }] },
  { nama: 'Beyoncé', namaEn: 'Beyoncé', lahir: { tahun: 1981, negara: 'Amerika Serikat' }, wafat: null, bidang: 'Musik', pencapaian: ['Memenangkan Grammy Award terbanyak sepanjang sejarah untuk seorang artis', 'Memulai karier di girl group Destiny\'s Child sebelum sukses solo', 'Dikenal karena penampilan panggung megah dan pengaruh budaya lintas generasi'], kutipan: 'Kekuatan sejati tidak datang dari kekuatan fisik. Itu datang dari kemauan yang tak tergoyahkan.', trivia: 'Mengumumkan kehamilan kembarnya lewat unggahan media sosial paling banyak disukai saat itu.', relasi: [{ nama: 'Jay-Z', jenis: 'suami sekaligus sesama musisi berpengaruh' }] },
  { nama: 'Grace Hopper', namaEn: 'Grace Hopper', lahir: { tahun: 1906, negara: 'Amerika Serikat' }, wafat: 1992, bidang: 'Ilmu Komputer', pencapaian: ['Mengembangkan compiler pertama penerjemah bahasa manusia jadi kode mesin', 'Berperan besar mengembangkan bahasa pemrograman COBOL', 'Mencapai pangkat laksamana muda (rear admiral) di Angkatan Laut AS'], kutipan: 'Kapal aman di pelabuhan, tapi bukan itu tujuan kapal dibuat.', trivia: 'Dikreditkan mempopulerkan istilah "bug" komputer setelah menemukan ngengat tersangkut di mesin komputer awal.', relasi: [{ nama: 'John von Neumann', jenis: 'sesama perintis awal ilmu komputer' }] },
  { nama: 'Otto von Bismarck', namaEn: 'Otto von Bismarck', lahir: { tahun: 1815, negara: 'Jerman' }, wafat: 1898, bidang: 'Politik', pencapaian: ['Memimpin unifikasi negara-negara Jerman menjadi satu Kekaisaran Jerman 1871', 'Dijuluki "Kanselir Besi" karena kebijakan luar negeri yang tegas', 'Memperkenalkan sistem jaminan sosial pertama di dunia (asuransi kesehatan dan pensiun)'], kutipan: 'Politik adalah seni tentang yang mungkin.', trivia: 'Dikenal ahli diplomasi "realpolitik", mengutamakan kepentingan praktis negara di atas ideologi.', relasi: [{ nama: 'Kaiser Wilhelm I', jenis: 'raja yang memberinya mandat memimpin unifikasi Jerman' }] },
];

function norm(s) {
  return String(s || '').toLowerCase().trim();
}

function findTokoh(query) {
  const q = norm(query);
  if (!q) return null;
  let found = TOKOH.find((t) => norm(t.nama) === q || norm(t.namaEn) === q);
  if (found) return found;
  found = TOKOH.find((t) => q.includes(norm(t.nama)) || norm(t.nama).includes(q) || q.includes(norm(t.namaEn)));
  return found || null;
}

function fmtTahun(t) {
  if (t == null) return 'sekarang (masih hidup)';
  return t < 0 ? Math.abs(t) + ' SM' : String(t);
}

function composeTokoh(t) {
  const wafatStr = t.wafat == null ? 'Masih hidup hingga sekarang.' : 'Wafat tahun ' + fmtTahun(t.wafat) + '.';
  return (
    `${t.nama} (${t.bidang}) — lahir tahun ${fmtTahun(t.lahir.tahun)} di ${t.lahir.negara}. ${wafatStr}\n\n` +
    'Pencapaian utama:\n' + t.pencapaian.map((p) => '• ' + p).join('\n') + '\n\n' +
    'Kutipan: "' + t.kutipan + '"\n\n' +
    'Trivia: ' + t.trivia
  );
}

function tryProfil(text) {
  const m = text.match(/^(siapa\s+itu|siapa|ceritakan\s+tentang|biografi(\s+dari)?)\s+(.+?)\??$/i);
  if (!m) return null;
  const t = findTokoh(m[3]);
  if (!t) return null;
  return composeTokoh(t);
}

function tryPencapaian(text) {
  const m = text.match(/^apa\s+(saja\s+)?pencapaian\s+(.+?)\??$|^prestasi\s+(.+?)\s+apa\s+saja\??$/i);
  if (!m) return null;
  const name = m[2] || m[3];
  const t = findTokoh(name);
  if (!t) return null;
  return t.nama + ' — pencapaian utama:\n' + t.pencapaian.map((p) => '• ' + p).join('\n');
}

function tryKutipan(text) {
  const m = text.match(/^kutipan\s+(terkenal\s+)?(dari\s+)?(.+?)\??$|^quote\s+dari\s+(.+?)\??$/i);
  if (!m) return null;
  const name = m[3] || m[4];
  const t = findTokoh(name);
  if (!t) return null;
  return t.nama + ' pernah berkata: "' + t.kutipan + '"';
}

function tryTrivia(text) {
  const m = text.match(/^(fakta\s+unik|trivia)\s+(tentang\s+|dari\s+)?(.+?)\??$/i);
  if (!m) return null;
  const t = findTokoh(m[3]);
  if (!t) return null;
  return 'Fakta unik tentang ' + t.nama + ': ' + t.trivia;
}

function tryRelasi(text) {
  const m = text.match(/^siapa\s+yang\s+berhubungan\s+dengan\s+(.+?)\??$|^hubungan\s+(.+?)\s+dengan\s+siapa\??$/i);
  if (!m) return null;
  const name = m[1] || m[2];
  const t = findTokoh(name);
  if (!t || !t.relasi.length) return null;
  return t.nama + ' berhubungan dengan: ' + t.relasi.map((r) => r.nama + ' (' + r.jenis + ')').join(', ') + '.';
}

function tryTokoh(text) {
  const t = String(text || '').trim();
  if (!t) return null;
  return tryPencapaian(t) || tryKutipan(t) || tryTrivia(t) || tryRelasi(t) || tryProfil(t) || null;
}

export const tokohStore = Object.freeze({
  TOKOH,
  findTokoh,
  composeTokoh,
  tryProfil,
  tryPencapaian,
  tryKutipan,
  tryTrivia,
  tryRelasi,
  tryTokoh,
});
