const data = [
  { text: 'Republik Demokratik Kongo — bahasa Prancis resmi, berdampingan Lingala dan Swahili. Sapaan: bonjour (halo), merci (terima kasih).', metadata: { region: 'african-tengah', name: 'Prancis Kongo', nativeName: 'Français', speakers: '40 juta', script: 'Latin', family: 'Roman', officialIn: ['Kongo'], greetings: { halo: 'bonjour', pagi: 'bonjour', terimakasih: 'merci' }, tags: ['kongo', 'african-tengah'] } },
  { text: 'Angola — bahasa Portugis resmi, 25 juta penutur. Sapaan: olá (halo), obrigado (terima kasih).', metadata: { region: 'african-tengah', name: 'Portugis Angola', nativeName: 'Português', speakers: '25 juta', script: 'Latin', family: 'Roman', officialIn: ['Angola'], greetings: { halo: 'olá', pagi: 'bom dia', terimakasih: 'obrigado' }, tags: ['angola', 'african-tengah'] } },
  { text: 'Gabon — bahasa Prancis resmi, 2 juta penutur. Sapaan: bonjour (halo), merci (terima kasih).', metadata: { region: 'african-tengah', name: 'Prancis Gabon', nativeName: 'Français', speakers: '2 juta', script: 'Latin', family: 'Roman', officialIn: ['Gabon'], greetings: { halo: 'bonjour', pagi: 'bonjour', terimakasih: 'merci' }, tags: ['gabon', 'african-tengah'] } },
  { text: 'Chad — dwibahasa resmi Prancis dan Arab. Sapaan: bonjour/salam (halo), merci/shukran (terima kasih).', metadata: { region: 'african-tengah', name: 'Arab Chad', nativeName: 'العربية التشادية', speakers: '7 juta', script: 'Arab', family: 'Semitik', officialIn: ['Chad'], greetings: { halo: 'salam', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['chad', 'african-tengah'] } },
  { text: 'Republik Afrika Tengah — bahasa Sango, lingua franca nasional berdampingan Prancis resmi. Sapaan: balao (halo), singila (terima kasih).', metadata: { region: 'african-tengah', name: 'Sango', nativeName: 'Sängö', speakers: '5 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Republik Afrika Tengah'], greetings: { halo: 'balao', pagi: 'balao', terimakasih: 'singila' }, tags: ['republik afrika tengah', 'african-tengah'] } },
];

export const DATA = data;
