const data = [
  { text: 'Etiopia — bahasa Amharik, 32 juta penutur. Aksara: Ge\'ez. Sapaan: selam (halo), ameseginalehu (terima kasih).', metadata: { region: 'african-timur', name: 'Amharik', nativeName: 'አማርኛ', speakers: '32 juta', script: 'Ge\'ez', family: 'Semitik', officialIn: ['Etiopia'], greetings: { halo: 'selam', pagi: 'endet aderu', terimakasih: 'ameseginalehu' }, tags: ['etiopia', 'african-timur'] } },
  { text: 'Kenya — bahasa Swahili, 20 juta penutur asli (100 juta+ penutur kedua). Sapaan: jambo (halo), asante (terima kasih).', metadata: { region: 'african-timur', name: 'Swahili', nativeName: 'Kiswahili', speakers: '100 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Kenya', 'Tanzania', 'Uganda'], greetings: { halo: 'jambo', pagi: 'habari za asubuhi', terimakasih: 'asante' }, tags: ['kenya', 'tanzania', 'african-timur'] } },
  { text: 'Uganda — bahasa Inggris resmi, berdampingan dengan Swahili dan Luganda. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'african-timur', name: 'Inggris Uganda', nativeName: 'English', speakers: '8 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Uganda'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['uganda', 'african-timur'] } },
  { text: 'Somalia — bahasa Somali, 16 juta penutur. Sapaan: iska warran (halo), mahadsanid (terima kasih).', metadata: { region: 'african-timur', name: 'Somali', nativeName: 'Af-Soomaali', speakers: '16 juta', script: 'Latin', family: 'Afro-Asiatik', officialIn: ['Somalia'], greetings: { halo: 'iska warran', pagi: 'subax wanaagsan', terimakasih: 'mahadsanid' }, tags: ['somalia', 'african-timur'] } },
  { text: 'Rwanda — bahasa Kinyarwanda, 12 juta penutur. Sapaan: muraho (halo), murakoze (terima kasih).', metadata: { region: 'african-timur', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', speakers: '12 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Rwanda'], greetings: { halo: 'muraho', pagi: 'mwaramutse', terimakasih: 'murakoze' }, tags: ['rwanda', 'african-timur'] } },
  { text: 'Madagaskar — bahasa Malagasi, 25 juta penutur. Sapaan: manao ahoana (halo), misaotra (terima kasih).', metadata: { region: 'african-timur', name: 'Malagasi', nativeName: 'Malagasy', speakers: '25 juta', script: 'Latin', family: 'Austronesia', officialIn: ['Madagaskar'], greetings: { halo: 'manao ahoana', pagi: 'manao ahoana', terimakasih: 'misaotra' }, tags: ['madagaskar', 'african-timur'] } },
];

export const DATA = data;
