const data = [
  { text: 'Afrika Selatan — bahasa Zulu, 12 juta penutur, salah satu dari 11 bahasa resmi. Sapaan: sawubona (halo), ngiyabonga (terima kasih).', metadata: { region: 'african-selatan', name: 'Zulu', nativeName: 'isiZulu', speakers: '12 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Afrika Selatan'], greetings: { halo: 'sawubona', pagi: 'sawubona', terimakasih: 'ngiyabonga' }, tags: ['afrika selatan', 'african-selatan'] } },
  { text: 'Afrika Selatan — bahasa Afrikaans, 7 juta penutur, turunan Belanda. Sapaan: hallo (halo), dankie (terima kasih).', metadata: { region: 'african-selatan', name: 'Afrikaans', nativeName: 'Afrikaans', speakers: '7 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Afrika Selatan', 'Namibia'], greetings: { halo: 'hallo', pagi: 'goeie môre', terimakasih: 'dankie' }, tags: ['afrika selatan', 'african-selatan'] } },
  { text: 'Namibia — bahasa Inggris resmi, berdampingan Afrikaans dan Oshiwambo. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'african-selatan', name: 'Inggris Namibia', nativeName: 'English', speakers: '2,5 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Namibia'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['namibia', 'african-selatan'] } },
  { text: 'Botswana — bahasa Setswana, 5 juta penutur, resmi berdampingan Inggris. Sapaan: dumela (halo), ke a leboga (terima kasih).', metadata: { region: 'african-selatan', name: 'Setswana', nativeName: 'Setswana', speakers: '5 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Botswana'], greetings: { halo: 'dumela', pagi: 'dumela', terimakasih: 'ke a leboga' }, tags: ['botswana', 'african-selatan'] } },
  { text: 'Zimbabwe — bahasa Shona, 10 juta penutur, salah satu bahasa resmi terbanyak dituturkan. Sapaan: mhoro (halo), ndatenda (terima kasih).', metadata: { region: 'african-selatan', name: 'Shona', nativeName: 'chiShona', speakers: '10 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Zimbabwe'], greetings: { halo: 'mhoro', pagi: 'mangwanani', terimakasih: 'ndatenda' }, tags: ['zimbabwe', 'african-selatan'] } },
  { text: 'Mozambik — bahasa Portugis resmi, 12 juta penutur. Sapaan: olá (halo), obrigado (terima kasih).', metadata: { region: 'african-selatan', name: 'Portugis Mozambik', nativeName: 'Português', speakers: '12 juta', script: 'Latin', family: 'Roman', officialIn: ['Mozambik'], greetings: { halo: 'olá', pagi: 'bom dia', terimakasih: 'obrigado' }, tags: ['mozambik', 'african-selatan'] } },
];

export const DATA = data;
