const data = [
  { text: 'Brasil — bahasa Portugis, 210 juta penutur. Aksara: Latin. Sapaan: olá (halo), obrigado (terima kasih).', metadata: { region: 'american-selatan', name: 'Portugis Brasil', nativeName: 'Português', speakers: '210 juta', script: 'Latin', family: 'Roman', officialIn: ['Brasil'], greetings: { halo: 'olá', pagi: 'bom dia', terimakasih: 'obrigado' }, tags: ['brasil', 'american-selatan'] } },
  { text: 'Argentina — bahasa Spanyol, 45 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-selatan', name: 'Spanyol Argentina', nativeName: 'Español', speakers: '45 juta', script: 'Latin', family: 'Roman', officialIn: ['Argentina'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['argentina', 'american-selatan'] } },
  { text: 'Kolombia — bahasa Spanyol, 50 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-selatan', name: 'Spanyol Kolombia', nativeName: 'Español', speakers: '50 juta', script: 'Latin', family: 'Roman', officialIn: ['Kolombia'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['kolombia', 'american-selatan'] } },
  { text: 'Chili — bahasa Spanyol, 19 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-selatan', name: 'Spanyol Chili', nativeName: 'Español', speakers: '19 juta', script: 'Latin', family: 'Roman', officialIn: ['Chili'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['chili', 'american-selatan'] } },
  { text: 'Peru — bahasa Quechua, 4 juta penutur, resmi berdampingan Spanyol. Sapaan: napaykullayki (halo), sulpayki (terima kasih).', metadata: { region: 'american-selatan', name: 'Quechua', nativeName: 'Runa Simi', speakers: '4 juta', script: 'Latin', family: 'Quechuan', officialIn: ['Peru', 'Bolivia'], greetings: { halo: 'napaykullayki', pagi: 'allin p\'unchay', terimakasih: 'sulpayki' }, tags: ['peru', 'american-selatan', 'bahasa asli'] } },
  { text: 'Venezuela — bahasa Spanyol, 29 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-selatan', name: 'Spanyol Venezuela', nativeName: 'Español', speakers: '29 juta', script: 'Latin', family: 'Roman', officialIn: ['Venezuela'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['venezuela', 'american-selatan'] } },
  { text: 'Bolivia — bahasa Aymara, 1,7 juta penutur, resmi berdampingan Spanyol. Sapaan: kamisaraki (halo), yuspagara (terima kasih).', metadata: { region: 'american-selatan', name: 'Aymara', nativeName: 'Aymar aru', speakers: '1,7 juta', script: 'Latin', family: 'Aymaran', officialIn: ['Bolivia'], greetings: { halo: 'kamisaraki', pagi: 'kamisaraki', terimakasih: 'yuspagara' }, tags: ['bolivia', 'american-selatan', 'bahasa asli'] } },
  { text: 'Paraguay — bahasa Guarani, 6,5 juta penutur, resmi berdampingan Spanyol. Sapaan: mba\'éichapa (halo), aguyje (terima kasih).', metadata: { region: 'american-selatan', name: 'Guarani', nativeName: 'Avañeʼẽ', speakers: '6,5 juta', script: 'Latin', family: 'Tupi-Guarani', officialIn: ['Paraguay'], greetings: { halo: 'mba\'éichapa', pagi: 'mba\'éichapa', terimakasih: 'aguyje' }, tags: ['paraguay', 'american-selatan', 'bahasa asli'] } },
  { text: 'Uruguay — bahasa Spanyol, 3,4 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-selatan', name: 'Spanyol Uruguay', nativeName: 'Español', speakers: '3,4 juta', script: 'Latin', family: 'Roman', officialIn: ['Uruguay'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['uruguay', 'american-selatan'] } },
  { text: 'Guyana — bahasa Inggris, 800 ribu penutur, satu-satunya negara Inggris di Amerika Selatan. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'american-selatan', name: 'Inggris Guyana', nativeName: 'English', speakers: '800 ribu', script: 'Latin', family: 'Jermanik', officialIn: ['Guyana'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['guyana', 'american-selatan'] } },
  { text: 'Suriname — bahasa Belanda, 600 ribu penutur, satu-satunya negara Belanda di Amerika Selatan. Sapaan: hallo (halo), dank je (terima kasih).', metadata: { region: 'american-selatan', name: 'Belanda Suriname', nativeName: 'Nederlands', speakers: '600 ribu', script: 'Latin', family: 'Jermanik', officialIn: ['Suriname'], greetings: { halo: 'hallo', pagi: 'goedemorgen', terimakasih: 'dank je' }, tags: ['suriname', 'american-selatan'] } },
];

export const DATA = data;
