const data = [
  { text: 'Jamaika — bahasa Inggris resmi, berdampingan dengan Patois Jamaika. Sapaan: hello (halo), wah gwaan (sapaan santai), thanks (terima kasih).', metadata: { region: 'american-karibia', name: 'Inggris Jamaika', nativeName: 'English', speakers: '3 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Jamaika'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['jamaika', 'american-karibia'] } },
  { text: 'Haiti — bahasa Kreol Haiti, 12 juta penutur, resmi berdampingan Prancis. Sapaan: bonjou (halo), mèsi (terima kasih).', metadata: { region: 'american-karibia', name: 'Kreol Haiti', nativeName: 'Kreyòl ayisyen', speakers: '12 juta', script: 'Latin', family: 'Kreol berbasis Prancis', officialIn: ['Haiti'], greetings: { halo: 'bonjou', pagi: 'bonjou', terimakasih: 'mèsi' }, tags: ['haiti', 'american-karibia'] } },
  { text: 'Republik Dominika — bahasa Spanyol, 11 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-karibia', name: 'Spanyol Dominika', nativeName: 'Español', speakers: '11 juta', script: 'Latin', family: 'Roman', officialIn: ['Republik Dominika'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['republik dominika', 'american-karibia'] } },
  { text: 'Bahama — bahasa Inggris resmi, berdampingan dengan Kreol Bahama. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'american-karibia', name: 'Inggris Bahama', nativeName: 'English', speakers: '400 ribu', script: 'Latin', family: 'Jermanik', officialIn: ['Bahama'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['bahama', 'american-karibia'] } },
  { text: 'Barbados — bahasa Inggris resmi, berdampingan dengan Bajan Creole. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'american-karibia', name: 'Inggris Barbados', nativeName: 'English', speakers: '280 ribu', script: 'Latin', family: 'Jermanik', officialIn: ['Barbados'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['barbados', 'american-karibia'] } },
  { text: 'Trinidad dan Tobago — bahasa Inggris, 1,3 juta penutur. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'american-karibia', name: 'Inggris Trinidad', nativeName: 'English', speakers: '1,3 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Trinidad dan Tobago'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['trinidad dan tobago', 'american-karibia'] } },
  { text: 'Puerto Rico — bahasa Spanyol, 3,2 juta penutur, resmi berdampingan Inggris. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-karibia', name: 'Spanyol Puerto Rico', nativeName: 'Español', speakers: '3,2 juta', script: 'Latin', family: 'Roman', officialIn: ['Puerto Rico'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['puerto rico', 'american-karibia'] } },
];

export const DATA = data;
