const data = [
  { text: 'India — bahasa Hindi, 600 juta penutur. Aksara: Devanagari. Sapaan: namaste (halo), dhanyavaad (terima kasih).', metadata: { region: 'asian-selatan', name: 'Hindi', nativeName: 'हिन्दी', speakers: '600 juta', script: 'Devanagari', family: 'Indo-Arya', officialIn: ['India'], greetings: { halo: 'namaste', pagi: 'suprabhat', terimakasih: 'dhanyavaad' }, tags: ['india', 'asia selatan'] } },
  { text: 'Pakistan — bahasa Urdu, 70 juta penutur asli. Aksara: Nastaliq (Arab-Persia). Sapaan: assalamualaikum (halo), shukriya (terima kasih).', metadata: { region: 'asian-selatan', name: 'Urdu', nativeName: 'اردو', speakers: '70 juta', script: 'Nastaliq', family: 'Indo-Arya', officialIn: ['Pakistan'], greetings: { halo: 'assalamualaikum', pagi: 'subah bakhair', terimakasih: 'shukriya' }, tags: ['pakistan', 'asia selatan'] } },
  { text: 'Bangladesh — bahasa Bengali, 230 juta penutur. Aksara: Bengali. Sapaan: assalamualaikum (halo), dhonnobad (terima kasih).', metadata: { region: 'asian-selatan', name: 'Bengali', nativeName: 'বাংলা', speakers: '230 juta', script: 'Bengali', family: 'Indo-Arya', officialIn: ['Bangladesh', 'India'], greetings: { halo: 'assalamualaikum', pagi: 'shuprovat', terimakasih: 'dhonnobad' }, tags: ['bangladesh', 'asia selatan'] } },
  { text: 'Sri Lanka — bahasa Sinhala, 16 juta penutur. Aksara: Sinhala. Sapaan: ayubowan (halo), sthuthi (terima kasih).', metadata: { region: 'asian-selatan', name: 'Sinhala', nativeName: 'සිංහල', speakers: '16 juta', script: 'Sinhala', family: 'Indo-Arya', officialIn: ['Sri Lanka'], greetings: { halo: 'ayubowan', pagi: 'suba udesanak', terimakasih: 'sthuthi' }, tags: ['sri lanka', 'asia selatan'] } },
  { text: 'Nepal — bahasa Nepali, 17 juta penutur. Aksara: Devanagari. Sapaan: namaste (halo), dhanyabad (terima kasih).', metadata: { region: 'asian-selatan', name: 'Nepali', nativeName: 'नेपाली', speakers: '17 juta', script: 'Devanagari', family: 'Indo-Arya', officialIn: ['Nepal'], greetings: { halo: 'namaste', pagi: 'shuprabhat', terimakasih: 'dhanyabad' }, tags: ['nepal', 'asia selatan'] } },
  { text: 'Bhutan — bahasa Dzongkha, 640 ribu penutur. Aksara: Aksara Tibet. Sapaan: kuzuzangpo (halo), kadinche (terima kasih).', metadata: { region: 'asian-selatan', name: 'Dzongkha', nativeName: 'རྫོང་ཁ', speakers: '640 ribu', script: 'Aksara Tibet', family: 'Sino-Tibet', officialIn: ['Bhutan'], greetings: { halo: 'kuzuzangpo', pagi: 'kuzuzangpo', terimakasih: 'kadinche' }, tags: ['bhutan', 'asia selatan'] } },
  { text: 'Maladewa — bahasa Dhivehi, 340 ribu penutur. Aksara: Thaana. Sapaan: assalaamu alaikum (halo), shukuriyaa (terima kasih).', metadata: { region: 'asian-selatan', name: 'Dhivehi', nativeName: 'ދިވެހި', speakers: '340 ribu', script: 'Thaana', family: 'Indo-Arya', officialIn: ['Maladewa'], greetings: { halo: 'assalaamu alaikum', pagi: 'assalaamu alaikum', terimakasih: 'shukuriyaa' }, tags: ['maladewa', 'asia selatan'] } },
  { text: 'Afghanistan — bahasa Pashto dan Dari, gabungan sekitar 40 juta penutur. Aksara: Arab-Persia. Sapaan: salaam (halo), manana (terima kasih).', metadata: { region: 'asian-selatan', name: 'Pashto', nativeName: 'پښتو', speakers: '40 juta', script: 'Arab-Persia', family: 'Indo-Iran', officialIn: ['Afghanistan'], greetings: { halo: 'salaam', pagi: 'sahar mo pa khair', terimakasih: 'manana' }, tags: ['afghanistan', 'asia selatan'] } },
];

export const DATA = data;
