const data = [
  { text: 'Italia — bahasa Italia, 65 juta penutur. Aksara: Latin. Sapaan: ciao (halo), grazie (terima kasih).', metadata: { region: 'eropan-selatan', name: 'Italia', nativeName: 'Italiano', speakers: '65 juta', script: 'Latin', family: 'Roman', officialIn: ['Italia', 'San Marino'], greetings: { halo: 'ciao', pagi: 'buongiorno', terimakasih: 'grazie' }, tags: ['italia', 'eropa selatan'] } },
  { text: 'Spanyol — bahasa Spanyol, 480 juta penutur global. Aksara: Latin. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'eropan-selatan', name: 'Spanyol', nativeName: 'Español', speakers: '480 juta', script: 'Latin', family: 'Roman', officialIn: ['Spanyol'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['spanyol', 'eropa selatan'] } },
  { text: 'Portugal — bahasa Portugis, 260 juta penutur global. Aksara: Latin. Sapaan: olá (halo), obrigado (terima kasih).', metadata: { region: 'eropan-selatan', name: 'Portugis', nativeName: 'Português', speakers: '260 juta', script: 'Latin', family: 'Roman', officialIn: ['Portugal'], greetings: { halo: 'olá', pagi: 'bom dia', terimakasih: 'obrigado' }, tags: ['portugal', 'eropa selatan'] } },
  { text: 'Yunani — bahasa Yunani, 13 juta penutur. Aksara: Yunani. Sapaan: yassou (halo), efharisto (terima kasih).', metadata: { region: 'eropan-selatan', name: 'Yunani', nativeName: 'Ελληνικά', speakers: '13 juta', script: 'Yunani', family: 'Helenik', officialIn: ['Yunani', 'Siprus'], greetings: { halo: 'yassou', pagi: 'kalimera', terimakasih: 'efharisto' }, tags: ['yunani', 'eropa selatan'] } },
  { text: 'Kroasia — bahasa Kroasia, 5,6 juta penutur. Aksara: Latin. Sapaan: bok (halo), hvala (terima kasih).', metadata: { region: 'eropan-selatan', name: 'Kroasia', nativeName: 'Hrvatski', speakers: '5,6 juta', script: 'Latin', family: 'Slavik', officialIn: ['Kroasia'], greetings: { halo: 'bok', pagi: 'dobro jutro', terimakasih: 'hvala' }, tags: ['kroasia', 'eropa selatan'] } },
  { text: 'Malta — bahasa Malta, 520 ribu penutur, campuran Arab dan Latin. Sapaan: bonġu (halo), grazzi (terima kasih).', metadata: { region: 'eropan-selatan', name: 'Malta', nativeName: 'Malti', speakers: '520 ribu', script: 'Latin', family: 'Semitik', officialIn: ['Malta'], greetings: { halo: 'bonġu', pagi: 'bonġu', terimakasih: 'grazzi' }, tags: ['malta', 'eropa selatan'] } },
];

export const DATA = data;
