const data = [
  { text: 'Norwegia — bahasa Norwegia, 5,3 juta penutur. Aksara: Latin. Sapaan: hei (halo), takk (terima kasih).', metadata: { region: 'eropan-utara', name: 'Norwegia', nativeName: 'Norsk', speakers: '5,3 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Norwegia'], greetings: { halo: 'hei', pagi: 'god morgen', terimakasih: 'takk' }, tags: ['norwegia', 'eropa utara'] } },
  { text: 'Swedia — bahasa Swedia, 10 juta penutur. Aksara: Latin. Sapaan: hej (halo), tack (terima kasih).', metadata: { region: 'eropan-utara', name: 'Swedia', nativeName: 'Svenska', speakers: '10 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Swedia'], greetings: { halo: 'hej', pagi: 'god morgon', terimakasih: 'tack' }, tags: ['swedia', 'eropa utara'] } },
  { text: 'Finlandia — bahasa Finlandia, 5,4 juta penutur. Aksara: Latin. Sapaan: hei (halo), kiitos (terima kasih).', metadata: { region: 'eropan-utara', name: 'Finlandia', nativeName: 'Suomi', speakers: '5,4 juta', script: 'Latin', family: 'Finno-Ugrik', officialIn: ['Finlandia'], greetings: { halo: 'hei', pagi: 'hyvää huomenta', terimakasih: 'kiitos' }, tags: ['finlandia', 'eropa utara'] } },
  { text: 'Denmark — bahasa Denmark, 6 juta penutur. Aksara: Latin. Sapaan: hej (halo), tak (terima kasih).', metadata: { region: 'eropan-utara', name: 'Denmark', nativeName: 'Dansk', speakers: '6 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Denmark'], greetings: { halo: 'hej', pagi: 'god morgen', terimakasih: 'tak' }, tags: ['denmark', 'eropa utara'] } },
  { text: 'Islandia — bahasa Islandia, 370 ribu penutur. Aksara: Latin. Sapaan: halló (halo), takk (terima kasih).', metadata: { region: 'eropan-utara', name: 'Islandia', nativeName: 'Íslenska', speakers: '370 ribu', script: 'Latin', family: 'Jermanik', officialIn: ['Islandia'], greetings: { halo: 'halló', pagi: 'góðan daginn', terimakasih: 'takk' }, tags: ['islandia', 'eropa utara'] } },
  { text: 'Estonia — bahasa Estonia, 1,1 juta penutur. Aksara: Latin. Sapaan: tere (halo), aitäh (terima kasih).', metadata: { region: 'eropan-utara', name: 'Estonia', nativeName: 'Eesti keel', speakers: '1,1 juta', script: 'Latin', family: 'Finno-Ugrik', officialIn: ['Estonia'], greetings: { halo: 'tere', pagi: 'tere hommikust', terimakasih: 'aitäh' }, tags: ['estonia', 'eropa utara'] } },
  { text: 'Latvia — bahasa Latvia, 1,5 juta penutur. Aksara: Latin. Sapaan: sveiki (halo), paldies (terima kasih).', metadata: { region: 'eropan-utara', name: 'Latvia', nativeName: 'Latviešu', speakers: '1,5 juta', script: 'Latin', family: 'Baltik', officialIn: ['Latvia'], greetings: { halo: 'sveiki', pagi: 'labrīt', terimakasih: 'paldies' }, tags: ['latvia', 'eropa utara'] } },
  { text: 'Lithuania — bahasa Lithuania, 2,8 juta penutur. Aksara: Latin. Sapaan: labas (halo), ačiū (terima kasih).', metadata: { region: 'eropan-utara', name: 'Lithuania', nativeName: 'Lietuvių', speakers: '2,8 juta', script: 'Latin', family: 'Baltik', officialIn: ['Lithuania'], greetings: { halo: 'labas', pagi: 'labas rytas', terimakasih: 'ačiū' }, tags: ['lithuania', 'eropa utara'] } },
];

export const DATA = data;
