const data = [
  { text: 'Jerman — bahasa Jerman, 100 juta penutur. Aksara: Latin. Sapaan: hallo (halo), danke (terima kasih).', metadata: { region: 'eropan-barat', name: 'Jerman', nativeName: 'Deutsch', speakers: '100 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Jerman', 'Austria', 'Swiss'], greetings: { halo: 'hallo', pagi: 'guten morgen', terimakasih: 'danke' }, tags: ['jerman', 'eropa barat'] } },
  { text: 'Prancis — bahasa Prancis, 80 juta penutur asli (300 juta global). Aksara: Latin. Sapaan: bonjour (halo), merci (terima kasih).', metadata: { region: 'eropan-barat', name: 'Prancis', nativeName: 'Français', speakers: '80 juta', script: 'Latin', family: 'Roman', officialIn: ['Prancis', 'Belgia', 'Swiss'], greetings: { halo: 'bonjour', pagi: 'bonjour', terimakasih: 'merci' }, tags: ['prancis', 'eropa barat'] } },
  { text: 'Inggris — bahasa Inggris, 75 juta penutur asli (1,5 miliar global). Aksara: Latin. Sapaan: hello (halo), thank you (terima kasih).', metadata: { region: 'eropan-barat', name: 'Inggris', nativeName: 'English', speakers: '1,5 miliar', script: 'Latin', family: 'Jermanik', officialIn: ['Inggris', 'Irlandia'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thank you' }, tags: ['inggris', 'eropa barat'] } },
  { text: 'Belanda — bahasa Belanda, 24 juta penutur. Aksara: Latin. Sapaan: hallo (halo), dank je (terima kasih).', metadata: { region: 'eropan-barat', name: 'Belanda', nativeName: 'Nederlands', speakers: '24 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Belanda', 'Belgia'], greetings: { halo: 'hallo', pagi: 'goedemorgen', terimakasih: 'dank je' }, tags: ['belanda', 'eropa barat'] } },
  { text: 'Swiss — bahasa Jerman, Prancis, Italia, dan Romansh, empat bahasa resmi. Sapaan: grüezi (halo, dialek Swiss-Jerman).', metadata: { region: 'eropan-barat', name: 'Romansh', nativeName: 'Rumantsch', speakers: '40 ribu', script: 'Latin', family: 'Roman', officialIn: ['Swiss'], greetings: { halo: 'allegra', pagi: 'bun di', terimakasih: 'grazia' }, tags: ['swiss', 'eropa barat'] } },
  { text: 'Irlandia — bahasa Irlandia (Gaelik), 1,7 juta penutur. Aksara: Latin. Sapaan: dia dhuit (halo), go raibh maith agat (terima kasih).', metadata: { region: 'eropan-barat', name: 'Irlandia', nativeName: 'Gaeilge', speakers: '1,7 juta', script: 'Latin', family: 'Keltik', officialIn: ['Irlandia'], greetings: { halo: 'dia dhuit', pagi: 'maidin mhaith', terimakasih: 'go raibh maith agat' }, tags: ['irlandia', 'eropa barat'] } },
];

export const DATA = data;
