const data = [
  { text: 'Rusia — bahasa Rusia, 150 juta penutur asli (250 juta global). Aksara: Sirilik. Sapaan: privet (halo), spasibo (terima kasih).', metadata: { region: 'eropan-timur', name: 'Rusia', nativeName: 'Русский', speakers: '250 juta', script: 'Sirilik', family: 'Slavik', officialIn: ['Rusia', 'Belarus'], greetings: { halo: 'privet', pagi: 'dobroye utro', terimakasih: 'spasibo' }, tags: ['rusia', 'eropa timur'] } },
  { text: 'Ukraina — bahasa Ukraina, 40 juta penutur. Aksara: Sirilik. Sapaan: pryvit (halo), dyakuyu (terima kasih).', metadata: { region: 'eropan-timur', name: 'Ukraina', nativeName: 'Українська', speakers: '40 juta', script: 'Sirilik', family: 'Slavik', officialIn: ['Ukraina'], greetings: { halo: 'pryvit', pagi: 'dobroho ranku', terimakasih: 'dyakuyu' }, tags: ['ukraina', 'eropa timur'] } },
  { text: 'Rumania — bahasa Rumania, 24 juta penutur. Aksara: Latin. Sapaan: salut (halo), mulțumesc (terima kasih).', metadata: { region: 'eropan-timur', name: 'Rumania', nativeName: 'Română', speakers: '24 juta', script: 'Latin', family: 'Roman', officialIn: ['Rumania', 'Moldova'], greetings: { halo: 'salut', pagi: 'bună dimineața', terimakasih: 'mulțumesc' }, tags: ['rumania', 'eropa timur'] } },
  { text: 'Belarus — bahasa Belarus, 5 juta penutur. Aksara: Sirilik. Sapaan: vitaju (halo), dziakuj (terima kasih).', metadata: { region: 'eropan-timur', name: 'Belarus', nativeName: 'Беларуская', speakers: '5 juta', script: 'Sirilik', family: 'Slavik', officialIn: ['Belarus'], greetings: { halo: 'vitaju', pagi: 'dobray ranicy', terimakasih: 'dziakuj' }, tags: ['belarus', 'eropa timur'] } },
  { text: 'Bulgaria — bahasa Bulgaria, 8 juta penutur. Aksara: Sirilik. Sapaan: zdravei (halo), blagodarya (terima kasih).', metadata: { region: 'eropan-timur', name: 'Bulgaria', nativeName: 'Български', speakers: '8 juta', script: 'Sirilik', family: 'Slavik', officialIn: ['Bulgaria'], greetings: { halo: 'zdravei', pagi: 'dobro utro', terimakasih: 'blagodarya' }, tags: ['bulgaria', 'eropa timur'] } },
];

export const DATA = data;
