const data = [
  { text: 'Australia — bahasa Inggris, 20 juta penutur. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'osenian', name: 'Inggris Australia', nativeName: 'English', speakers: '20 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Australia'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['australia', 'osenian'] } },
  { text: 'Selandia Baru — bahasa Maori, 185 ribu penutur, resmi berdampingan Inggris. Sapaan: kia ora (halo), ngā mihi (terima kasih).', metadata: { region: 'osenian', name: 'Maori', nativeName: 'Te Reo Māori', speakers: '185 ribu', script: 'Latin', family: 'Austronesia', officialIn: ['Selandia Baru'], greetings: { halo: 'kia ora', pagi: 'ata mārie', terimakasih: 'ngā mihi' }, tags: ['selandia baru', 'osenian'] } },
  { text: 'Fiji — bahasa Fiji, 350 ribu penutur, resmi berdampingan Inggris. Sapaan: bula (halo), vinaka (terima kasih).', metadata: { region: 'osenian', name: 'Fiji', nativeName: 'Vosa Vakaviti', speakers: '350 ribu', script: 'Latin', family: 'Austronesia', officialIn: ['Fiji'], greetings: { halo: 'bula', pagi: 'yadra', terimakasih: 'vinaka' }, tags: ['fiji', 'osenian'] } },
  { text: 'Papua Nugini — bahasa Tok Pisin, lingua franca nasional, 4 juta penutur. Sapaan: apinun (halo), tenkyu (terima kasih).', metadata: { region: 'osenian', name: 'Tok Pisin', nativeName: 'Tok Pisin', speakers: '4 juta', script: 'Latin', family: 'Kreol berbasis Inggris', officialIn: ['Papua Nugini'], greetings: { halo: 'apinun', pagi: 'moning', terimakasih: 'tenkyu' }, tags: ['papua nugini', 'osenian'] } },
  { text: 'Samoa — bahasa Samoa, 500 ribu penutur, resmi berdampingan Inggris. Sapaan: talofa (halo), fa\'afetai (terima kasih).', metadata: { region: 'osenian', name: 'Samoa', nativeName: 'Gagana Samoa', speakers: '500 ribu', script: 'Latin', family: 'Austronesia', officialIn: ['Samoa'], greetings: { halo: 'talofa', pagi: 'talofa', terimakasih: 'fa\'afetai' }, tags: ['samoa', 'osenian'] } },
  { text: 'Tonga — bahasa Tonga, 190 ribu penutur, resmi berdampingan Inggris. Sapaan: malo e lelei (halo), malo (terima kasih).', metadata: { region: 'osenian', name: 'Tonga', nativeName: 'Lea Faka-Tonga', speakers: '190 ribu', script: 'Latin', family: 'Austronesia', officialIn: ['Tonga'], greetings: { halo: 'malo e lelei', pagi: 'malo e lelei', terimakasih: 'malo' }, tags: ['tonga', 'osenian'] } },
];

export const DATA = data;
