const data = [
  { text: 'Nigeria — bahasa Hausa, 70 juta penutur, salah satu bahasa terbesar Afrika Barat. Sapaan: sannu (halo), na gode (terima kasih).', metadata: { region: 'african-barat', name: 'Hausa', nativeName: 'Hausa', speakers: '70 juta', script: 'Latin', family: 'Afro-Asiatik', officialIn: ['Nigeria', 'Ghana'], greetings: { halo: 'sannu', pagi: 'ina kwana', terimakasih: 'na gode' }, tags: ['nigeria', 'african-barat'] } },
  { text: 'Nigeria — bahasa Yoruba, 45 juta penutur. Sapaan: bawo (halo), e se (terima kasih).', metadata: { region: 'african-barat', name: 'Yoruba', nativeName: 'Yorùbá', speakers: '45 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Nigeria'], greetings: { halo: 'bawo', pagi: 'e kaaro', terimakasih: 'e se' }, tags: ['nigeria', 'african-barat'] } },
  { text: 'Nigeria — bahasa Igbo, 27 juta penutur. Sapaan: ndewo (halo), daalu (terima kasih).', metadata: { region: 'african-barat', name: 'Igbo', nativeName: 'Igbo', speakers: '27 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Nigeria'], greetings: { halo: 'ndewo', pagi: 'ụtụtụ ọma', terimakasih: 'daalu' }, tags: ['nigeria', 'african-barat'] } },
  { text: 'Ghana — bahasa Inggris resmi, berdampingan dengan Twi lokal. Sapaan: hello (halo), medaase (terima kasih, Twi).', metadata: { region: 'african-barat', name: 'Inggris Ghana', nativeName: 'English', speakers: '10 juta', script: 'Latin', family: 'Jermanik', officialIn: ['Ghana'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'medaase' }, tags: ['ghana', 'african-barat'] } },
  { text: 'Pantai Gading — bahasa Prancis resmi, 25 juta penutur. Sapaan: bonjour (halo), merci (terima kasih).', metadata: { region: 'african-barat', name: 'Prancis Pantai Gading', nativeName: 'Français', speakers: '25 juta', script: 'Latin', family: 'Roman', officialIn: ['Pantai Gading'], greetings: { halo: 'bonjour', pagi: 'bonjour', terimakasih: 'merci' }, tags: ['pantai gading', 'african-barat'] } },
  { text: 'Senegal — bahasa Wolof, 12 juta penutur, lingua franca lokal berdampingan Prancis resmi. Sapaan: nanga def (halo), jërëjëf (terima kasih).', metadata: { region: 'african-barat', name: 'Wolof', nativeName: 'Wolof', speakers: '12 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Senegal'], greetings: { halo: 'nanga def', pagi: 'jamm nga fanane', terimakasih: 'jërëjëf' }, tags: ['senegal', 'african-barat'] } },
  { text: 'Mali — bahasa Bambara, 14 juta penutur, lingua franca lokal berdampingan Prancis resmi. Sapaan: i ni ce (halo), i ni ce (terima kasih).', metadata: { region: 'african-barat', name: 'Bambara', nativeName: 'Bamanankan', speakers: '14 juta', script: 'Latin', family: 'Niger-Kongo', officialIn: ['Mali'], greetings: { halo: 'i ni ce', pagi: 'i ni sogoma', terimakasih: 'i ni ce' }, tags: ['mali', 'african-barat'] } },
  { text: 'Kamerun — dwibahasa resmi Prancis dan Inggris. Sapaan: bonjour/hello (halo), merci/thanks (terima kasih).', metadata: { region: 'african-barat', name: 'Prancis Kamerun', nativeName: 'Français', speakers: '15 juta', script: 'Latin', family: 'Roman', officialIn: ['Kamerun'], greetings: { halo: 'bonjour', pagi: 'bonjour', terimakasih: 'merci' }, tags: ['kamerun', 'african-barat'] } },
];

export const DATA = data;
