const data = [
  { text: 'Mesir — bahasa Arab dialek Mesir, 100 juta penutur. Sapaan: ahlan (halo), shukran (terima kasih).', metadata: { region: 'african-utara', name: 'Arab Mesir', nativeName: 'العربية المصرية', speakers: '100 juta', script: 'Arab', family: 'Semitik', officialIn: ['Mesir'], greetings: { halo: 'ahlan', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['mesir', 'african-utara'] } },
  { text: 'Maroko — bahasa Arab Maroko (Darija), berdampingan dengan Berber. Sapaan: salam (halo), shukran (terima kasih).', metadata: { region: 'african-utara', name: 'Arab Maroko', nativeName: 'الدارجة', speakers: '30 juta', script: 'Arab', family: 'Semitik', officialIn: ['Maroko'], greetings: { halo: 'salam', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['maroko', 'african-utara'] } },
  { text: 'Aljazair — bahasa Arab, resmi berdampingan Berber (Tamazight). Sapaan: salam (halo), shukran (terima kasih).', metadata: { region: 'african-utara', name: 'Berber (Tamazight)', nativeName: 'ⵜⴰⵎⴰⵣⵉⵖⵜ', speakers: '14 juta', script: 'Tifinagh', family: 'Afro-Asiatik', officialIn: ['Aljazair', 'Maroko'], greetings: { halo: 'azul', pagi: 'azul', terimakasih: 'tanmirt' }, tags: ['aljazair', 'african-utara', 'bahasa asli'] } },
  { text: 'Tunisia — bahasa Arab Tunisia, 12 juta penutur. Sapaan: aslema (halo), shukran (terima kasih).', metadata: { region: 'african-utara', name: 'Arab Tunisia', nativeName: 'التونسية', speakers: '12 juta', script: 'Arab', family: 'Semitik', officialIn: ['Tunisia'], greetings: { halo: 'aslema', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['tunisia', 'african-utara'] } },
  { text: 'Libya — bahasa Arab Libya, 7 juta penutur. Sapaan: salam (halo), shukran (terima kasih).', metadata: { region: 'african-utara', name: 'Arab Libya', nativeName: 'الليبية', speakers: '7 juta', script: 'Arab', family: 'Semitik', officialIn: ['Libya'], greetings: { halo: 'salam', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['libya', 'african-utara'] } },
  { text: 'Sudan — bahasa Arab Sudan, 30 juta penutur. Sapaan: salam (halo), shukran (terima kasih).', metadata: { region: 'african-utara', name: 'Arab Sudan', nativeName: 'العربية السودانية', speakers: '30 juta', script: 'Arab', family: 'Semitik', officialIn: ['Sudan'], greetings: { halo: 'salam', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['sudan', 'african-utara'] } },
];

export const DATA = data;
