const data = [
  { text: 'Guatemala — bahasa Spanyol resmi, berdampingan dengan bahasa Maya K\'iche\'. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-tengah', name: 'Spanyol Guatemala', nativeName: 'Español', speakers: '15 juta', script: 'Latin', family: 'Roman', officialIn: ['Guatemala'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['guatemala', 'american-tengah'] } },
  { text: 'Honduras — bahasa Spanyol, 9 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-tengah', name: 'Spanyol Honduras', nativeName: 'Español', speakers: '9 juta', script: 'Latin', family: 'Roman', officialIn: ['Honduras'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['honduras', 'american-tengah'] } },
  { text: 'Nikaragua — bahasa Spanyol, 6 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-tengah', name: 'Spanyol Nikaragua', nativeName: 'Español', speakers: '6 juta', script: 'Latin', family: 'Roman', officialIn: ['Nikaragua'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['nikaragua', 'american-tengah'] } },
  { text: 'Kosta Rika — bahasa Spanyol, 5 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-tengah', name: 'Spanyol Kosta Rika', nativeName: 'Español', speakers: '5 juta', script: 'Latin', family: 'Roman', officialIn: ['Kosta Rika'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['kosta rika', 'american-tengah'] } },
  { text: 'Panama — bahasa Spanyol, 4 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-tengah', name: 'Spanyol Panama', nativeName: 'Español', speakers: '4 juta', script: 'Latin', family: 'Roman', officialIn: ['Panama'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['panama', 'american-tengah'] } },
  { text: 'Belize — bahasa Inggris resmi, dituturkan luas berdampingan dengan Kriol Belize. Sapaan: hello (halo), thanks (terima kasih).', metadata: { region: 'american-tengah', name: 'Inggris Belize', nativeName: 'English', speakers: '250 ribu', script: 'Latin', family: 'Jermanik', officialIn: ['Belize'], greetings: { halo: 'hello', pagi: 'good morning', terimakasih: 'thanks' }, tags: ['belize', 'american-tengah'] } },
  { text: 'El Salvador — bahasa Spanyol, 6,5 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-tengah', name: 'Spanyol El Salvador', nativeName: 'Español', speakers: '6,5 juta', script: 'Latin', family: 'Roman', officialIn: ['El Salvador'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['el salvador', 'american-tengah'] } },
  { text: 'Kuba — bahasa Spanyol, 11 juta penutur. Sapaan: hola (halo), gracias (terima kasih).', metadata: { region: 'american-tengah', name: 'Spanyol Kuba', nativeName: 'Español', speakers: '11 juta', script: 'Latin', family: 'Roman', officialIn: ['Kuba'], greetings: { halo: 'hola', pagi: 'buenos días', terimakasih: 'gracias' }, tags: ['kuba', 'american-tengah'] } },
];

export const DATA = data;
