const data = [
  { text: 'Kazakhstan — bahasa Kazakh, 13 juta penutur. Aksara: Sirilik (transisi ke Latin). Sapaan: salem (halo), rakhmet (terima kasih).', metadata: { region: 'asian-tengah', name: 'Kazakh', nativeName: 'Қазақ тілі', speakers: '13 juta', script: 'Sirilik', family: 'Turkik', officialIn: ['Kazakhstan'], greetings: { halo: 'salem', pagi: 'qayyrly tañ', terimakasih: 'rakhmet' }, tags: ['kazakhstan', 'asia tengah'] } },
  { text: 'Uzbekistan — bahasa Uzbek, 34 juta penutur. Aksara: Latin. Sapaan: salom (halo), rahmat (terima kasih).', metadata: { region: 'asian-tengah', name: 'Uzbek', nativeName: 'Oʻzbek tili', speakers: '34 juta', script: 'Latin', family: 'Turkik', officialIn: ['Uzbekistan'], greetings: { halo: 'salom', pagi: 'xayrli tong', terimakasih: 'rahmat' }, tags: ['uzbekistan', 'asia tengah'] } },
  { text: 'Turkmenistan — bahasa Turkmen, 7 juta penutur. Aksara: Latin. Sapaan: salam (halo), sag boluñ (terima kasih).', metadata: { region: 'asian-tengah', name: 'Turkmen', nativeName: 'Türkmençe', speakers: '7 juta', script: 'Latin', family: 'Turkik', officialIn: ['Turkmenistan'], greetings: { halo: 'salam', pagi: 'ertiriñiz haýyrly bolsun', terimakasih: 'sag boluñ' }, tags: ['turkmenistan', 'asia tengah'] } },
  { text: 'Kirgistan — bahasa Kirgiz, 4,3 juta penutur. Aksara: Sirilik. Sapaan: salam (halo), rakhmat (terima kasih).', metadata: { region: 'asian-tengah', name: 'Kirgiz', nativeName: 'Кыргызча', speakers: '4,3 juta', script: 'Sirilik', family: 'Turkik', officialIn: ['Kirgistan'], greetings: { halo: 'salam', pagi: 'kutmanduu tañ', terimakasih: 'rakhmat' }, tags: ['kirgistan', 'asia tengah'] } },
  { text: 'Tajikistan — bahasa Tajik, 8,5 juta penutur. Aksara: Sirilik. Sapaan: salom (halo), rahmat (terima kasih).', metadata: { region: 'asian-tengah', name: 'Tajik', nativeName: 'Тоҷикӣ', speakers: '8,5 juta', script: 'Sirilik', family: 'Indo-Iran', officialIn: ['Tajikistan'], greetings: { halo: 'salom', pagi: 'subhaton ba khair', terimakasih: 'rahmat' }, tags: ['tajikistan', 'asia tengah'] } },
];

export const DATA = data;
