const data = [
  { text: 'China — bahasa Mandarin, sekitar 1,1 miliar penutur. Aksara: Hanzi (karakter Han). Sapaan: nǐ hǎo (halo), xièxiè (terima kasih).', metadata: { region: 'asian-timur', name: 'Mandarin', nativeName: '普通话', speakers: '1,1 miliar', script: 'Hanzi', family: 'Sino-Tibet', officialIn: ['China', 'Taiwan', 'Singapura'], greetings: { halo: 'nǐ hǎo', pagi: 'zǎoshang hǎo', terimakasih: 'xièxiè' }, tags: ['china', 'mandarin', 'asia timur'] } },
  { text: 'Jepang — bahasa Jepang, 125 juta penutur. Aksara: Kanji, Hiragana, Katakana. Sapaan: konnichiwa (halo), arigatou (terima kasih).', metadata: { region: 'asian-timur', name: 'Jepang', nativeName: '日本語', speakers: '125 juta', script: 'Kanji, Hiragana, Katakana', family: 'Japonik', officialIn: ['Jepang'], greetings: { halo: 'konnichiwa', pagi: 'ohayou gozaimasu', terimakasih: 'arigatou' }, tags: ['jepang', 'asia timur'] } },
  { text: 'Korea Selatan — bahasa Korea, 80 juta penutur. Aksara: Hangeul. Sapaan: annyeonghaseyo (halo), gamsahamnida (terima kasih).', metadata: { region: 'asian-timur', name: 'Korea', nativeName: '한국어', speakers: '80 juta', script: 'Hangeul', family: 'Koreanik', officialIn: ['Korea Selatan', 'Korea Utara'], greetings: { halo: 'annyeonghaseyo', pagi: 'joheun achim', terimakasih: 'gamsahamnida' }, tags: ['korea', 'asia timur'] } },
  { text: 'Mongolia — bahasa Mongolia, 5,7 juta penutur. Aksara: Sirilik Mongolia. Sapaan: sain baina uu (halo), өглөөний мэнд (selamat pagi).', metadata: { region: 'asian-timur', name: 'Mongolia', nativeName: 'Монгол хэл', speakers: '5,7 juta', script: 'Sirilik', family: 'Mongolik', officialIn: ['Mongolia'], greetings: { halo: 'sain baina uu', pagi: 'Өглөөний мэнд', terimakasih: 'bayarlalaa' }, tags: ['mongolia', 'asia timur'] } },
  { text: 'Taiwan — bahasa Hokkien Taiwan, 15 juta penutur, mendampingi Mandarin resmi. Sapaan: lí hó (halo), to-siā (terima kasih).', metadata: { region: 'asian-timur', name: 'Hokkien Taiwan', nativeName: '臺語', speakers: '15 juta', script: 'Hanzi', family: 'Sino-Tibet', officialIn: ['Taiwan'], greetings: { halo: 'lí hó', pagi: 'gau chá', terimakasih: 'to-siā' }, tags: ['taiwan', 'asia timur'] } },
  { text: 'Hong Kong — bahasa Kanton, 6,4 juta penutur. Aksara: Hanzi tradisional. Sapaan: néih hóu (halo), dòjeh (terima kasih).', metadata: { region: 'asian-timur', name: 'Kanton', nativeName: '廣東話', speakers: '6,4 juta', script: 'Hanzi tradisional', family: 'Sino-Tibet', officialIn: ['Hong Kong', 'Makau'], greetings: { halo: 'néih hóu', pagi: 'jóusàhn', terimakasih: 'dòjeh' }, tags: ['hong kong', 'asia timur'] } },
  { text: 'Tibet — bahasa Tibet, 6 juta penutur. Aksara: Aksara Tibet. Sapaan: tashi delek (halo/salam).', metadata: { region: 'asian-timur', name: 'Tibet', nativeName: 'བོད་སྐད', speakers: '6 juta', script: 'Aksara Tibet', family: 'Sino-Tibet', officialIn: ['Tibet'], greetings: { halo: 'tashi delek', pagi: 'tashi delek', terimakasih: 'thuk je che' }, tags: ['tibet', 'asia timur'] } },
];

export const DATA = data;
