const data = [
  { text: 'Arab Saudi — bahasa Arab, 300 juta penutur global. Aksara: Arab. Sapaan: assalamualaikum (halo), shukran (terima kasih).', metadata: { region: 'asian-barat', name: 'Arab', nativeName: 'العربية', speakers: '300 juta', script: 'Arab', family: 'Semitik', officialIn: ['Arab Saudi', 'Irak', 'Suriah', 'Yaman'], greetings: { halo: 'assalamualaikum', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['arab saudi', 'asia barat'] } },
  { text: 'Iran — bahasa Persia (Farsi), 70 juta penutur. Aksara: Arab-Persia. Sapaan: salaam (halo), mamnoon (terima kasih).', metadata: { region: 'asian-barat', name: 'Persia', nativeName: 'فارسی', speakers: '70 juta', script: 'Arab-Persia', family: 'Indo-Iran', officialIn: ['Iran'], greetings: { halo: 'salaam', pagi: 'sobh bekheir', terimakasih: 'mamnoon' }, tags: ['iran', 'asia barat'] } },
  { text: 'Turki — bahasa Turki, 80 juta penutur. Aksara: Latin. Sapaan: merhaba (halo), teşekkürler (terima kasih).', metadata: { region: 'asian-barat', name: 'Turki', nativeName: 'Türkçe', speakers: '80 juta', script: 'Latin', family: 'Turkik', officialIn: ['Turki'], greetings: { halo: 'merhaba', pagi: 'günaydın', terimakasih: 'teşekkürler' }, tags: ['turki', 'asia barat'] } },
  { text: 'Israel — bahasa Ibrani, 9 juta penutur. Aksara: Ibrani. Sapaan: shalom (halo), toda (terima kasih).', metadata: { region: 'asian-barat', name: 'Ibrani', nativeName: 'עברית', speakers: '9 juta', script: 'Ibrani', family: 'Semitik', officialIn: ['Israel'], greetings: { halo: 'shalom', pagi: 'boker tov', terimakasih: 'toda' }, tags: ['israel', 'asia barat'] } },
  { text: 'Yordania — bahasa Arab dialek Levant, digunakan luas di Yordania, Lebanon, Palestina. Sapaan: marhaba (halo), shukran (terima kasih).', metadata: { region: 'asian-barat', name: 'Arab Levant', nativeName: 'العربية الشامية', speakers: '20 juta', script: 'Arab', family: 'Semitik', officialIn: ['Yordania', 'Lebanon', 'Palestina'], greetings: { halo: 'marhaba', pagi: 'sabah al-khair', terimakasih: 'shukran' }, tags: ['yordania', 'asia barat'] } },
  { text: 'Kuwait/Teluk — bahasa Arab dialek Teluk, dipakai Kuwait, Qatar, Bahrain, UEA. Sapaan: marhaba (halo), mashkoor (terima kasih).', metadata: { region: 'asian-barat', name: 'Arab Teluk', nativeName: 'العربية الخليجية', speakers: '10 juta', script: 'Arab', family: 'Semitik', officialIn: ['Kuwait', 'Qatar', 'Bahrain', 'Uni Emirat Arab'], greetings: { halo: 'marhaba', pagi: 'sabah al-khair', terimakasih: 'mashkoor' }, tags: ['kuwait', 'asia barat'] } },
];

export const DATA = data;
