const data = [
  { text: 'Flat White — kopi susu dengan lapisan busa tipis, diyakini berasal dari Australia atau Selandia Baru dan populer di seluruh dunia.', metadata: { name: 'Flat White', country: 'Australia', region: 'osenia', type: 'minuman', tags: ['flat white', 'australia', 'kopi'] } },
  { text: 'Bir Australia (VB/XXXX) — Australia punya budaya bir santai yang kuat, dengan merek populer seperti Victoria Bitter dan XXXX.', metadata: { name: 'Bir Australia', country: 'Australia', region: 'osenia', type: 'minuman', tags: ['bir', 'australia'] } },
  { text: 'Wine Australia — wilayah seperti Barossa Valley terkenal sebagai penghasil wine berkualitas tinggi, terutama Shiraz.', metadata: { name: 'Wine Australia', country: 'Australia', region: 'osenia', type: 'minuman', tags: ['wine', 'australia'] } },
  { text: 'L&P (Lemon & Paeroa) — minuman bersoda rasa lemon khas Selandia Baru, dianggap minuman ikonik nasional.', metadata: { name: 'L&P', country: 'Selandia Baru', region: 'osenia', type: 'minuman', tags: ['lp', 'selandia baru'] } },
  { text: 'Wine Selandia Baru — terkenal dengan Sauvignon Blanc dari wilayah Marlborough yang jadi salah satu wine putih terbaik dunia.', metadata: { name: 'Wine Selandia Baru', country: 'Selandia Baru', region: 'osenia', type: 'minuman', tags: ['wine', 'selandia baru', 'marlborough'] } },
  { text: 'Kava — minuman tradisional dari akar tanaman kava yang punya efek menenangkan, penting dalam upacara adat Fiji dan Pasifik.', metadata: { name: 'Kava', country: 'Fiji', region: 'osenia', type: 'minuman', tags: ['kava', 'fiji'] } },
  { text: 'Air Kelapa Fiji — air kelapa segar langsung dari buahnya, minuman sehari-hari yang menyegarkan di kepulauan tropis Fiji.', metadata: { name: 'Air Kelapa Fiji', country: 'Fiji', region: 'osenia', type: 'minuman', tags: ['air kelapa', 'fiji'] } },
  { text: 'Kava Vanuatu — Vanuatu dikenal memiliki kava dengan kadar dan kualitas tinggi, diminum di nakamal (rumah komunitas) tradisional.', metadata: { name: 'Kava Vanuatu', country: 'Vanuatu', region: 'osenia', type: 'minuman', tags: ['kava', 'vanuatu'] } },
  { text: 'Otai — minuman segar dari campuran buah tropis dan santan khas Tonga dan Samoa, diminum dingin saat cuaca panas.', metadata: { name: 'Otai', country: 'Tonga', region: 'osenia', type: 'minuman', tags: ['otai', 'tonga'] } },
  { text: 'Kava Samoa — bagian penting dari upacara adat ava di Samoa, diminum dalam mangkuk kayu bersama komunitas.', metadata: { name: 'Kava Samoa', country: 'Samoa', region: 'osenia', type: 'minuman', tags: ['kava', 'samoa'] } },
  { text: 'Air Kelapa Papua Nugini — minuman alami dari kelapa muda, sumber hidrasi utama di banyak desa pesisir Papua Nugini.', metadata: { name: 'Air Kelapa Papua Nugini', country: 'Papua New Guinea', region: 'osenia', type: 'minuman', tags: ['air kelapa', 'papua new guinea'] } },
  { text: 'Kopi Papua Nugini — kopi arabika dataran tinggi dengan cita rasa kaya, menjadi salah satu komoditas ekspor penting negara ini.', metadata: { name: 'Kopi Papua Nugini', country: 'Papua New Guinea', region: 'osenia', type: 'minuman', tags: ['kopi', 'papua new guinea'] } },
  { text: 'Bir Kepulauan Solomon (SolBrew) — merek bir lokal populer di Kepulauan Solomon, sering dinikmati saat berkumpul santai.', metadata: { name: 'SolBrew', country: 'Kepulauan Solomon', region: 'osenia', type: 'minuman', tags: ['solbrew', 'kepulauan solomon'] } },
  { text: 'Jus Pandanus — minuman dari buah pandan khas beberapa pulau Pasifik seperti Kiribati dan Kepulauan Marshall, rasa manis unik.', metadata: { name: 'Jus Pandanus', country: 'Kepulauan Marshall', region: 'osenia', type: 'minuman', tags: ['pandanus', 'kepulauan marshall'] } },
  { text: 'Billy Tea — teh yang diseduh dalam kaleng logam (billy can) di atas api unggun, tradisi khas kehidupan luar (outback) Australia.', metadata: { name: 'Billy Tea', country: 'Australia', region: 'osenia', type: 'minuman', tags: ['billy tea', 'australia'] } },
  { text: 'Anggur Selandia Baru Pinot Noir — wilayah Central Otago terkenal sebagai penghasil Pinot Noir berkualitas tinggi di belahan bumi selatan.', metadata: { name: 'Pinot Noir Selandia Baru', country: 'Selandia Baru', region: 'osenia', type: 'minuman', tags: ['pinot noir', 'selandia baru'] } },
];

export const DATA = data;
