const data = [
  { text: 'Nelson Mandela — pemimpin Afrika Selatan, presiden kulit hitam pertama, tokoh utama perjuangan anti-apartheid. Lahir tahun 1918 di Afrika Selatan.', metadata: { name: 'Nelson Mandela', field: 'pemimpin', knownFor: 'anti-apartheid, presiden Afrika Selatan', country: 'Afrika Selatan', born: '1918', tags: ['mandela', 'apartheid'] } },
  { text: 'Winston Churchill — pemimpin Inggris, Perdana Menteri yang memimpin negara itu selama Perang Dunia II. Lahir tahun 1874 di Inggris.', metadata: { name: 'Winston Churchill', field: 'pemimpin', knownFor: 'PM Inggris Perang Dunia II', country: 'Inggris', born: '1874', tags: ['churchill', 'perang dunia ii'] } },
  { text: 'Abraham Lincoln — presiden ke-16 Amerika Serikat, memimpin negara melalui Perang Saudara dan menghapus perbudakan. Lahir tahun 1809 di Amerika Serikat.', metadata: { name: 'Abraham Lincoln', field: 'pemimpin', knownFor: 'presiden AS, hapus perbudakan', country: 'Amerika Serikat', born: '1809', tags: ['lincoln', 'perbudakan'] } },
  { text: 'Angela Merkel — kanselir wanita pertama Jerman, memimpin negara itu selama enam belas tahun. Lahir tahun 1954 di Jerman.', metadata: { name: 'Angela Merkel', field: 'pemimpin', knownFor: 'kanselir wanita pertama Jerman', country: 'Jerman', born: '1954', tags: ['merkel', 'jerman'] } },
  { text: 'Ratu Elizabeth II — raja/ratu Inggris dengan masa pemerintahan terlama dalam sejarah monarki Inggris. Lahir tahun 1926 di Inggris.', metadata: { name: 'Ratu Elizabeth II', field: 'pemimpin', knownFor: 'monarki Inggris terlama', country: 'Inggris', born: '1926', tags: ['elizabeth ii', 'monarki'] } },
  { text: 'Jawaharlal Nehru — perdana menteri pertama India, memimpin negara itu pasca kemerdekaan dari Inggris. Lahir tahun 1889 di India.', metadata: { name: 'Jawaharlal Nehru', field: 'pemimpin', knownFor: 'PM pertama India', country: 'India', born: '1889', tags: ['nehru', 'india'] } },
  { text: 'Kwame Nkrumah — presiden pertama Ghana, tokoh penting gerakan pan-Afrikanisme dan dekolonisasi Afrika. Lahir tahun 1909 di Ghana.', metadata: { name: 'Kwame Nkrumah', field: 'pemimpin', knownFor: 'presiden pertama Ghana, pan-Afrikanisme', country: 'Ghana', born: '1909', tags: ['nkrumah', 'ghana'] } },
  { text: 'Lee Kuan Yew — perdana menteri pendiri Singapura, arsitek transformasi negara itu menjadi pusat ekonomi dunia. Lahir tahun 1923 di Singapura.', metadata: { name: 'Lee Kuan Yew', field: 'pemimpin', knownFor: 'PM pendiri Singapura', country: 'Singapura', born: '1923', tags: ['lee kuan yew', 'singapura'] } },
  { text: 'Simon Bolivar — pemimpin revolusi Amerika Selatan yang membebaskan beberapa negara dari kekuasaan kolonial Spanyol. Lahir tahun 1783 di Venezuela.', metadata: { name: 'Simon Bolivar', field: 'pemimpin', knownFor: 'pembebas Amerika Selatan', country: 'Venezuela', born: '1783', tags: ['bolivar', 'amerika selatan'] } },
  { text: 'Otto von Bismarck — negarawan Jerman yang memimpin unifikasi negara-negara Jerman menjadi satu kekaisaran pada 1871. Lahir tahun 1815 di Jerman.', metadata: { name: 'Otto von Bismarck', field: 'pemimpin', knownFor: 'unifikasi Jerman', country: 'Jerman', born: '1815', tags: ['bismarck', 'unifikasi jerman'] } },
  { text: 'Golda Meir — perdana menteri wanita pertama Israel, memimpin negara itu pada masa-masa penting sejarahnya. Lahir tahun 1898 di Israel.', metadata: { name: 'Golda Meir', field: 'pemimpin', knownFor: 'PM wanita pertama Israel', country: 'Israel', born: '1898', tags: ['golda meir', 'israel'] } },
  { text: 'Justin Trudeau — perdana menteri Kanada yang dikenal dengan kebijakan progresif dan keterbukaan terhadap imigrasi. Lahir tahun 1971 di Kanada.', metadata: { name: 'Justin Trudeau', field: 'pemimpin', knownFor: 'PM Kanada', country: 'Kanada', born: '1971', tags: ['trudeau', 'kanada'] } },
  { text: 'Jacinda Ardern — perdana menteri Selandia Baru, dikenal atas kepemimpinan empatik saat krisis nasional. Lahir tahun 1980 di Selandia Baru.', metadata: { name: 'Jacinda Ardern', field: 'pemimpin', knownFor: 'PM Selandia Baru', country: 'Selandia Baru', born: '1980', tags: ['ardern', 'selandia baru'] } },
  { text: 'Sun Yat-sen — bapak pendiri Republik Tiongkok, tokoh sentral revolusi yang mengakhiri era kekaisaran Tiongkok. Lahir tahun 1866 di Tiongkok.', metadata: { name: 'Sun Yat-sen', field: 'pemimpin', knownFor: 'bapak pendiri Republik Tiongkok', country: 'Tiongkok', born: '1866', tags: ['sun yat-sen', 'tiongkok'] } },
  { text: 'Jomo Kenyatta — presiden pertama Kenya, pemimpin gerakan kemerdekaan negara itu dari penjajahan Inggris. Lahir tahun 1897 di Kenya.', metadata: { name: 'Jomo Kenyatta', field: 'pemimpin', knownFor: 'presiden pertama Kenya', country: 'Kenya', born: '1897', tags: ['kenyatta', 'kenya'] } },
];

export const DATA = data;
