const data = [
  { text: 'Marco Polo — penjelajah Italia yang menempuh Jalur Sutra hingga Tiongkok pada abad ke-13, catatannya membuka mata Eropa pada Asia. Lahir tahun 1254 di Italia.', metadata: { name: 'Marco Polo', field: 'penjelajah', knownFor: 'perjalanan Jalur Sutra ke Tiongkok', country: 'Italia', born: '1254', tags: ['marco polo', 'jalur sutra'] } },
  { text: 'Christopher Columbus — penjelajah yang berlayar melintasi Atlantik pada 1492 dan mencapai benua Amerika. Lahir tahun 1451 di Italia.', metadata: { name: 'Christopher Columbus', field: 'penjelajah', knownFor: 'pelayaran ke Amerika 1492', country: 'Italia', born: '1451', tags: ['columbus', 'amerika'] } },
  { text: 'Ferdinand Magellan — penjelajah Portugal yang memimpin ekspedisi pertama mengelilingi dunia lewat laut. Lahir tahun 1480 di Portugal.', metadata: { name: 'Ferdinand Magellan', field: 'penjelajah', knownFor: 'ekspedisi keliling dunia pertama', country: 'Portugal', born: '1480', tags: ['magellan', 'keliling dunia'] } },
  { text: 'Vasco da Gama — penjelajah Portugal yang pertama menemukan jalur laut langsung dari Eropa ke India. Lahir tahun 1460 di Portugal.', metadata: { name: 'Vasco da Gama', field: 'penjelajah', knownFor: 'jalur laut Eropa-India', country: 'Portugal', born: '1460', tags: ['vasco da gama', 'india'] } },
  { text: 'James Cook — penjelajah Inggris yang memetakan Pasifik, termasuk pantai Australia dan Selandia Baru. Lahir tahun 1728 di Inggris.', metadata: { name: 'James Cook', field: 'penjelajah', knownFor: 'pemetaan Pasifik', country: 'Inggris', born: '1728', tags: ['james cook', 'pasifik'] } },
  { text: 'Ibnu Battuta — penjelajah Maroko abad ke-14 yang menempuh puluhan ribu kilometer melintasi dunia Islam, Asia, dan Afrika. Lahir tahun 1304 di Maroko.', metadata: { name: 'Ibnu Battuta', field: 'penjelajah', knownFor: 'perjalanan lintas dunia Islam', country: 'Maroko', born: '1304', tags: ['ibnu battuta', 'maroko'] } },
  { text: 'Zheng He — laksamana dan penjelajah Tiongkok era Dinasti Ming yang memimpin armada besar mengarungi Samudra Hindia. Lahir tahun 1371 di Tiongkok.', metadata: { name: 'Zheng He', field: 'penjelajah', knownFor: 'ekspedisi armada Ming', country: 'Tiongkok', born: '1371', tags: ['zheng he', 'ming'] } },
  { text: 'Amerigo Vespucci — penjelajah dan kartografer Italia yang namanya menjadi asal-usul nama benua Amerika. Lahir tahun 1454 di Italia.', metadata: { name: 'Amerigo Vespucci', field: 'penjelajah', knownFor: 'asal nama benua Amerika', country: 'Italia', born: '1454', tags: ['amerigo vespucci', 'amerika'] } },
  { text: 'Roald Amundsen — penjelajah Norwegia, orang pertama yang mencapai Kutub Selatan pada 1911. Lahir tahun 1872 di Norwegia.', metadata: { name: 'Roald Amundsen', field: 'penjelajah', knownFor: 'orang pertama capai Kutub Selatan', country: 'Norwegia', born: '1872', tags: ['amundsen', 'kutub selatan'] } },
  { text: 'Edmund Hillary — pendaki Selandia Baru yang bersama Tenzing Norgay menjadi orang pertama mencapai puncak Everest 1953. Lahir tahun 1919 di Selandia Baru.', metadata: { name: 'Edmund Hillary', field: 'penjelajah', knownFor: 'pendaki pertama Everest', country: 'Selandia Baru', born: '1919', tags: ['hillary', 'everest'] } },
  { text: 'Tenzing Norgay — pendaki Sherpa Nepal yang bersama Edmund Hillary pertama kali mencapai puncak Gunung Everest. Lahir tahun 1914 di Nepal.', metadata: { name: 'Tenzing Norgay', field: 'penjelajah', knownFor: 'pendaki pertama Everest', country: 'Nepal', born: '1914', tags: ['tenzing norgay', 'everest'] } },
  { text: 'Neil Armstrong — astronot Amerika Serikat, manusia pertama yang menginjakkan kaki di Bulan pada 1969. Lahir tahun 1930 di Amerika Serikat.', metadata: { name: 'Neil Armstrong', field: 'penjelajah', knownFor: 'manusia pertama di Bulan', country: 'Amerika Serikat', born: '1930', tags: ['neil armstrong', 'bulan'] } },
  { text: 'Yuri Gagarin — kosmonaut Uni Soviet, manusia pertama yang terbang ke luar angkasa pada 1961. Lahir tahun 1934 di Rusia.', metadata: { name: 'Yuri Gagarin', field: 'penjelajah', knownFor: 'manusia pertama ke luar angkasa', country: 'Rusia', born: '1934', tags: ['gagarin', 'luar angkasa'] } },
  { text: 'Jacques Cousteau — penjelajah dan oseanograf Prancis yang mempopulerkan eksplorasi bawah laut lewat film dan alat selam. Lahir tahun 1910 di Prancis.', metadata: { name: 'Jacques Cousteau', field: 'penjelajah', knownFor: 'eksplorasi bawah laut', country: 'Prancis', born: '1910', tags: ['cousteau', 'laut'] } },
  { text: 'Ernest Shackleton — penjelajah Inggris-Irlandia terkenal karena ekspedisi Antarktika yang penuh keteguhan bertahan hidup. Lahir tahun 1874 di Inggris.', metadata: { name: 'Ernest Shackleton', field: 'penjelajah', knownFor: 'ekspedisi Antarktika', country: 'Inggris', born: '1874', tags: ['shackleton', 'antarktika'] } },
];

export const DATA = data;
