const data = [
  { text: 'Sapaan Mesir — jabat tangan hangat, sering berlangsung lebih lama dibanding budaya Barat, disertai tanya kabar keluarga.', metadata: { name: 'Sapaan Mesir', country: 'Mesir', region: 'afrika', type: 'sapaan', tags: ['mesir', 'jabat tangan'] } },
  { text: 'Tip di Mesir — baksheesh (tip kecil) diharapkan untuk banyak layanan, dari porter hingga penjaga situs wisata.', metadata: { name: 'Tip Mesir', country: 'Mesir', region: 'afrika', type: 'tip', tags: ['mesir', 'baksheesh'] } },
  { text: 'Tabu di Mesir — menunjukkan telapak kaki ke arah orang lain dianggap tidak sopan, mirip kebiasaan di banyak negara Timur Tengah.', metadata: { name: 'Tabu Kaki Mesir', country: 'Mesir', region: 'afrika', type: 'tabu', tags: ['mesir', 'kaki'] } },
  { text: 'Sapaan Maroko — jabat tangan lalu menyentuh dada sebagai tanda ketulusan; pria dan wanita yang belum kenal dekat biasanya tidak berjabat tangan.', metadata: { name: 'Sapaan Maroko', country: 'Maroko', region: 'afrika', type: 'sapaan', tags: ['maroko', 'jabat tangan'] } },
  { text: 'Tip di Maroko — tip kecil diharapkan di kafe, restoran, dan untuk pemandu wisata sebagai bagian dari kebiasaan sehari-hari.', metadata: { name: 'Tip Maroko', country: 'Maroko', region: 'afrika', type: 'tip', tags: ['maroko', 'tip'] } },
  { text: 'Tabu di Maroko — makan atau memberi sesuatu dengan tangan kiri dianggap kurang sopan menurut adat setempat.', metadata: { name: 'Tabu Tangan Kiri Maroko', country: 'Maroko', region: 'afrika', type: 'tabu', tags: ['maroko', 'tangan kiri'] } },
  { text: 'Sapaan Nigeria — menyapa orang yang lebih tua dengan sedikit membungkuk atau berlutut adalah tanda hormat di banyak suku.', metadata: { name: 'Sapaan Nigeria', country: 'Nigeria', region: 'afrika', type: 'sapaan', tags: ['nigeria', 'hormat'] } },
  { text: 'Tabu di Nigeria — menggunakan tangan kiri untuk memberi atau menerima barang dianggap tidak sopan di banyak komunitas.', metadata: { name: 'Tabu Tangan Kiri Nigeria', country: 'Nigeria', region: 'afrika', type: 'tabu', tags: ['nigeria', 'tangan kiri'] } },
  { text: 'Sapaan Afrika Selatan — jabat tangan hangat; di kalangan Zulu, jabat tangan tiga tahap dengan gerakan khas cukup umum.', metadata: { name: 'Sapaan Afrika Selatan', country: 'Afrika Selatan', region: 'afrika', type: 'sapaan', tags: ['afrika selatan', 'jabat tangan'] } },
  { text: 'Tip di Afrika Selatan — tip sekitar 10-15% lazim di restoran, dianggap bagian penting dari penghasilan pelayan.', metadata: { name: 'Tip Afrika Selatan', country: 'Afrika Selatan', region: 'afrika', type: 'tip', tags: ['afrika selatan', 'tip'] } },
  { text: 'Sapaan Kenya — jabat tangan lembut dan berlangsung agak lama; kontak mata langsung dengan orang yang lebih tua kadang dihindari sebagai tanda hormat.', metadata: { name: 'Sapaan Kenya', country: 'Kenya', region: 'afrika', type: 'sapaan', tags: ['kenya', 'jabat tangan'] } },
  { text: 'Tabu di Kenya — menunjuk dengan jari telunjuk ke arah orang dianggap kasar di beberapa komunitas lokal.', metadata: { name: 'Tabu Menunjuk Kenya', country: 'Kenya', region: 'afrika', type: 'tabu', tags: ['kenya', 'menunjuk'] } },
  { text: 'Sapaan Etiopia — jabat tangan disertai sedikit membungkuk; teman dekat sesama jenis saling mencium pipi tiga kali.', metadata: { name: 'Sapaan Etiopia', country: 'Etiopia', region: 'afrika', type: 'sapaan', tags: ['etiopia', 'cium pipi'] } },
  { text: 'Tabu di Etiopia — menolak tawaran kopi tradisional (buna) dianggap kurang sopan karena upacara kopi adalah simbol keramahan.', metadata: { name: 'Tabu Menolak Kopi Etiopia', country: 'Etiopia', region: 'afrika', type: 'tabu', tags: ['etiopia', 'kopi'] } },
  { text: 'Sapaan Ghana — jabat tangan disertai jentikan jari di akhir (versi tradisional Akan) sebagai tanda keakraban.', metadata: { name: 'Sapaan Ghana', country: 'Ghana', region: 'afrika', type: 'sapaan', tags: ['ghana', 'jabat tangan'] } },
  { text: 'Tip di Ghana — tip kecil dihargai di restoran kota besar, meski belum menjadi kebiasaan wajib secara umum.', metadata: { name: 'Tip Ghana', country: 'Ghana', region: 'afrika', type: 'tip', tags: ['ghana', 'tip'] } },
  { text: 'Sapaan Tanzania — salam "Jambo" atau "Hujambo" umum diucapkan pada wisatawan, disertai jabat tangan ramah.', metadata: { name: 'Sapaan Tanzania', country: 'Tanzania', region: 'afrika', type: 'sapaan', tags: ['tanzania', 'jambo'] } },
  { text: 'Tabu di Tanzania — memotret orang tanpa izin, terutama suku Maasai, dianggap tidak sopan dan bisa memicu konflik.', metadata: { name: 'Tabu Memotret Tanpa Izin Tanzania', country: 'Tanzania', region: 'afrika', type: 'tabu', tags: ['tanzania', 'memotret'] } },
  { text: 'Sapaan Aljazair — jabat tangan hangat, sering disertai meletakkan tangan di dada setelahnya sebagai tanda ketulusan.', metadata: { name: 'Sapaan Aljazair', country: 'Aljazair', region: 'afrika', type: 'sapaan', tags: ['aljazair', 'jabat tangan'] } },
  { text: 'Tabu di Tunisia — menunjukkan telapak kaki atau menyilangkan kaki dengan sol menghadap orang lain dianggap tidak sopan.', metadata: { name: 'Tabu Kaki Tunisia', country: 'Tunisia', region: 'afrika', type: 'tabu', tags: ['tunisia', 'kaki'] } },
];

export const DATA = data;
