const data = [
  { text: 'Sapaan Arab Saudi — "As-salamu alaykum" diucapkan hangat, jabat tangan lembut antar sesama pria; pria dan wanita yang bukan mahram umumnya tidak berjabat tangan.', metadata: { name: 'Sapaan Arab Saudi', country: 'Arab Saudi', region: 'timur-tengah', type: 'sapaan', tags: ['arab saudi', 'salam'] } },
  { text: 'Tabu di Arab Saudi — menunjukkan telapak kaki atau menyilangkan kaki ke arah orang lain dianggap sangat tidak sopan.', metadata: { name: 'Tabu Kaki Arab Saudi', country: 'Arab Saudi', region: 'timur-tengah', type: 'tabu', tags: ['arab saudi', 'kaki'] } },
  { text: 'Tip di Arab Saudi — tip 10% mulai lazim di restoran kota besar meski belum wajib, dianggap apresiasi tambahan.', metadata: { name: 'Tip Arab Saudi', country: 'Arab Saudi', region: 'timur-tengah', type: 'tip', tags: ['arab saudi', 'tip'] } },
  { text: 'Sapaan Uni Emirat Arab — jabat tangan hangat disertai "As-salamu alaykum"; basa-basi menanyakan kabar keluarga dianggap sopan sebelum membahas bisnis.', metadata: { name: 'Sapaan UEA', country: 'Uni Emirat Arab', region: 'timur-tengah', type: 'sapaan', tags: ['uni emirat arab', 'salam'] } },
  { text: 'Tip di Uni Emirat Arab — service charge sering sudah termasuk tagihan, tip tambahan 10% tetap dihargai.', metadata: { name: 'Tip UEA', country: 'Uni Emirat Arab', region: 'timur-tengah', type: 'tip', tags: ['uni emirat arab', 'tip'] } },
  { text: 'Tabu di Uni Emirat Arab — makan atau minum di depan umum pada siang hari selama Ramadan dianggap tidak sopan bagi non-Muslim sekalipun.', metadata: { name: 'Tabu Ramadan UEA', country: 'Uni Emirat Arab', region: 'timur-tengah', type: 'tabu', tags: ['uni emirat arab', 'ramadan'] } },
  { text: 'Sapaan Turki — jabat tangan hangat, orang yang lebih muda kadang mencium tangan orang tua lalu menempelkannya ke dahi sebagai tanda hormat.', metadata: { name: 'Sapaan Turki', country: 'Turki', region: 'timur-tengah', type: 'sapaan', tags: ['turki', 'jabat tangan'] } },
  { text: 'Tip di Turki — tip sekitar 5-10% lazim di restoran, biasanya diberikan tunai terpisah dari tagihan.', metadata: { name: 'Tip Turki', country: 'Turki', region: 'timur-tengah', type: 'tip', tags: ['turki', 'tip'] } },
  { text: 'Tabu di Turki — menolak tawaran teh dari tuan rumah dianggap kurang sopan, karena menyuguh teh adalah simbol keramahan.', metadata: { name: 'Tabu Menolak Teh Turki', country: 'Turki', region: 'timur-tengah', type: 'tabu', tags: ['turki', 'teh'] } },
  { text: 'Sapaan Iran — jabat tangan hangat antar sesama jenis; taarof (basa-basi sopan menawarkan sesuatu berulang kali) adalah tradisi penting.', metadata: { name: 'Sapaan Iran', country: 'Iran', region: 'timur-tengah', type: 'sapaan', tags: ['iran', 'taarof'] } },
  { text: 'Tabu di Iran — menunjukkan telapak kaki atau punggung ke arah orang lain dianggap tidak sopan dalam pertemuan formal.', metadata: { name: 'Tabu Kaki Iran', country: 'Iran', region: 'timur-tengah', type: 'tabu', tags: ['iran', 'kaki'] } },
  { text: 'Sapaan Yordania — jabat tangan hangat disertai tangan kanan menyentuh dada, sering diikuti pertanyaan basa-basi tentang kesehatan.', metadata: { name: 'Sapaan Yordania', country: 'Yordania', region: 'timur-tengah', type: 'sapaan', tags: ['yordania', 'jabat tangan'] } },
  { text: 'Tip di Yordania — tip sekitar 10% lazim di restoran turis, sering sudah tertulis sebagai service charge di tagihan.', metadata: { name: 'Tip Yordania', country: 'Yordania', region: 'timur-tengah', type: 'tip', tags: ['yordania', 'tip'] } },
  { text: 'Sapaan Lebanon — cium pipi tiga kali (bergantian kanan-kiri-kanan) umum di antara teman dan keluarga.', metadata: { name: 'Sapaan Lebanon', country: 'Lebanon', region: 'timur-tengah', type: 'sapaan', tags: ['lebanon', 'cium pipi'] } },
  { text: 'Tabu di Lebanon — membicarakan politik atau agama pada perkenalan pertama sebaiknya dihindari karena bisa jadi topik sensitif.', metadata: { name: 'Tabu Topik Sensitif Lebanon', country: 'Lebanon', region: 'timur-tengah', type: 'tabu', tags: ['lebanon', 'politik'] } },
  { text: 'Sapaan Qatar — jabat tangan lembut dan hangat antar pria; salam formal "As-salamu alaykum" umum digunakan.', metadata: { name: 'Sapaan Qatar', country: 'Qatar', region: 'timur-tengah', type: 'sapaan', tags: ['qatar', 'salam'] } },
  { text: 'Tabu di Qatar — berpakaian terlalu terbuka di tempat umum dianggap tidak sopan dan bisa melanggar norma setempat.', metadata: { name: 'Tabu Berpakaian Qatar', country: 'Qatar', region: 'timur-tengah', type: 'tabu', tags: ['qatar', 'berpakaian'] } },
  { text: 'Sapaan Kuwait — jabat tangan hangat antar sesama jenis, sering disertai obrolan ringan tentang keluarga sebelum ke topik utama.', metadata: { name: 'Sapaan Kuwait', country: 'Kuwait', region: 'timur-tengah', type: 'sapaan', tags: ['kuwait', 'jabat tangan'] } },
  { text: 'Tip di Kuwait — tip 10% mulai umum di restoran kota besar, meski tradisi ini relatif baru dibanding negara Teluk lain.', metadata: { name: 'Tip Kuwait', country: 'Kuwait', region: 'timur-tengah', type: 'tip', tags: ['kuwait', 'tip'] } },
  { text: 'Sapaan Oman — jabat tangan lembut, kadang diikuti sentuhan hidung ringan (khashm) sebagai sapaan tradisional yang lebih akrab.', metadata: { name: 'Sapaan Oman', country: 'Oman', region: 'timur-tengah', type: 'sapaan', tags: ['oman', 'khashm'] } },
];

export const DATA = data;
