const data = [
  { text: 'Sapaan Australia — jabat tangan santai dan ramah, sapaan informal seperti "g\'day" umum digunakan sehari-hari.', metadata: { name: 'Sapaan Australia', country: 'Australia', region: 'osenia', type: 'sapaan', tags: ['australia', 'jabat tangan'] } },
  { text: 'Tip di Australia — tip tidak wajib karena upah pekerja sudah diatur layak; tip kecil hanya untuk pelayanan istimewa.', metadata: { name: 'Tip Australia', country: 'Australia', region: 'osenia', type: 'tip', tags: ['australia', 'tip'] } },
  { text: 'Tabu di Australia — memotong antrean atau bersikap terlalu formal/kaku bisa dianggap aneh; budaya lokal cenderung santai dan egaliter.', metadata: { name: 'Tabu Formalitas Berlebih Australia', country: 'Australia', region: 'osenia', type: 'tabu', tags: ['australia', 'formalitas'] } },
  { text: 'Sapaan Selandia Baru — jabat tangan hangat; dalam budaya Maori, hongi (menempelkan hidung dan dahi) adalah sapaan tradisional khusus.', metadata: { name: 'Sapaan Selandia Baru', country: 'Selandia Baru', region: 'osenia', type: 'sapaan', tags: ['selandia baru', 'hongi'] } },
  { text: 'Tip di Selandia Baru — tip tidak menjadi kebiasaan umum, meski belakangan mulai muncul di beberapa restoran kota besar.', metadata: { name: 'Tip Selandia Baru', country: 'Selandia Baru', region: 'osenia', type: 'tip', tags: ['selandia baru', 'tip'] } },
  { text: 'Tabu di Selandia Baru — duduk di atas meja atau menaruh barang di atas kepala orang lain dianggap tidak sopan menurut adat Maori.', metadata: { name: 'Tabu Kepala Selandia Baru', country: 'Selandia Baru', region: 'osenia', type: 'tabu', tags: ['selandia baru', 'kepala'] } },
  { text: 'Sapaan Fiji — sapaan "Bula" diucapkan hangat dengan senyum lebar, sering disertai jabat tangan santai.', metadata: { name: 'Sapaan Fiji', country: 'Fiji', region: 'osenia', type: 'sapaan', tags: ['fiji', 'bula'] } },
  { text: 'Tabu di Fiji — menyentuh kepala orang lain, termasuk anak-anak, dianggap tidak sopan karena kepala dianggap bagian tubuh yang suci.', metadata: { name: 'Tabu Kepala Fiji', country: 'Fiji', region: 'osenia', type: 'tabu', tags: ['fiji', 'kepala'] } },
  { text: 'Sapaan Papua Nugini — jabat tangan hangat; di banyak komunitas, menyapa dengan menyebut hubungan kekerabatan dianggap sopan.', metadata: { name: 'Sapaan Papua Nugini', country: 'Papua New Guinea', region: 'osenia', type: 'sapaan', tags: ['papua new guinea', 'jabat tangan'] } },
  { text: 'Sapaan Samoa — sapaan "Talofa" hangat, sering disertai senyum dan sedikit anggukan kepala sebagai tanda hormat.', metadata: { name: 'Sapaan Samoa', country: 'Samoa', region: 'osenia', type: 'sapaan', tags: ['samoa', 'talofa'] } },
  { text: 'Tabu di Samoa — berdiri saat orang lain duduk sedang berbicara penting dianggap kurang sopan dalam pertemuan adat (fono).', metadata: { name: 'Tabu Berdiri Samoa', country: 'Samoa', region: 'osenia', type: 'tabu', tags: ['samoa', 'fono'] } },
  { text: 'Sapaan Tonga — jabat tangan lembut, sering disertai sedikit menunduk sebagai tanda hormat pada bangsawan atau tetua.', metadata: { name: 'Sapaan Tonga', country: 'Tonga', region: 'osenia', type: 'sapaan', tags: ['tonga', 'jabat tangan'] } },
  { text: 'Tabu di Tonga — mengenakan topi di dalam ruangan resmi atau di hadapan raja dianggap tidak sopan.', metadata: { name: 'Tabu Topi Tonga', country: 'Tonga', region: 'osenia', type: 'tabu', tags: ['tonga', 'topi'] } },
  { text: 'Sapaan Kepulauan Solomon — jabat tangan santai, senyum ramah, dan pertanyaan basa-basi tentang keluarga umum dipakai.', metadata: { name: 'Sapaan Kepulauan Solomon', country: 'Kepulauan Solomon', region: 'osenia', type: 'sapaan', tags: ['kepulauan solomon', 'jabat tangan'] } },
  { text: 'Sapaan Vanuatu — jabat tangan hangat; menyapa dengan menyebut nama desa/klan dianggap ramah dan sopan.', metadata: { name: 'Sapaan Vanuatu', country: 'Vanuatu', region: 'osenia', type: 'sapaan', tags: ['vanuatu', 'jabat tangan'] } },
  { text: 'Tabu di Vanuatu — memasuki area yang ditandai sebagai tanah adat (tabu/nasara) tanpa izin dianggap pelanggaran serius.', metadata: { name: 'Tabu Tanah Adat Vanuatu', country: 'Vanuatu', region: 'osenia', type: 'tabu', tags: ['vanuatu', 'tanah adat'] } },
  { text: 'Sapaan Kepulauan Marshall — jabat tangan lembut disertai senyum; menanyakan kabar keluarga dianggap ramah dan lazim.', metadata: { name: 'Sapaan Kepulauan Marshall', country: 'Kepulauan Marshall', region: 'osenia', type: 'sapaan', tags: ['kepulauan marshall', 'jabat tangan'] } },
  { text: 'Tip di Fiji — tip tidak menjadi tradisi lokal, meski beberapa resor besar mulai menerapkan service charge tambahan.', metadata: { name: 'Tip Fiji', country: 'Fiji', region: 'osenia', type: 'tip', tags: ['fiji', 'tip'] } },
  { text: 'Tabu di Papua Nugini — menunjuk langsung dengan jari ke orang lain saat berbicara dianggap kasar di banyak komunitas.', metadata: { name: 'Tabu Menunjuk Papua Nugini', country: 'Papua New Guinea', region: 'osenia', type: 'tabu', tags: ['papua new guinea', 'menunjuk'] } },
  { text: 'Sapaan Australia Adat — dalam budaya Aborigin, kontak mata langsung dengan tetua kadang dihindari sebagai tanda hormat, berbeda dari kebiasaan Barat.', metadata: { name: 'Sapaan Aborigin', country: 'Australia', region: 'osenia', type: 'sapaan', tags: ['australia', 'aborigin'] } },
];

export const DATA = data;
