export default [
    ['Mari kita mulai dengan satu fakta yang layak diingat hari ini.', 'Let us begin with one fact worth remembering today.'],
    ['Kita buka siaran dengan hal yang sederhana, tapi tajam.', 'We open this broadcast with something simple, but sharp.'],
    ['Tentang ', 'About '],
    ['Ibu kotanya ', 'Its capital is '],
    ['Populasinya sekitar ', 'Its population is about '],
    ['Populasinya tercatat sekitar ', 'Its population is recorded at about '],
    ['Mata uangnya ', 'Its currency is '],
    ['Bahasanya ', 'Its languages are '],
    ['Sistem pemerintahannya ', 'Its government system is '],
    ['Negara dengan ekonomi paling kompetitif di dunia.', 'One of the most competitive economies in the world.'],
    ['Pusat perdagangan, teknologi, dan inovasi.', 'A hub of trade, technology, and innovation.'],
    ['Rumah bagi ', 'Home to '],
    ['Siaran selesai. Yang penting ikut dalam keputusan hari ini.', 'That concludes this broadcast. What matters is what shapes today\'s decisions.'],
    ['Cukup satu yang menempel. Sisanya bisa nanti.', 'One sticky idea is enough. The rest can wait.'],

    ['Selamat pagi', 'Good morning'], ['Selamat siang', 'Good afternoon'], ['Selamat sore', 'Good evening'], ['Selamat malam', 'Good evening'],
    ['Hari ini ', 'Today is '],
    ['Masih segar di ingatan, kemarin kita membahas ', 'Still fresh in memory, yesterday we discussed '],
    ['. Hari ini kita lanjut melangkah.', '. Today we keep moving forward.'],
    ['Kemarin kita sempat menyinggung ', 'Yesterday we briefly touched on '],
    ['. Hari ini kita lanjut.', '. Today we continue.'],
    ['Dari catatan pengembangan: ', 'From the development notes: '],
    ['Dari catatan pengembangan.', 'From the development notes.'],
    ['Pustaka dataries belum terhubung di halaman ini.', 'The dataries library is not connected on this page yet.'],
    ['Kisah yang kuat. Apakah pelajarannya masih relevan hari ini?', 'A powerful story. Is the lesson still relevant today?'],
    ['Kisah yang kuat. Tapi konteks zamannya berbeda, apakah pelajarannya masih relevan?', 'A powerful story. But the era is different; is the lesson still relevant?'],
    ['Justru itu ujiannya. Prinsipnya bertahan, caranya yang berubah.', 'That is exactly the test. Principles endure; methods change.'],
    ['Fakta memberi arah, pertanyaan memberi kedalaman, kisah memberi makna. Sampai jumpa.', 'Facts give direction, questions give depth, stories give meaning. See you soon.'],
    ['Ada topik yang ingin kamu dengar besok? Simpan di Rategoan, dan Pitutur akan merangkainya.', 'Any topic you would like to hear tomorrow? Save it in Rategoan, and Pitutur will weave it.'],
    ['Menarik. Apakah masih berlaku hari ini?', 'Interesting. Does it still hold today?'],
    ['Menarik. Tapi apakah masih berlaku hari ini?', 'Interesting. But does it still hold today?'],
    ['Data ini dari pustaka lokal Rategoan, bisa dicek kapan saja.', 'This data comes from the Rategoan local library and can be checked anytime.'],
    ['Catatan yang adil. Data ini dari pustaka lokal Rategoan, bisa dicek kapan saja.', 'A fair note. This data comes from the Rategoan local library, verifiable anytime.'],
    ['Kesimpulan hari ini: ', 'In conclusion today: '],
    ['Oke, apa pelajaran yang bisa kita pakai hari ini?', 'So, what lesson can we use today?'],
    ['Apa pelajaran yang bisa dipakai hari ini?', 'What lesson can we use today?'],
    ['Prinsipnya bertahan, caranya yang berubah.', 'The principle endures; the method changes.'],
    ['Pelajarannya sederhana. Prinsip bertahan, cara berubah. Yang penting mau belajar.', 'The lesson is simple. Principles endure, methods change. What matters is the will to learn.'],
    ['Pelajarannya sederhana. Ambil satu poin, praktikkan.', 'The lesson is simple. Take one point and practice it.'],
    ['Serius?', 'Seriously?'], ['Wah, lanjut.', 'Wow, go on.'], ['Hmm, menarik.', 'Hmm, interesting.'], ['Oke, terus?', 'Okay, and then?'],
    ['Oke, aku ikut.', 'Okay, I am with you.'], ['Masuk akal.', 'That makes sense.'], ['Sip, dicatat.', 'Got it, noted.'], ['Baik, terus.', 'Alright, continue.'],
    ['Ada kisah di balik ini.', 'There is a story behind this.'], ['Ini bagian favoritku.', 'This is my favorite part.'], ['Pelajaran pelan-pelan.', 'Lessons, slowly.'],
    ['Intinya sederhana: yang diulang akan menempel.', 'Simply put: what is repeated will stick.'],
    ['Mulai dari satu kebiasaan kecil, konsisten lebih penting daripada sempurna.', 'Start with one small habit; consistency matters more than perfection.'],
    ['Karena keputusan hari ini menyusun hasil minggu depan.', 'Because today\'s decisions shape next week\'s results.'],
    ['Yang bertahan biasanya prinsipnya, bukan detailnya.', 'What endures is usually the principle, not the detail.'],
    ['Bayangkan ini seperti menanam. Hasilnya tidak sehari, tapi pasti kelihatan.', 'Imagine planting. Results are not overnight, but they will show.'],
    ['Orang sering tahu, tapi jarang mengulang. Padahal mengulang itu kuncinya.', 'People often know, but rarely repeat. Yet repetition is the key.'],
    ['Ceritanya sederhana: sedikit demi sedikit, lama-lama jadi biasa.', 'The story is simple: little by little, it becomes habit.'],
    ['Kalau hanya didengar sekali, cepat hilang. Kalau dipraktikkan, jadi milikmu.', 'Heard once, it fades fast. Practiced, it becomes yours.'],
    ['Ambil satu poin, coba hari ini.', 'Take one point and try it today.'],
    ['Jangan hafalkan semua. Pilih satu, kerjakan.', 'Do not memorize everything. Pick one and do it.'],
    ['Siaran ini cukup jika satu ide ikut pulang bersamamu.', 'This broadcast is enough if one idea goes home with you.'],
    ['Intinya apa, Warta?', 'What is the core, Warta?'],
    ['Satu hal yang wajib diingat?', 'One thing we must remember?'],
    ['Kenapa ini penting?', 'Why does this matter?'],
    ['Contoh sederhananya?', 'A simple example?'],
    ['Kalau dipraktikkan hari ini, mulai dari mana?', 'If we practice today, where do we start?'],
    ['Bagian mana yang paling sering dilupakan orang?', 'Which part do people forget most often?'],
    ['Apakah ini masih relevan di situasi kita sekarang?', 'Is this still relevant to our situation now?'],
    ['Ada risiko kalau poin ini diabaikan?', 'Is there a risk if this point is ignored?'],
    ['Bisa disederhanakan dalam satu kalimat?', 'Can this be simplified into one sentence?'],
    ['Siapa yang paling butuh mendengar ini?', 'Who most needs to hear this?'],
    ['Kelas frasa singkat.', 'A short phrase class.'], ['Frasa hari ini: ', "Today's phrase: "], ['Artinya: ', 'It means: '],
    ['Sekarang ulangi pelan-pelan. ', 'Now repeat it slowly. '], ['Bagus. Sedikit demi sedikit lama menjadi bukit.', 'Well done. Little by little becomes a mountain over time.'],
    ['Coba ulangi pelan-pelan.', 'Try repeating it slowly.'],
    ['Ulangi: ', 'Repeat: '],
    ['Sumber Koleksi dimatikan. Nyalakan kembali untuk review audio simpananmu.', 'Collection source is off. Turn it back on for audio reviews of your saves.'],
    ['Koleksimu masih kosong. Simpan jawaban penting di Rategoan, lalu kembali ke sini.', 'Your collection is still empty. Save important answers in Rategoan, then come back here.'],
    ['Pitutur akan membacakan ulang simpananmu sebagai review audio, supaya ingatanmu tetap segar.', 'Pitutur will read your saves back as an audio review, so your memory stays fresh.'],
    ['Pitutur akan membacakan ulang simpananmu sebagai review audio.', 'Pitutur will read your saves back as an audio review.'],
    ['Review Koleksi. Dengarkan baik-baik: ', 'Collection Review. Listen carefully: '],
    ['Review Koleksi hari ini. ', 'Today is a Collection Review. '],
    ['Saatnya review koleksi.', 'Time for a collection review.'],
    ['Dengarkan baik-baik simpanan ini.', 'Listen carefully to this save.'],
    ['Coba jawab dalam hati. Apa intinya?', 'Answer in your heart. What is the core?'],
    ['Coba pendengar jawab dulu dalam hati. Warta, apa intinya?', 'Let listeners answer in their hearts first. Warta, what is the core?'],
    ['Intinya: ', 'The core: '],
    ['Warta, kenapa ini penting untuk diingat?', 'Warta, why is this important to remember?'],
    ['Karena yang diulang akan menempel. ', 'Because repetition makes it stick. '],
    ['Aku punya cara ingat yang mudah. Bayangkan ini sebagai cerita, bukan hafalan.', 'I have an easy way to remember. Imagine this as a story, not memorization.'],
    ['Siap. Fokus ke poin pentingnya.', 'Ready. Focus on the important points.'],
    ['Siap. Tolong yang penting saja, Warta.', 'Ready. Just the important parts, Warta.'],
    ['Sampai di sini dulu. Sisa materi siap di siaran berikutnya.', 'We stop here for now. The rest is ready in the next broadcast.'],
    ['Sampai di sini. Sisa materi siap di siaran berikutnya.', 'We stop here. The rest is ready in the next broadcast.'],
    ['Istirahat sebentar. Nanti kita lanjut.', 'A short break. We will continue later.'],
    ['Istirahat sebentar, lalu lanjut.', 'A short break, then continue.'],
    ['Siaran berikutnya akan mengulang dari awal bila materi ini dipilih lagi.', 'The next broadcast will restart from the beginning if this material is chosen again.'],
    ['Keduanya boleh. Yang penting satu ide ikut dipraktikkan.', 'Either works. What matters is practicing one idea.'],
    ['Kita ulang dari awal, atau pindah materi?', 'Shall we restart from the beginning, or switch material?'],
    ['Ulang dari awal, atau ganti materi?', 'Restart from the beginning, or switch material?'],
    ['Satu hal yang paling menempel buatmu?', 'What is the one thing that sticks with you most?'],
    ['Dokumen ini sudah tidak tersedia, mungkin sudah dihapus.', 'This document is no longer available; it may have been deleted.']
  ];
