export default [
  ['Selamat pagi', 'Sugeng enjing'],
  ['Selamat siang', 'Sugeng siang'],
  ['Selamat sore', 'Sugeng sonten'],
  ['Selamat malam', 'Sugeng ndalu'],
  ['Mari kita mulai dengan satu fakta yang layak diingat hari ini.', 'Ayo miwiti karo siji fakta sing pantes elinga dina iki.'],
  ['Kita buka siaran dengan hal yang sederhana, tapi tajam.', 'Kita mbukak siaran karo bab sing prasaja, nanging landhep.'],
  ['Mari kita bahas satu materi singkat.', 'Ayo rembugan siji materi cekak.'],
  ['Cukup satu yang menempel. Sisanya bisa nanti.', 'Cekap siji sing nempel. Sisane mengko wae.'],
  ['Siaran selesai. Yang penting ikut dalam keputusan hari ini.', 'Siaran rampung. Sing penting mlebu ing putusan dina iki.'],
  ['Siaran ini cukup jika satu ide ikut pulang bersamamu.', 'Siaran iki cukup menawa siji gagasan mbalik karo kowe.'],
  ['Ambil satu poin. Coba hari ini, jangan besok.', 'Jupuk siji poin. Coba dina iki, aja sesuk.'],
  ['Tidak perlu hafal semua. Pilih satu, kerjakan sampai terasa.', 'Ora perlu ngapalake kabeh. Pilih siji, garap nganti kroso.'],
  ['Tutup dengan tindakan kecil. Itu yang membuat materi hidup.', 'Tutup karo tumindak cilik. Kuwi sing nggawe materi urip.'],
  ['Yang menonjol: ', 'Sing njendhel: '],
  ['Pegangan singkatnya: ', 'Pegangan cekake: '],
  ['Intinya: ', 'Intine: '],
  ['Simpan ini: ', 'Simpen iki: '],
  ['Intinya apa, Warta?', 'Intine apa, Warta?'],
  ['Satu hal yang wajib dibawa pulang?', 'Siji bab sing kudu digawa mulih?'],
  ['Kenapa ini penting buat pendengar?', 'Kok iki penting kanggo pamireng?'],
  ['Contoh sederhananya seperti apa?', 'Conto prasajane kaya apa?'],
  ['Hmm, bagian ini layak dicatat.', 'Hmm, bagean iki pantes dicathet.'],
  ['Oke, aku ikut alurnya dulu.', 'Oke, aku nuruti alure dhisik.'],
  ['Ini baru. Tunggu, aku cerna sebentar.', 'Iki anyar. Enteni, aku cerna sedhela.'],
  ['Masuk akal, tapi aku ingin dengar lanjutannya.', 'Masuk akal, nanging aku pengin ngrungokake terusané.'],
  ['Baik, satu poin lagi dari kamu.', 'Becik, siji poin maneh saka kowe.'],
  ['Pelan-pelan. Aku catat yang penting saja.', 'Alon-alon. Aku cathet sing penting wae.'],
  ['Oh, begitu. Lanjut, Warta.', 'Oh, ngono. Terusna, Warta.'],
  ['Satu hal lagi yang sering terlewat.', 'Siji bab maneh sing kerep keliwat.'],
  ['Kalau kita geser sedikit ke sisi lain,', 'Menawa kita geser sethithik menyang sisi liya,'],
  ['Masih ada potongan yang menentukan.', 'Isih ana potongan sing nentokake.'],
  ['Sekarang yang biasanya orang lewatkan:', 'Saiki sing biasane wong nglirwakake:'],
  ['Tambahan singkat, tapi penting:', 'Tambahan cekak, nanging penting:'],
  ['Dan ini yang membuatnya beda:', 'Lan iki sing ndadekake beda:'],
  ['Kalau ini dipraktikkan hari ini, langkah pertamanya apa?', 'Menawa iki dilakoni dina iki, langkah kapisane apa?'],
  ['Bagian mana yang paling sering dilupakan orang?', 'Bagean endi sing paling kerep dilalekake wong?'],
  ['Apakah ini masih relevan di situasi kita sekarang?', 'Apa iki isih relevan ing kahanan kita saiki?'],
  ['Ada risiko nyata kalau poin ini diabaikan?', 'Ana risiko nyata menawa poin iki dilirwakake?'],
  ['Bisa kamu sederhanakan dalam satu kalimat?', 'Bisa kowe prasajakake ing siji ukara?'],
  ['Siapa yang paling butuh mendengar ini duluan?', 'Sapa sing paling butuh ngrungokake iki dhisik?'],
  ['Ambil satu fakta yang baru saja disebut. Itu cukup untuk sesi ini.', 'Jupuk siji fakta sing lagi wae kasebut. Kuwi cukup kanggo sesi iki.'],
  ['Yang menempel biasanya yang diulang dengan sadar, bukan yang paling panjang.', 'Sing nempel biasane sing diulang kanthi eling, dudu sing paling dawa.'],
  ['Simpan dulu intinya. Detail bisa dibuka di siaran berikutnya.', 'Simpen dhisik intine. Rincian bisa dibukak ing siaran sabanjure.'],
  ['Satu ide cukup. Kerjakan sampai terasa.', 'Siji gagasan cukup. Garap nganti kroso.'],
  ['Bayangkan menanam. Hasilnya tidak datang sehari, tapi jejaknya pasti kelihatan.', 'Bayangna nandur. Asile ora teka sedina, nanging jejake mesti katon.'],
  ['Banyak orang sudah tahu, tapi jarang mengulang. Padahal mengulang itu jembatannya.', 'Akeh wong wis ngerti, nanging arang ngulang. Padahal ngulang kuwi jembatane.'],
  ['Ceritanya sederhana: sedikit demi sedikit, lama-lama jadi biasa.', 'Critane prasaja: sethithik-sethithik, suwe-suwe dadi biyasa.'],
  ['Didengar sekali, mudah hilang. Dipraktikkan, jadi milikmu sendiri.', 'Dirungokake sepisan, gampang ilang. Dilakoni, dadi duweke dhewe.'],
  ['Seperti belajar jalur pulang: yang sering dilalui, tidak perlu peta lagi.', 'Kaya sinau dalan mulih: sing kerep diliwati, ora perlu peta maneh.'],
  ['Dari catatan pengembangan.', 'Saka cathetan pangembangan.'],
  ['Dari catatan pengembangan: ', 'Saka cathetan pangembangan: '],
  ['Tentang ', 'Babagan '],
  ['Hari ini ', 'Dina iki '],
  ['Ibu kotanya ', 'Kutha krajane '],
  ['Populasinya sekitar ', 'Cacah jiwane kira-kira '],
  ['Populasinya tercatat sekitar ', 'Cacah jiwane kacathet kira-kira '],
  ['Mata uangnya ', 'Dhuwite '],
  ['Bahasanya ', 'Basane '],
  ['Sistem pemerintahannya ', 'Sistem pamaréntahane '],
  ['Rumah bagi ', 'Omah kanggo '],
  ['Serius?', 'Tenan?'],
  ['Wah, lanjut.', 'Wah, terusna.'],
  ['Hmm, menarik.', 'Hmm, narik.'],
  ['Oke, terus?', 'Oke, banjur?'],
  ['Ada kisah di balik ini.', 'Ana kisah ing mburi iki.'],
  ['Ini bagian favoritku.', 'Iki bagean favoritku.'],
  ['Pelajaran pelan-pelan.', 'Pelajaran alon-alon.'],
  ['Intinya: ', 'Intine: ']
];
