export default [
    ['Selamat pagi', 'Wilujeng enjing'], ['Selamat siang', 'Wilujeng siang'], ['Selamat sore', 'Wilujeng sonten'], ['Selamat malam', 'Wilujeng wengi'],
    ['Hari ini ', 'Dinten ieu '],
    ['Masih segar di ingatan, kemarin kita membahas ', 'Masih seger keneh dina ingetan, kamari urang ngabahas '],
    ['. Hari ini kita lanjut melangkah.', '. Dinten ieu urang teras lengkah.'],
    ['Dari catatan pengembangan: ', 'Ti catetan pamekaran: '],
    ['Pustaka dataries belum terhubung di halaman ini.', 'Pustaka dataries teu acan nyambung di kaca ieu.'],
    ['Kisah yang kuat. Tapi konteks zamannya berbeda, apakah pelajarannya masih relevan?', 'Kisah anu kuat. Tapi konteks jamanana beda, naha pelajaranana masih relevan?'],
    ['Justru itu ujiannya. Prinsipnya bertahan, caranya yang berubah.', 'Justru eta ujianana. Prinsipna tetep, carana anu robih.'],
    ['Fakta memberi arah, pertanyaan memberi kedalaman, kisah memberi makna. Sampai jumpa.', 'Fakta masihan arah, patarosan masihan jero, kisah masihan makna. Tepang deui.'],
    ['Ada topik yang ingin kamu dengar besok? Simpan di Rategoan, dan Pitutur akan merangkainya.', 'Aya topik anu hoyong didangu isukan? Simpen di Rategoan, teras Pitutur bakal ngarangkena.'],
    ['Menarik. Tapi apakah masih berlaku hari ini?', 'Narik. Tapi naha masih berlaku dinten ieu?'],
    ['Catatan yang adil. Data ini dari pustaka lokal Rategoan, bisa dicek kapan saja.', 'Catetan anu adil. Data ieu ti pustaka lokal Rategoan, tiasa dicek iraha wae.'],
    ['Kesimpulan hari ini: ', 'Kesimpulan dinten ieu: '],
    ['Oke, apa pelajaran yang bisa kita pakai hari ini?', 'Oke, naon pelajaran anu tiasa urang pakai dinten ieu?'],
    ['Prinsipnya bertahan, caranya yang berubah.', 'Prinsipna tetep, carana anu robih.'],
    ['Pelajarannya sederhana. Prinsip bertahan, cara berubah. Yang penting mau belajar.', 'Pelajaranana saderhana. Prinsip tetep, cara robih. Anu penting daek diajar.'],
    ['Warta, sebentar. Apakah itu masih relevan hari ini? Aku ragu pendengar langsung percaya.', 'Warta, sakedap. Naha masih relevan dinten ieu? Abi ragu pendengar langsung percaya.'],
    ['Ragu itu sehat, Tanya. Data ini dari pustaka lokal Rategoan, jadi bisa diverifikasi kapan saja.', 'Ragu teh sehat, Tanya. Data ieu ti pustaka lokal Rategoan, janten tiasa diverifikasi iraha wae.'],
    ['Ini mengingatkanku pada sebuah kisah.', 'Ieu ngingetkeun abi kana hiji kisah.'],
    ['Kisah, kalau begitu, apa pelajaran yang bisa kita ambil?', 'Kisah, upami kitu, naon pelajaran anu tiasa urang candak?'],
    ['Serius?', 'Saenyana?'], ['Wah, lanjut.', 'Wah, teraskeun.'], ['Hmm, menarik.', 'Hmm, narik.'], ['Oke, terus?', 'Oke, teras?'],
    ['Ada kisah di balik ini.', 'Aya kisah di balik ieu.'], ['Ini bagian favoritku.', 'Ieu bagian karesep abdi.'], ['Pelajaran pelan-pelan.', 'Pelajaran laun-laun.'],
    ['Kelas frasa singkat.', 'Kelas frasa pondok.'], ['Frasa hari ini: ', 'Frasa dinten ieu: '], ['Artinya: ', 'Hartosna: '],
    ['Sekarang ulangi pelan-pelan. ', 'Ayeuna ulangan alon-alon. '], ['Bagus. Sedikit demi sedikit lama menjadi bukit.', 'Sae. Saeutik-saeutik lila-lila jadi gunung.'],
    ['Intinya: ', 'Intina: ']
  ];
